"""Standard-library Python source membership; callers own hashes and run receipts.

Generated bytecode caches are omitted. Linked/nonregular entries are refused even
when they are not Python sources, matching the existing native source policy.
"""

from __future__ import annotations

from pathlib import Path


class SourceMembershipError(ValueError):
    """A source tree cannot be inventoried without following unsafe entries."""


def python_members(directory: Path, *, label: str = "Python") -> dict[str, Path]:
    """Return sorted relative Python names and their ordinary resolved file paths."""
    directory = Path(directory)
    if directory.is_symlink() or not directory.is_dir():
        raise SourceMembershipError(f"{label} source directory is absent or symlinked: {directory}")
    inputs = {}
    for member in sorted(directory.rglob("*")):
        relative = member.relative_to(directory)
        if "__pycache__" in relative.parts:
            continue
        if member.is_symlink() or not (member.is_file() or member.is_dir()):
            raise SourceMembershipError(f"{label} implementation contains symlinked or nonregular entries: {member}")
        if member.is_file() and member.suffix == ".py":
            inputs[relative.as_posix()] = member.resolve()
    return inputs
