"""Ingest OpenBLAS RISC-V vector kernels (``kernel/riscv64/``).

OpenBLAS ships hand- and generator-written RVV kernels in four filename families:
``*_rvv.c`` (RVV 1.0 intrinsics), ``*_vector*.c`` (older intrinsic spellings),
``*_kernel_<MR>x<NR>_zvl{128,256}b.c`` (autogenerated GEMM/TRMM register-blocked kernels)
and ``*_c910v.c`` (T-Head C910). Scalar fallbacks (e.g. plain ``amax.c``) are skipped and
counted. The leading letter(s) of a GEMM-family filename encode the dtype
(``s/d/c/z/sb/sh``); BLAS1/2 kernels are precision-generic via ``DOUBLE`` macros, so their
dtype is honestly ``unknown``. Pure text parsing — nothing is compiled or executed.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterator

from merlin.kernels.types import NormalizedKernel

_VECTOR_SUFFIXES = ("_rvv.c", "_c910v.c")
_KERNEL_RE = re.compile(
    r"^(?P<prefix>[a-z0-9]+?)_?kernel_(?P<mr>\d+)x(?P<nr>\d+)_(?:zvl(?P<vlen>\d+)b|c910v)\.c$")

# dtype letter(s) for the autogenerated GEMM family, longest-first.
_DTYPE_PREFIX = (("sb", "bf16"), ("sh", "f16"), ("s", "f32"), ("d", "f64"),
                 ("c", "c32"), ("z", "c64"))

# BLAS op roots, longest/most-specific first. ncopy/tcopy are the *pack* routines.
_OP_ROOTS = (
    ("gemm_ncopy", "pack"), ("gemm_tcopy", "pack"), ("gemm_beta", "scal"),
    ("omatcopy", "transpose"), ("trmm", "trmm"), ("gemv", "gemv"), ("gemm", "gemm"),
    ("symv", "symv"), ("hemv", "hemv"), ("axpby", "axpby"), ("axpy", "axpy"),
    ("amax", "amax"), ("amin", "amin"), ("asum", "asum"), ("nrm2", "nrm2"),
    ("copy", "copy"), ("dot", "dot"), ("rotm", "rot"), ("rot", "rot"),
    ("scal", "scal"), ("swap", "swap"), ("sum", "sum"), ("max", "max"), ("min", "min"),
)


def _parse_gemm_kernel(name: str) -> tuple[str, str, dict] | None:
    """Parse ``dgemm_kernel_8x4_zvl128b.c``-style names -> (op, dtype, shape)."""
    m = _KERNEL_RE.match(name)
    if not m:
        return None
    prefix = m.group("prefix")  # e.g. "dgemm", "ztrmm", "sbgemm", "ztrmm" (or "ztrmmkernel")
    dtype = "unknown"
    for letters, dt in _DTYPE_PREFIX:
        if prefix.startswith(letters) and len(prefix) > len(letters):
            dtype, prefix = dt, prefix[len(letters):]
            break
    op = next((op for root, op in _OP_ROOTS if prefix.startswith(root)), prefix or "unknown")
    shape: dict = {"MR": int(m.group("mr")), "NR": int(m.group("nr"))}
    if m.group("vlen"):
        shape["vlen_bits"] = int(m.group("vlen"))
    return op, dtype, shape


def _parse_blas(name: str) -> tuple[str, str] | None:
    """Parse ``zaxpy_rvv.c`` / ``gemv_n_vector.c``-style names -> (op, dtype)."""
    stem = re.sub(r"_(?:rvv|c910v|vector(?:_v2)?)(?=\.c$|_)", "", name)[:-2].rstrip("_")
    # index variants (iamax/izamin) reduce to the same decision as the base op
    stem = re.sub(r"^i", "", stem)
    dtype = "unknown"
    for letters, dt in (("sb", "bf16"), ("z", "c64"), ("ds", "f32")):
        rest = stem[len(letters):]
        if stem.startswith(letters) and any(rest.startswith(root) for root, _ in _OP_ROOTS):
            dtype, stem = dt, rest
            break
    op = next((op for root, op in _OP_ROOTS if stem.startswith(root)), None)
    return (op, dtype) if op else (stem.split("_")[0] or "unknown", dtype)


def _is_vector_kernel(name: str) -> bool:
    return (name.endswith(_VECTOR_SUFFIXES) or "_vector" in name
            or bool(_KERNEL_RE.match(name)))


def ingest_openblas(repo: str, target: str = "rvv", limit: int | None = None,
                    diagnostics: dict | None = None) -> Iterator[NormalizedKernel]:
    """Yield NormalizedKernels for OpenBLAS vector kernels under ``repo``.

    Globs ``kernel/riscv64/*.c``; scalar fallbacks are skipped (counted in
    ``diagnostics['scalar_skipped']`` when a dict is passed).
    """
    root = Path(repo)
    kdir = root / "kernel" / "riscv64"
    if not kdir.is_dir():  # tolerate being pointed at the kernel dir itself
        kdir = root
    count = scalar_skipped = 0
    for path in sorted(kdir.glob("*.c")):
        name = path.name
        if not _is_vector_kernel(name):
            scalar_skipped += 1
            continue
        parsed = _parse_gemm_kernel(name)
        if parsed:
            op, dtype, shape = parsed
        else:
            op, dtype = _parse_blas(name)
            shape = {}
        try:
            rel = str(path.relative_to(root))
        except ValueError:
            rel = str(path)
        yield NormalizedKernel(
            source="openblas", target=target, path=rel, op=op, dtype=dtype, shape=shape,
            raw_text=path.read_text(encoding="utf-8", errors="replace"),
        )
        count += 1
        if limit is not None and count >= limit:
            break
    if diagnostics is not None:
        diagnostics["scalar_skipped"] = scalar_skipped
        diagnostics["vector_kernels"] = count
