"""CIRCT facts -> one distilled RTL_DIGEST.md (so the CIRCT arm reads ONE spec sheet, not 55 RTL files).

The merlin+CIRCT arm's biggest token sink in abc4 was *exploration*: ~67 find/grep/cat commands crawling
the RTL + headers. This is exactly what CIRCT is for: it already statically analyzed the elaborated RTL
into facts.json. This renders those facts as a human-readable digest — module map, the full ISA funct
table, the memory map, datapaths, dataflow, and the legal-sequencing rules — everything the agent would
otherwise grep the hardware for. Reading one digest instead of crawling 55 Scala files is the CIRCT arm's
"the RTL was pre-analyzed for you" advantage (a from-scratch/no-CIRCT path cannot get this).

ANTI-CHEAT: the digest is RTL-derived STRUCTURAL truth (what the hardware IS) — module hierarchy, port
widths, capacities, the legal funct set. It contains NO lowering answer: no command buffers, no goldens,
no per-capsule instruction sequences. Same line facts.json already sits on. CIRCT-arm-only (the no-CIRCT
arm explores the RTL itself) — which preserves the merlin-vs-merlin+CIRCT distinction.

Usage: python -m merlin.targetgen.rtl.gen_rtl_digest [--facts <facts.json>] [--out RTL_DIGEST.md]
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

_DEFAULT_FACTS = (Path(__file__).resolve().parents[5]
                  / "merlin/targets/gemmini/contracts/rtl_facts/facts.json")


def generate(facts: dict) -> str:
    f = facts["facts"]
    src = f.get("source", {})
    gen = facts.get("generator", {})
    fd = next(i for i in f["interfaces"] if i.get("name") == "funct_decode_table")
    names = {int(k): v for k, v in fd["names"].items()}
    mesh = next((a for a in f.get("arrays", []) if a.get("name") == "mesh"), {})
    mems = {m["name"]: m for m in f.get("memories", [])}
    spad, acc = mems.get("scratchpad", {}), mems.get("accumulator", {})

    L = []
    L.append("# RTL_DIGEST — Gemmini accelerator, distilled from the RTL by CIRCT (read this, not the RTL)")
    L.append("")
    L.append("> Generated by `merlin.targetgen.rtl.gen_rtl_digest` from `facts.json`, which CIRCT extracted")
    L.append(f"> from the elaborated RTL (`{src.get('kind')}`, config `{src.get('config')}`).")
    L.append("> This is the hardware's structural truth. It does NOT contain any lowering/answer — you still")
    L.append("> write the op algorithm. Build your encoder with `gen_isa_module`; consult this for the rest.")
    L.append("")
    L.append("## Module map (what to target)")
    for i in f.get("interfaces", []):
        L.append(f"- **{i.get('name')}** — {i.get('evidence','')}")
    L.append("")
    L.append("## Compute fabric")
    L.append(f"- Systolic mesh: **{mesh.get('rows')}×{mesh.get('cols')}** PEs ({mesh.get('tiles')} tiles, "
             f"square={mesh.get('square')}). **Tile every matmul operand to DIM={mesh.get('rows')}.**")
    for d in f.get("datapaths", []):
        L.append(f"- datapath **{d.get('name')}**: dtype `{d.get('dtype')}` ({d.get('evidence')})")
    L.append("")
    L.append("## Memory map (respect these capacities)")
    if spad:
        L.append(f"- **Scratchpad**: {spad.get('banks')} banks × depth {spad.get('depth')} rows × "
                 f"{spad.get('row_elems')} elems × {spad.get('elem_bits')}b = {spad.get('bytes')} B. Inputs live here.")
    if acc:
        L.append(f"- **Accumulator**: {acc.get('banks')} banks × depth {acc.get('depth')} × {acc.get('lanes')} "
                 f"lanes × {acc.get('lane_bits')}b = {acc.get('bytes')} B. Partial sums live here.")
    L.append("")
    L.append(f"## ISA — custom opcode `{hex(fd['custom_opcode'])}`, funct3 `{fd['funct3']}` "
             f"({len(names)} legal funct codes)")
    L.append("| funct | name | role |")
    L.append("|---|---|---|")
    for c in sorted(names):
        n = names[c]
        role = ("config" if "CONFIG" in n else "compute" if "COMPUTE" in n else
                "load" if "LOAD" in n else "store" if "STORE" in n else
                "loop" if "LOOP" in n else "control")
        L.append(f"| {c} | `{n}` | {role} |")
    L.append("")
    L.append("## Legal-sequencing rules (the structural invariants the hardware enforces)")
    L.append("1. **Config before use** — emit the relevant `*CONFIG*` funct before the first `COMPUTE_*` "
             "(exec config) and before the first `STORE` (store config). Violations are rejected.")
    L.append("2. **Decode-clean** — only the funct codes above are legal; any other custom-3 funct is an "
             "UNKNOWN instruction the RTL rejects.")
    L.append("3. **Movement** (`LOAD`→`STORE`, no `COMPUTE`); **matmul** (`LOAD`/`PRELOAD`→`COMPUTE`→`STORE`); "
             "**conv** ⇒ im2col to 2D then matmul. Tile to DIM; keep residency within the capacities above.")
    L.append("")
    L.append(f"_Provenance: {gen.get('method','')[:200]}_")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--facts", default=str(_DEFAULT_FACTS))
    ap.add_argument("--out", default="")
    a = ap.parse_args(argv)
    md = generate(json.loads(Path(a.facts).read_text()))
    if a.out:
        Path(a.out).write_text(md)
        print(f"wrote {a.out} ({len(md.splitlines())} lines)")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
