#ifndef IREE_GEMMINI_COMPILER_DIALECT_GEMMINI_IR_GEMMINIDIALECT_H_
#define IREE_GEMMINI_COMPILER_DIALECT_GEMMINI_IR_GEMMINIDIALECT_H_

#include "mlir/IR/Dialect.h"

#include "compiler/src/merlin/Dialect/Gemmini/IR/GemminiDialect.h.inc"

#endif // IREE_GEMMINI_COMPILER_DIALECT_GEMMINI_IR_GEMMINIDIALECT_H_
