#!/usr/bin/env python3
"""Generate the instruction-surface OPU target's capability contract from RTL facts + its residual.

The contract is a GENERATED product, regenerated by running this script — never hand-edited. Two things
make that worth a script rather than a one-off: the facts come from the sibling command-buffer target's
state manifest (the same silicon, introspected by the same reader, since a second name for one unit does
not give it a second set of datapaths), and the exposure/geometry declarations come from the residual, so
the two sources have to be joined somewhere reproducible.

The fact source is named on the command line rather than inferred, because "which physical unit are these
facts about" is precisely the question a wrong answer here would silently answer for us.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import yaml

from merlin.common.paths import artifacts_dir, merlin_dir
from merlin.common.yaml import write_yaml
from merlin.targetgen import capability_manifests as cm

_TARGET_DIR = merlin_dir() / "experiments" / "capsule_bench" / "targets"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--target-dir",
        default="saturn_opu_rvv",  # target-ok: this script generates that one target's contract
        help="the capsule-bench target directory holding the descriptor + residual",
    )
    ap.add_argument(
        "--facts-from",
        required=True,
        help="the mlc target whose OPU state manifest the facts are read from (the same "
        "physical unit this surface drives)",
    )
    a = ap.parse_args(argv)

    tdir = _TARGET_DIR / a.target_dir
    descriptor = yaml.safe_load((tdir / "target_experiment.yaml").read_text(encoding="utf-8"))
    residual = yaml.safe_load((tdir / "manifest_residual.yaml").read_text(encoding="utf-8"))

    from merlin.targetgen.rtl import spatial_introspect as si

    facts = si.build_fact_bundle(a.facts_from)
    required = ("tile_dim", "mrf_depth", "element_widths", "dtypes", "fma_latency", "op_categories", "accum_kind")
    missing = [key for key in required if not (facts.get("fields") or {}).get(key, {}).get("derived")]
    inputs = facts.get("inputs") or {}
    state_manifest = Path(str(inputs.get("state_manifest") or ""))
    hw_mlir = Path(str(inputs.get("hw_mlir") or ""))
    if missing or not state_manifest.is_file() or not hw_mlir.is_file():
        # A partial bundle is not a capability contract. In particular, an available state manifest
        # without the matching HW MLIR cannot ground the FP8 datapath and its format uncertainty.
        print(
            f"REFUSED: incomplete grounded OPU facts for {a.facts_from!r}: "
            f"missing fields={missing}, state_manifest={state_manifest.is_file()}, "
            f"hw_mlir={hw_mlir.is_file()} ({facts.get('reason')})",
            file=sys.stderr,
        )
        return 2

    manifest = cm.derive_manifest(descriptor, facts, residual=residual)
    target = manifest.get("name") or residual.get("name")
    out = artifacts_dir() / "targets" / str(target) / "contracts" / "target_contract.yaml"
    write_yaml(
        out,
        manifest,
        header=(
            f"GENERATED by build_tools/scripts/{Path(__file__).name} from {a.facts_from} OPU facts + "
            f"{a.target_dir}/manifest_residual.yaml — regenerate, never hand-edit"
        ),
    )

    def _digest(path: Path) -> str:
        return hashlib.sha256(path.read_bytes()).hexdigest()

    receipt = {
        "schema_version": 1,
        "target": str(target),
        "facts_from": a.facts_from,
        "derivation": "spatial_introspect state-manifest + HW MLIR, then capability_manifests.derive_manifest",
        "generator_sources_sha256": {
            "entrypoint": _digest(Path(__file__)),
            "spatial_introspect": _digest(Path(si.__file__)),
            "capability_manifests": _digest(Path(cm.__file__)),
        },
        "inputs": {
            label: {"path": str(path), "sha256": _digest(path)}
            for label, path in (
                ("descriptor", tdir / "target_experiment.yaml"),
                ("residual", tdir / "manifest_residual.yaml"),
                ("state_manifest", state_manifest),
                ("hw_mlir", hw_mlir),
            )
        },
        "output_sha256": _digest(out),
        # MLC's cached arc has no machine-readable source commit. Hashing the exact extracted inputs
        # makes this generation reproducible but does NOT prove that they came from the declared RTL
        # hardware pin, nor does it provide numerical or L3 certification.
        "hardware_pin_status": "unverified_cached_arc_source_revision",
    }
    receipt_path = out.with_suffix(".generation.json")
    receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    unit = (manifest.get("compute_units") or [{}])[0]
    print(f"wrote {out}")
    print(f"wrote {receipt_path} (cached arc source revision UNVERIFIED)")
    print(
        f"  target={target} endpoint={manifest.get('endpoint_kind')} "
        f"exposure={unit.get('exposure')} matrix_unit={unit.get('matrix_unit')} "
        f"hardware_config={unit.get('hardware_config')} dtypes={unit.get('dtypes')}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
