#!/usr/bin/env python3
"""Living package docs: derive docs/reference/module_index.md from the merlin package's __init__ docstrings,
and lint package AGENT.md for staleness. Single source of truth = the code (mirrors gen_cli_docs.py).

Usage:
  gen_package_docs.py            # (re)generate docs/reference/module_index.md
  gen_package_docs.py --check    # exit 1 if the index is stale, or an AGENT.md is missing/stale
"""
from __future__ import annotations

import ast
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PKG = ROOT / "merlin" / "python" / "merlin"
INDEX = ROOT / "docs" / "reference" / "module_index.md"

# Phrases that were copy-pasted boilerplate and misrepresent live code — must never reappear.
STALE_PHRASES = ("no real logic yet", "no real algorithms", "no real passes yet",
                 "todo stubs only at this stage", "placeholder modules with explicit todos")


def _first_docline(init: Path) -> str:
    """The docstring's first PARAGRAPH, unwrapped -- not its first physical line.

    Reading one line cut nine package purposes mid-sentence wherever the author had wrapped at 100
    columns: `merlin.mining` published "fork an iteration of the RVV codegen (a transform-dialect"
    to the module index and to its own AGENT.md, with the close paren and the verb on line two.
    """
    try:
        doc = ast.get_docstring(ast.parse(init.read_text(encoding="utf-8"))) or ""
    except Exception:
        doc = ""
    doc = doc.strip()
    if not doc:
        return "(no module docstring — add one)"
    para: list[str] = []
    for line in doc.splitlines():
        if not line.strip():
            break
        para.append(line.strip())
    text = " ".join(para)
    if len(text) > 200:
        cut = text.rfind(" ", 0, 200)
        text = text[:cut if cut > 0 else 200].rstrip(" ,;:") + "…"
    return text


def _packages() -> list[tuple[Path, Path]]:
    """(relative-dir, __init__path) for every importable package under merlin/, sorted."""
    return sorted(((init.parent.relative_to(PKG), init) for init in PKG.rglob("__init__.py")),
                  key=lambda t: str(t[0]))


def gen_index() -> str:
    out = [
        "# merlin package — module index (AUTO-GENERATED)",
        "",
        "Generated by `build_tools/scripts/gen_package_docs.py` from each package's `__init__.py`",
        "module docstring. **Do not edit by hand** — run the generator (it's `--check`ed by",
        "`check_structure.py`). One row per importable package; the purpose is the docstring's first line.",
        "",
        "| package | purpose |",
        "|---|---|",
    ]
    for rel, init in _packages():
        dotted = "merlin." + str(rel).replace(os.sep, ".") if str(rel) != "." else "merlin"
        purpose = _first_docline(init).replace("|", "\\|")
        out.append(f"| `{dotted}` | {purpose} |")
    return "\n".join(out) + "\n"


def _gen_agent_md(rel: Path) -> str:
    """Minimal AGENT.md for a package: Purpose (from __init__ docstring) + module list."""
    d = PKG / rel
    label = str(rel).replace(os.sep, "/")
    purpose = _first_docline(d / "__init__.py")
    mods = [f"- `{f.name}` — {_first_docline(f)}"
            for f in sorted(d.glob("*.py")) if f.name != "__init__.py"]
    subpkgs = sorted(s.name for s in d.iterdir() if s.is_dir() and (s / '__init__.py').is_file())
    body = [f"# AGENT.md — merlin/python/merlin/{label}", "", "## Purpose", "", purpose, ""]
    if mods:
        body += ["## Modules", "", *mods, ""]
    if subpkgs:
        body += ["## Subpackages", "", *[f"- `{s}/`" for s in subpkgs], ""]
    body += ["<!-- Purpose/Modules derived from docstrings via build_tools/scripts/gen_package_docs.py.",
             "     Add hand-written notes (invariants, gotchas) below. -->", ""]
    return "\n".join(body)


def _check_agent_md(errors: list[str]) -> None:
    for rel, init in _packages():
        agent = init.parent / "AGENT.md"
        label = "merlin." + str(rel).replace(os.sep, ".") if str(rel) != "." else "merlin"
        if not agent.is_file():
            errors.append(f"package {label}: missing AGENT.md")
            continue
        # The header names the package. Four survived a rename pointing at the old path -- mining/
        # still called itself rvvgen -- which is exactly the kind of drift a reader believes.
        want = "merlin/python/merlin" + (f"/{rel.as_posix()}" if str(rel) != "." else "")
        head = agent.read_text(encoding="utf-8").splitlines()[0]
        if want not in head:
            errors.append(f"package {label}: AGENT.md header says {head.strip()!r}, not {want!r}")
        low = agent.read_text(encoding="utf-8").lower()
        for ph in STALE_PHRASES:
            if ph in low:
                errors.append(f"package {label}: stale AGENT.md phrase {ph!r}")
        # The package docstring is what the generated module index publishes, so the same phrases must
        # not survive there either. Until 2026-09-14 only AGENT.md was read, and two packages with dozens
        # of importers still told every reader of the index "Scaffold package. No real logic yet."
        try:
            doc = (ast.get_docstring(ast.parse(init.read_text(encoding="utf-8"))) or "").lower()
        except SyntaxError:
            doc = ""
        for ph in STALE_PHRASES:
            if ph in doc:
                errors.append(f"package {label}: stale __init__ docstring phrase {ph!r}")


def main(argv: list[str]) -> int:
    idx = gen_index()
    if "--check" in argv:
        errors: list[str] = []
        cur = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
        if cur != idx:
            errors.append("docs/reference/module_index.md is stale — run build_tools/scripts/gen_package_docs.py")
        _check_agent_md(errors)
        if errors:
            sys.stderr.write("package-docs check FAILED:\n")
            for e in errors:
                sys.stderr.write(f"  - {e}\n")
            return 1
        print("package docs: OK")
        return 0
    INDEX.write_text(idx, encoding="utf-8")
    created = 0
    for rel, init in _packages():
        agent = init.parent / "AGENT.md"
        if not agent.is_file():
            agent.write_text(_gen_agent_md(rel), encoding="utf-8")
            created += 1
    print(f"wrote {INDEX.relative_to(ROOT)} ({len(_packages())} packages); "
          f"generated {created} missing AGENT.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
