#!/usr/bin/env python3
"""Generate the instruction-surface OPU target's capability contract from RTL facts + its residual.

The contract is a GENERATED product, regenerated by running this script — never hand-edited. Two things
make that worth a script rather than a one-off: the facts come from the sibling command-buffer target's
state manifest (the same silicon, introspected by the same reader, since a second name for one unit does
not give it a second set of datapaths), and the exposure/geometry declarations come from the residual, so
the two sources have to be joined somewhere reproducible.

The fact source is named on the command line rather than inferred, because "which physical unit are these
facts about" is precisely the question a wrong answer here would silently answer for us.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from merlin.common.paths import artifacts_dir, merlin_dir
from merlin.common.yaml import write_yaml
from merlin.targetgen import capability_manifests as cm

_TARGET_DIR = merlin_dir() / "experiments" / "capsule_bench" / "targets"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target-dir", default="saturn_opu_rvv",
                    help="the capsule-bench target directory holding the descriptor + residual")
    ap.add_argument("--facts-from", required=True,
                    help="the mlc target whose OPU state manifest the facts are read from (the same "
                         "physical unit this surface drives)")
    a = ap.parse_args(argv)

    tdir = _TARGET_DIR / a.target_dir
    descriptor = yaml.safe_load((tdir / "target_experiment.yaml").read_text(encoding="utf-8"))
    residual = yaml.safe_load((tdir / "manifest_residual.yaml").read_text(encoding="utf-8"))

    from merlin.targetgen.rtl import spatial_introspect as si
    facts = si.build_fact_bundle(a.facts_from)
    if not facts.get("n_derived"):
        # Fail closed: a hollow bundle would produce a contract with no datapaths and no geometry, which
        # reads exactly like a target that legitimately has none.
        print(f"REFUSED: no grounded OPU facts for {a.facts_from!r} ({facts.get('reason')}) — "
              f"build the arc model / set MERLIN_MLC_DIR", file=sys.stderr)
        return 2

    manifest = cm.derive_manifest(descriptor, facts, residual=residual)
    target = manifest.get("name") or residual.get("name")
    out = artifacts_dir() / "targets" / str(target) / "contracts" / "target_contract.yaml"
    write_yaml(out, manifest, header=(
        f"GENERATED by build_tools/scripts/{Path(__file__).name} from {a.facts_from} OPU facts + "
        f"{a.target_dir}/manifest_residual.yaml — regenerate, never hand-edit"))
    unit = (manifest.get("compute_units") or [{}])[0]
    print(f"wrote {out}")
    print(f"  target={target} endpoint={manifest.get('endpoint_kind')} "
          f"exposure={unit.get('exposure')} matrix_unit={unit.get('matrix_unit')} "
          f"hardware_config={unit.get('hardware_config')} dtypes={unit.get('dtypes')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
