"""Buddy-specific generated C ABI harnesses (not shared compiler semantics)."""

from __future__ import annotations

from merlin.mining import k1


def _native_harness_c(out_elems: int, out_lastdim: int, in_elems: int, param_elems: int, input_vals: list[int]) -> str:
    dump_cap = min(out_elems, 4096)
    in_init = ",".join(str(int(v)) for v in input_vals) or "0"
    return f"""/* Generated by merlin.baselines.buddy — buddy-native K1 harness. Do not edit. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <pthread.h>

typedef struct {{ void *a; void *al; int64_t off; int64_t sz[8]; int64_t st[8]; }} MR;
/* result (rank3), params (rank1), input (rank2) */
extern void _mlir_ciface_forward(MR *res, MR *params, MR *input);

#define OUT_ELEMS {out_elems}
#define OUT_LASTDIM {out_lastdim}
#define IN_ELEMS {in_elems}
#define PARAM_ELEMS {param_elems}L
#define DUMP_CAP {dump_cap}
#define K1_TIMEBASE_HZ {k1.K1_TIMEBASE_HZ}ULL
#define K1_CPU_HZ {k1.K1_CPU_HZ}ULL

static float OUT[OUT_ELEMS];
static int64_t IN[IN_ELEMS] = {{{in_init}}};

static inline uint64_t rd_time(void) {{ uint64_t t; __asm__ volatile("rdtime %0":"=r"(t)); return t; }}
static inline uint64_t rd_vlenb(void){{ uint64_t v; __asm__ volatile("csrr %0, vlenb":"=r"(v)); return v; }}
static uint64_t wall_ns(void){{ struct timespec ts; clock_gettime(CLOCK_MONOTONIC,&ts);
  return (uint64_t)ts.tv_sec*1000000000ULL+(uint64_t)ts.tv_nsec; }}

static const float *PARAMS;

static void *worker(void *arg){{
  (void)arg;
  printf("=== buddy_native vlenb=%llu ===\\n",(unsigned long long)rd_vlenb()); fflush(stdout);
  MR res={{0}}, par={{0}}, inp={{0}};
  res.a=res.al=OUT; res.off=0; res.sz[0]=1; res.sz[1]=OUT_ELEMS/OUT_LASTDIM; res.sz[2]=OUT_LASTDIM;
  res.st[0]=OUT_ELEMS; res.st[1]=OUT_LASTDIM; res.st[2]=1;
  par.a=par.al=(void*)PARAMS; par.off=0; par.sz[0]=PARAM_ELEMS; par.st[0]=1;
  inp.a=inp.al=IN; inp.off=0; inp.sz[0]=1; inp.sz[1]=IN_ELEMS; inp.st[0]=IN_ELEMS; inp.st[1]=1;
  uint64_t w0=wall_ns(), t0=rd_time();
  _mlir_ciface_forward(&res,&par,&inp);
  uint64_t t1=rd_time(), w1=wall_ns();
  /* buddy's forward ALLOCATES the result internally and the ciface stores the returned descriptor
   * into &res — so the data lives at res.al (buddy's aligned ptr), NOT our pre-passed OUT[]. Read
   * from res.al + res.off. */
  const float *R = (const float *)res.al;
  if (!R) {{ fprintf(stderr,"FAIL null result ptr\\n"); R = OUT; }}
  R += res.off;
  int k = OUT_ELEMS<DUMP_CAP?OUT_ELEMS:DUMP_CAP;
  printf("OUT %d",k);
  for(int i=0;i<k;i++){{ uint32_t b; memcpy(&b,&R[i],4); printf(" %u",(unsigned)b); }}
  printf("\\n");
  if(OUT_ELEMS>DUMP_CAP){{
    int rows=OUT_ELEMS/OUT_LASTDIM; printf("ARGMAX %d",rows);
    for(int r=0;r<rows;r++){{ const float*row=&R[(long)r*OUT_LASTDIM]; int bi=0; float bv=row[0];
      for(int j=1;j<OUT_LASTDIM;j++) if(row[j]>bv){{bv=row[j];bi=j;}} printf(" %d",bi); }}
    printf("\\n");
    float s=0; for(int i=0;i<OUT_ELEMS;i++) s+=R[i]; uint32_t sb; memcpy(&sb,&s,4);
    printf("SUM %u\\n",(unsigned)sb);
  }}
  uint64_t ticks=t1-t0, est=ticks*(K1_CPU_HZ/K1_TIMEBASE_HZ);
  printf("METRIC cycles %llu\\n",(unsigned long long)est);
  printf("METRIC time_ticks %llu\\n",(unsigned long long)ticks);
  printf("METRIC wall_ns %llu\\n",(unsigned long long)(w1-w0));
  printf("DONE\\n"); fflush(stdout);
  return NULL;
}}

int main(int argc,char**argv){{
  const char*wp=getenv("MERLIN_WEIGHTS"); if(!wp&&argc>1) wp=argv[1];
  if(!wp){{ fprintf(stderr,"FAIL no MERLIN_WEIGHTS (arg0.data)\\n"); return 2; }}
  int fd=open(wp,O_RDONLY); if(fd<0){{ fprintf(stderr,"FAIL open %s\\n",wp); return 2; }}
  struct stat st; fstat(fd,&st);
  void*m=mmap(NULL,(size_t)st.st_size,PROT_READ,MAP_PRIVATE,fd,0);
  if(m==MAP_FAILED){{ fprintf(stderr,"FAIL mmap params\\n"); return 2; }}
  PARAMS=(const float*)m;
  pthread_attr_t at; pthread_t th;
  if(pthread_attr_init(&at)==0 && pthread_attr_setstacksize(&at,(size_t){k1.K1_STACK_BYTES}ULL)==0
     && pthread_create(&th,&at,worker,NULL)==0) pthread_join(th,NULL);
  else worker(NULL);
  return 0;
}}
"""


def _m2m_harness_c(*, mmap_weights: bool = False) -> str:
    """buddy m2m-path harness: sret-first ciface + RANK-EXACT packed operand descriptors.

    Builds each forward operand's memref descriptor packed to its actual rank (so buddy's
    dynamic-strided reads land on the right bytes), calls the sret-first ciface with the result
    descriptor first, then reads the output from that returned descriptor's aligned pointer."""
    mmap_includes = (
        "#include <fcntl.h>\n#include <sys/mman.h>\n#include <sys/stat.h>\n#include <unistd.h>\n"
        if mmap_weights
        else ""
    )
    weights_decl = (
        "static const void *MERLIN_WEIGHTS_PTR;\n"
        if mmap_weights
        else "extern const unsigned char _binary_weights_bin_start[];\nstatic const void *MERLIN_WEIGHTS_PTR;\n"
    )
    if mmap_weights:
        weights_init = """  const char *wpath = getenv("MERLIN_WEIGHTS");
  if (!wpath && argc > 1) wpath = argv[1];
  if (!wpath) { fprintf(stderr, "FAIL no MERLIN_WEIGHTS path\\n"); return 2; }
  int wfd = open(wpath, O_RDONLY);
  if (wfd < 0) { fprintf(stderr, "FAIL open weights %s\\n", wpath); return 2; }
  struct stat wst; fstat(wfd, &wst);
  void *wmap = mmap(NULL, (size_t)wst.st_size, PROT_READ, MAP_PRIVATE, wfd, 0);
  if (wmap == MAP_FAILED) { fprintf(stderr, "FAIL mmap weights\\n"); return 2; }
  MERLIN_WEIGHTS_PTR = wmap;"""
    else:
        weights_init = "  MERLIN_WEIGHTS_PTR = (const void *)_binary_weights_bin_start;"
    return f"""/* Generated by merlin.baselines.buddy — buddy m2m K1 harness (sret-first, rank-exact). Do not edit. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/resource.h>
#include <pthread.h>
{mmap_includes}#include "merlin_model.h"
#include "model_gen.h"
#include "model_io.h"

{weights_decl}#define MERLIN_DUMP_CAP {4096}
#define MERLIN_TIMEBASE_HZ {k1.K1_TIMEBASE_HZ}ULL
#define MERLIN_CPU_HZ {k1.K1_CPU_HZ}ULL

/* buddy overwrites this with the freshly-allocated result descriptor. */
extern void *_mlir_ciface_forward();  /* variadic-tolerant decl; called via merlin_buddy_invoke */
void merlin_buddy_invoke(void **descs);  /* generated in model_call.c (sret-first unrolled call) */
extern void *merlin_buddy_result_desc;

/* A packed rank-R memref descriptor: ptr, ptr, i64 offset, i64 sizes[R], i64 strides[R]. We pack
 * per operand to its EXACT rank (buddy reads dynamic strides from here). A generous byte buffer
 * holds each; the fields are written at rank-dependent offsets. */
static float OUT[MERLIN_OUT_ELEMS];

/* build a rank-exact descriptor for arg `i` into `buf` (>= 24 + 16*rank bytes); returns buf. */
static void *pack_desc(unsigned char *buf, const merlin_arg_t *a, void *data) {{
  int r = a->rank;
  void **pa = (void **)buf;          /* [0] allocated */
  pa[0] = data;                      /* allocated */
  pa[1] = data;                      /* aligned    */
  int64_t *q = (int64_t *)(buf + 16);
  q[0] = 0;                          /* offset */
  int64_t *sizes = q + 1;            /* sizes[r] */
  int64_t *strides = sizes + r;      /* strides[r] IMMEDIATELY after sizes[r] (rank-exact packing) */
  int64_t s = 1;
  for (int d = r - 1; d >= 0; d--) {{ sizes[d] = a->dims[d]; strides[d] = s; s *= a->dims[d]; }}
  return buf;
}}

static inline uint64_t rd_time(void) {{ uint64_t t; __asm__ volatile("rdtime %0":"=r"(t)); return t; }}
static inline uint64_t rd_vlenb(void){{ uint64_t v; __asm__ volatile("csrr %0, vlenb":"=r"(v)); return v; }}
static uint64_t wall_ns(void){{ struct timespec ts; clock_gettime(CLOCK_MONOTONIC,&ts);
  return (uint64_t)ts.tv_sec*1000000000ULL+(uint64_t)ts.tv_nsec; }}

static void *worker(void *arg) {{
  (void)arg;
  printf("=== buddy_m2m vlenb=%llu ===\\n",(unsigned long long)rd_vlenb());
  /* COMPUTE-vs-OVERHEAD split. The buddy ELF is a monolithic forward (all GEMM/attention/norm compute
   * + its own intermediate allocs) plus this thin harness. The only "runtime overhead" outside the
   * compute is our descriptor-pack loop (building rank-exact memref descriptors for the N operands);
   * there is NO merlin dispatch/per-op runtime here. We bracket the descriptor pack (overhead_region)
   * with cheap rdtime, then the forward (compute_region) — reported alongside the clean whole-forward
   * e2e (the headline). rdtime brackets are ~near-zero cost, so they don't perturb the e2e. */
  static unsigned char DBUF[MERLIN_N_ARGS][24 + 16 * MERLIN_MAX_RANK];
  static void *DPTR[MERLIN_N_ARGS];
  uint64_t ov0 = rd_time();
  for (int i = 0; i < MERLIN_N_ARGS; i++) {{
    const merlin_arg_t *a = &MERLIN_ARGS[i];
    void *data = 0;
    if (a->kind == MERLIN_WEIGHT)      data = (void *)((const char *)MERLIN_WEIGHTS_PTR + a->offset);
    else if (a->kind == MERLIN_INPUT)  data = MERLIN_INPUT_PTR[i];
    else /* MERLIN_OUTPUT */           data = OUT;   /* placeholder; buddy overwrites this descriptor */
    DPTR[i] = pack_desc(DBUF[i], a, data);
  }}
  uint64_t ov1 = rd_time();          /* descriptor-pack overhead = ov1-ov0 */
  uint64_t w0=wall_ns(), t0=rd_time();
  merlin_buddy_invoke(DPTR);          /* the compute region (whole monolithic forward) */
  uint64_t t1=rd_time(), w1=wall_ns();

  /* read the output from buddy's RETURNED (sret) descriptor's aligned pointer + offset. */
  const float *R = OUT;
  void **rp = (void **)merlin_buddy_result_desc;
  if (rp && rp[1]) {{ int64_t off = ((int64_t *)((unsigned char *)merlin_buddy_result_desc + 16))[0];
                      R = (const float *)rp[1] + off; }}

  int k = MERLIN_OUT_ELEMS < MERLIN_DUMP_CAP ? MERLIN_OUT_ELEMS : MERLIN_DUMP_CAP;
  printf("OUT %d", k);
  for (int i=0;i<k;i++){{ uint32_t b; memcpy(&b,&R[i],4); printf(" %u",(unsigned)b); }}
  printf("\\n");
  if (MERLIN_OUT_ELEMS > MERLIN_DUMP_CAP) {{
    int rows = MERLIN_OUT_ELEMS / MERLIN_OUT_LASTDIM;
    printf("ARGMAX %d", rows);
    for (int r=0;r<rows;r++){{ const float*row=&R[(long)r*MERLIN_OUT_LASTDIM]; int bi=0; float bv=row[0];
      for (int j=1;j<MERLIN_OUT_LASTDIM;j++) if(row[j]>bv){{bv=row[j];bi=j;}} printf(" %d",bi); }}
    printf("\\n");
    float s=0; for(int i=0;i<MERLIN_OUT_ELEMS;i++) s+=R[i]; uint32_t sb; memcpy(&sb,&s,4);
    printf("SUM %u\\n",(unsigned)sb);
  }}
  uint64_t ticks=t1-t0, est=ticks*(MERLIN_CPU_HZ/MERLIN_TIMEBASE_HZ);
  uint64_t ov=ov1-ov0;               /* descriptor-pack overhead ticks */
  printf("METRIC cycles %llu\\n",(unsigned long long)est);
  printf("METRIC time_ticks %llu\\n",(unsigned long long)ticks);
  printf("METRIC wall_ns %llu\\n",(unsigned long long)(w1-w0));
  /* compute-vs-overhead split (rdtime ticks): compute = the whole forward; overhead = descriptor pack.
   * MERLIN_REGION name=<> ticks=<> is the format profile.parse_profile consumes. */
  printf("MERLIN_REGION name=compute ticks=%llu\\n",(unsigned long long)ticks);
  printf("MERLIN_REGION name=overhead ticks=%llu\\n",(unsigned long long)ov);
  printf("METRIC overhead_ticks %llu\\n",(unsigned long long)ov);
  printf("DONE\\n"); fflush(stdout);
  return NULL;
}}

int main(int argc, char **argv) {{
  (void)argc; (void)argv;
{weights_init}
  struct rlimit rl = {{ {k1.K1_STACK_BYTES}ULL, {k1.K1_STACK_BYTES}ULL }};
  setrlimit(RLIMIT_STACK, &rl);
  pthread_attr_t attr; pthread_t th;
  if (pthread_attr_init(&attr)==0 && pthread_attr_setstacksize(&attr,(size_t){k1.K1_STACK_BYTES}ULL)==0
      && pthread_create(&th,&attr,worker,NULL)==0) pthread_join(th,NULL);
  else worker(NULL);
  return 0;
}}
"""


def _buddy_model_call_c(n_ciface_args: int) -> str:
    """buddy sret-first invocation shim: call ``_mlir_ciface_forward(result, in0, in1, ...)``.

    The c_runtime arg table (and our ``DPTR``) is in signature order with OUTPUT last (``d[N-1]``).
    buddy's ciface wants ``(result_desc*, operand0*, ...)`` — so we pass the OUTPUT descriptor FIRST,
    then the N-1 signature operands. buddy overwrites the result descriptor in place; we stash a
    pointer to it (``merlin_buddy_result_desc``) so the harness reads the aligned data post-call."""
    fwd_args = ",".join(["void*"] * n_ciface_args)
    passed = ",".join(["d[N-1]"] + [f"d[{i}]" for i in range(n_ciface_args - 1)])
    return f"""/* Generated by merlin.baselines.buddy — buddy sret-first ciface shim. Do not edit. */
#define N {n_ciface_args}
extern void _mlir_ciface_forward({fwd_args});
void *merlin_buddy_result_desc = 0;
void merlin_buddy_invoke(void **d) {{
  merlin_buddy_result_desc = d[N-1];
  _mlir_ciface_forward({passed});
}}
"""
