// Auto-generated by merlin LinalgToCudaTileText pass.
// Source matmul: C[128x256] = A[128x64] * B[64x256], f32
// Tile sizes: TILE_M=64, TILE_N=64, TILE_K=32

cuda_tile.module @matmul_kernel {
  entry @matmul_f32(
      %A_base: !cuda_tile.tile<ptr<f32>>,
      %B_base: !cuda_tile.tile<ptr<f32>>,
      %C_base: !cuda_tile.tile<ptr<f32>>) {
    %A_tv = make_tensor_view %A_base, shape = [128, 64], strides = [64, 1]
        : tensor_view<128x64xf32, strides=[64,1]>
    %B_tv = make_tensor_view %B_base, shape = [64, 256], strides = [256, 1]
        : tensor_view<64x256xf32, strides=[256,1]>
    %C_tv = make_tensor_view %C_base, shape = [128, 256], strides = [256, 1]
        : tensor_view<128x256xf32, strides=[256,1]>
    %A_pv = make_partition_view %A_tv
        : partition_view<tile=(64x32), tensor_view<128x64xf32, strides=[64,1]>>
    %B_pv = make_partition_view %B_tv
        : partition_view<tile=(32x64), tensor_view<64x256xf32, strides=[256,1]>>
    %C_pv = make_partition_view %C_tv
        : partition_view<tile=(64x64), tensor_view<128x256xf32, strides=[256,1]>>
    %bx, %by, %bz = get_tile_block_id : tile<i32>
    %c_tile:2 = load_view_tko weak %C_pv[%bx, %by]
        : partition_view<tile=(64x64), tensor_view<128x256xf32, strides=[256,1]>>, tile<i32>
        -> tile<64x64xf32>, token
    %c0 = constant <i32: 0> : tile<i32>
    %c_K_tiles = constant <i32: 2> : tile<i32>
    %c1 = constant <i32: 1> : tile<i32>
    %acc = for %k in (%c0 to %c_K_tiles, step %c1) : tile<i32>
        iter_values(%acc_iter = %c_tile) -> (tile<64x64xf32>) {
      %a_tile:2 = load_view_tko weak %A_pv[%bx, %k]
          : partition_view<tile=(64x32), tensor_view<128x64xf32, strides=[64,1]>>, tile<i32>
          -> tile<64x32xf32>, token
      %b_tile:2 = load_view_tko weak %B_pv[%k, %by]
          : partition_view<tile=(32x64), tensor_view<64x256xf32, strides=[256,1]>>, tile<i32>
          -> tile<32x64xf32>, token
      %updated = mmaf %a_tile, %b_tile, %acc_iter
          : tile<64x32xf32>, tile<32x64xf32>, tile<64x64xf32>
      continue %updated : tile<64x64xf32>
    }
    %tok = store_view_tko weak %acc, %C_pv[%bx, %by]
        : tile<64x64xf32>, partition_view<tile=(64x64), tensor_view<128x256xf32, strides=[256,1]>>, tile<i32>
        -> token
    return
  }
}
