// Minimal OpenBLAS `common.h` shim so the riscv64 sgemm kernel compiles
// standalone for the ceiling driver. Provides only what the autogenerated
// gemm kernel body references: BLASLONG, FLOAT, and the __riscv_* RVV
// intrinsics. CNAME is set by the including driver before #include of the
// kernel. This is NOT the real OpenBLAS common.h (no BLAS dispatch / cpu
// detection); it is the smallest surface the inner kernel needs.
#ifndef MERLIN_CEILING_COMMON_H
#define MERLIN_CEILING_COMMON_H

#include <stdint.h>
#include <riscv_vector.h>

#ifndef BLASLONG
typedef int64_t BLASLONG;
#endif
#ifndef FLOAT
typedef float FLOAT;
#endif

#endif // MERLIN_CEILING_COMMON_H
