"""Command buffer -> bare-metal C driver around the Merlin RVV kernel.

Generates a ``main.c`` that embeds the (deterministically materialized) leaf tensors,
executes the command stream — matmuls through the hand-written RVV assembly kernel
(``merlin/runtime/baremetal/spike/rvv_matmul_i8.S``), epilogues in scalar C with
semantics matching :mod:`merlin.runtime.tensor` exactly (rounding arithmetic shift,
saturating i8 clamp) — partitioned row-wise across harts, and reports outputs +
metrics over the HTIF console (``OUT``/``METRIC``/``DONE`` lines).
"""
from __future__ import annotations

from typing import Any

from ..commandbuffer import BIAS_STAGES, bias_tensor_name, materialize_inputs
from ..simulator import base_matmul_cycles  # noqa: F401  (cycle model stays Python-side)


class CodegenError(RuntimeError):
    pass


def _shapes(cb: dict[str, Any]) -> dict[str, tuple[int, ...]]:
    """Propagate shapes through the command stream (same rules as the simulator)."""
    shapes: dict[str, tuple[int, ...]] = {}
    for name, spec in cb.get("tensors", {}).items():
        shapes[name] = tuple(spec["shape"])
    for cmd in cb.get("commands", []):
        op, ops = cmd["opcode"], cmd.get("operands", {})
        if op == "RES_PACK":
            shapes[ops["dst"]] = shapes[ops["src"]]
        elif op in ("MATMUL_RESIDENT", "MATMUL"):
            m, _ = shapes[ops["lhs"]]
            _, n = shapes[ops["rhs"]]
            shapes[ops["dst"]] = (m, n)
        elif op == "COMMIT":
            shapes[ops["dst"]] = shapes[ops["src"]]
    return shapes


def _c_array(name: str, ctype: str, data: list[int], const: bool = True) -> str:
    vals = ",".join(str(v) for v in data)
    qual = "static const" if const else "static"
    return f"{qual} {ctype} {name}[{len(data)}] = {{{vals}}};"


def generate_driver(cb: dict[str, Any], nharts: int = 4) -> str:
    """Return the C source of the bare-metal driver for ``cb``."""
    leaves = materialize_inputs(cb)
    shapes = _shapes(cb)
    default_shift = int(cb.get("params", {}).get("requant_shift", 4))

    lines: list[str] = [
        "/* Generated by merlin.runtime.backends.rvv_codegen — do not edit. */",
        "#include <stdint.h>",
        '#include "htif.h"',
        "void merlin_rvv_matmul_i8(const int8_t*, const int8_t*, int32_t*, "
        "long, long, long, long, long);",
        "",
        f"#define NHARTS {nharts}",
        "static volatile int barrier_count = 0;",
        "static volatile int barrier_sense = 0;",
        "static void barrier(void) {",
        "  int sense = barrier_sense;",
        "  if (__atomic_add_fetch(&barrier_count, 1, __ATOMIC_ACQ_REL) == NHARTS) {",
        "    barrier_count = 0;",
        "    __atomic_store_n(&barrier_sense, !sense, __ATOMIC_RELEASE);",
        "  } else {",
        "    while (__atomic_load_n(&barrier_sense, __ATOMIC_ACQUIRE) == sense) ;",
        "  }",
        "}",
        "static inline long row_lo(long h, long m) { return h * m / NHARTS; }",
        "static inline long row_hi(long h, long m) { return (h + 1) * m / NHARTS; }",
        "static inline int32_t sat_i8(int32_t x) "
        "{ return x < -128 ? -128 : (x > 127 ? 127 : x); }",
        "",
    ]

    # Leaf tensors, embedded exactly as the Python engine materializes them.
    for name in sorted(leaves):
        t = leaves[name]
        ctype = "int8_t" if t.dtype == "i8" else "int32_t"
        lines.append(_c_array(f"T_{name}", ctype, list(t.data)))
    lines.append("")

    # Buffers for produced tensors (accumulators and committed outputs, all i32).
    produced: list[str] = []
    for cmd in cb.get("commands", []):
        dst = cmd.get("operands", {}).get("dst")
        if dst and dst not in leaves and dst not in produced \
                and cmd["opcode"] != "RES_PACK":
            produced.append(dst)
            r, c = shapes[dst]
            lines.append(f"static int32_t B_{dst}[{r * c}];")
    lines.append("")

    counters = ["command_count", "pack_count", "resident_hits", "resident_misses",
                "evictions", "accumulator_commits", "dispatch_count"]
    lines += [f"static long m_{c} = 0;" for c in counters]
    lines.append("")

    body: list[str] = [
        "int main(long hart) {",
        "  uint64_t cyc0 = 0, cyc1 = 0;",
        "  barrier();",
        '  if (hart == 0) asm volatile("csrr %0, mcycle" : "=r"(cyc0));',
    ]

    resident: dict[str, str] = {}  # handle name -> backing leaf array expr
    outputs: list[str] = []
    bytes_moved = bytes_read = bytes_written = 0

    def ref(name: str) -> str:
        """C expression for a tensor's storage."""
        if name in resident:
            return resident[name]
        return f"T_{name}" if name in leaves else f"B_{name}"

    for cmd in cb.get("commands", []):
        op, ops = cmd["opcode"], cmd.get("operands", {})
        attrs = cmd.get("attributes", {})
        body.append(f"  /* {op} {ops} */")
        body.append("  if (hart == 0) m_command_count++;")

        if op == "RES_PACK":
            # The packed copy has identical values; on a CPU the data is already
            # in memory, so this is a (counted) layout no-op.
            resident[ops["dst"]] = ref(ops["src"])
            r, c = shapes[ops["src"]]
            bytes_moved += r * c
            bytes_read += r * c
            body.append("  if (hart == 0) m_pack_count++;")

        elif op in ("MATMUL_RESIDENT", "MATMUL"):
            lhs, rhs, dst = ops["lhs"], ops["rhs"], ops["dst"]
            m, k = shapes[lhs]
            _, n = shapes[rhs]
            hit = "m_resident_hits" if rhs in resident else "m_resident_misses"
            body += [
                f"  if (hart == 0) {{ {hit}++; m_dispatch_count++; }}",
                f"  merlin_rvv_matmul_i8({ref(lhs)}, {ref(rhs)}, B_{dst}, "
                f"{m}, {k}, {n}, row_lo(hart, {m}), row_hi(hart, {m}));",
                "  barrier();",
            ]
            bytes_read += m * k
            if rhs not in resident:
                # Non-resident RHS re-fetched per dispatch (same rule as the engine).
                bytes_read += k * n
                bytes_moved += k * n

        elif op == "COMMIT":
            src, dst = ops["src"], ops["dst"]
            m, n = shapes[src]
            shift = int(attrs.get("requant_shift", default_shift))
            stages = list(attrs.get("epilogue", []))
            stmts = []
            for stage in stages:
                if stage in BIAS_STAGES:
                    stmts.append(f"x += T_{bias_tensor_name(ops, attrs, op=f'COMMIT {dst!r}')}[j];")
                elif stage == "requant":
                    if shift > 0:
                        stmts.append(f"x = (x + (1 << ({shift} - 1))) >> {shift};")
                elif stage == "relu":
                    stmts.append("if (x < 0) x = 0;")
                elif stage == "maxpool":
                    # DECLARED AND REFUSED BY NAME, not implemented. The commit this emitter generates
                    # is a per-element loop that writes B_dst[i*n+j] from B_src[i*n+j]; a pooling stage
                    # is a windowed reduction whose output has FEWER rows than the accumulator, so it
                    # cannot be expressed as a statement inside that loop -- emitting one would produce
                    # a kernel whose output buffer and declared shape disagree. Naming the refusal here
                    # rather than letting it fall through the generic message below is the point: the
                    # runtime engines DO implement this stage, so a reader hitting the generic
                    # "unknown epilogue stage" would reasonably conclude the ABI had never defined it.
                    raise CodegenError(
                        "epilogue stage 'maxpool' is defined by the command-buffer ABI but this "
                        "vector-lane emitter cannot generate it: its commit is an elementwise loop "
                        "over the accumulator, and pooling reduces the row count. Emit the pooled "
                        "store as its own nest instead of as a commit stage")
                else:
                    raise CodegenError(f"unknown epilogue stage '{stage}'")
            if attrs.get("output_dtype", "i8") == "i8":
                stmts.append("x = sat_i8(x);")
                bytes_written += m * n
                bytes_moved += m * n
            else:
                bytes_written += 4 * m * n
                bytes_moved += 4 * m * n
            inner = " ".join(stmts)
            body += [
                f"  for (long i = row_lo(hart, {m}); i < row_hi(hart, {m}); i++)",
                f"    for (long j = 0; j < {n}; j++) {{",
                f"      int32_t x = B_{src}[i * {n} + j];",
                f"      {inner}",
                f"      B_{dst}[i * {n} + j] = x;",
                "    }",
                "  barrier();",
                "  if (hart == 0) m_accumulator_commits++;",
            ]
            outputs.append(dst)

        elif op == "EVICT":
            resident.pop(ops["handle"], None)
            body.append("  if (hart == 0) m_evictions++;")

        else:
            raise CodegenError(f"unknown opcode '{op}'")

    body += [
        "  barrier();",
        "  if (hart == 0) {",
        '    asm volatile("csrr %0, mcycle" : "=r"(cyc1));',
    ]
    for name in outputs:
        r, c = shapes[name]
        body += [
            f'    htif_puts("OUT {name} {r} {c}");',
            f"    for (long i = 0; i < {r * c}; i++) "
            f"{{ htif_putc(' '); htif_putd(B_{name}[i]); }}",
            "    htif_putc('\\n');",
        ]
    body.append('    htif_puts("METRIC cycles "); '
                "htif_putd((long)(cyc1 - cyc0)); htif_putc('\\n');")
    for c in counters:
        body.append(f'    htif_puts("METRIC {c} "); htif_putd(m_{c}); '
                    "htif_putc('\\n');")
    for name, val in (("bytes_moved", bytes_moved), ("bytes_read", bytes_read),
                      ("bytes_written", bytes_written)):
        body.append(f'    htif_puts("METRIC {name} {val}\\n");')
    body += [
        f'    htif_puts("METRIC harts {nharts}\\n");',
        '    htif_puts("DONE\\n");',
        "    htif_exit(0);",
        "  }",
        "  for (;;) ;",
        "}",
    ]
    return "\n".join(lines + body) + "\n"
