"""Command buffer -> bare-metal C driver using RVV vector intrinsics (the Saturn-vectors family).

Emits a stripmined RVV kernel (vsetvl / vle / vadd|vmul / vmax / vse / vredsum) for the vector
opcodes VECTOR_MAP and VREDUCE over 1-D i32 vectors, runs on spike rv64gcv (or the Saturn-OPU
RTL), and prints results as VOUT/METRIC/DONE via the existing HTIF harness. Leaf tensors are
embedded exactly as the Merlin engine materializes them, so the same bytes feed reference,
simulator, and this kernel.

This is the NON-matmul family codegen — it shares the harness/oracle plumbing with the matmul
path but none of its semantics.
"""
from __future__ import annotations

from typing import Any

from ..commandbuffer import materialize_inputs


class VecCodegenError(RuntimeError):
    pass


def _c_array(name: str, data: list[int]) -> str:
    vals = ",".join(str(int(v)) for v in data)
    return f"static int32_t {name}[{len(data)}] = {{{vals}}};"


def _shapes(cb: dict[str, Any]) -> dict[str, int]:
    """Length of each 1-D vector tensor, propagated through the command stream."""
    sh: dict[str, int] = {}
    for name, spec in cb.get("tensors", {}).items():
        shape = spec["shape"]
        sh[name] = shape[0] if len(shape) == 1 else shape[0] * shape[1]
    for cmd in cb.get("commands", []):
        op, ops = cmd["opcode"], cmd.get("operands", {})
        if op == "VECTOR_MAP":
            sh[ops["dst"]] = sh[ops["lhs"]]
        elif op == "VREDUCE":
            sh[ops["dst"]] = 1
    return sh


def generate_driver(cb: dict[str, Any], *, mode: str = "explicit") -> str:
    if mode != "explicit":
        raise VecCodegenError("only mode='explicit' is supported")
    leaves = materialize_inputs(cb)
    sh = _shapes(cb)
    tensors = cb.get("tensors", {})
    outputs = [n for n, s in tensors.items() if s.get("role") == "output"]

    lines = [
        "/* Generated by merlin.runtime.backends.saturn_vec_codegen — do not edit. */",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <riscv_vector.h>",
        '#include "htif.h"',
        "",
    ]
    for name in sorted(leaves):
        lines.append(_c_array(f"T_{name}", list(leaves[name].data)))
    # buffers for produced tensors (intermediates + outputs)
    produced = []
    for cmd in cb.get("commands", []):
        dst = cmd.get("operands", {}).get("dst")
        if dst and dst not in leaves and dst not in produced:
            produced.append(dst)
            lines.append(f"static int32_t T_{dst}[{sh[dst]}];")
    lines += ["", "int main(long hart) {", "  if (hart != 0) { for(;;); }",
              "  uint64_t c0, c1;",
              '  asm volatile("csrr %0, mcycle" : "=r"(c0));']

    for cmd in cb.get("commands", []):
        op, ops, attrs = cmd["opcode"], cmd.get("operands", {}), cmd.get("attributes", {})
        if op == "VECTOR_MAP":
            n = sh[ops["lhs"]]
            a, b, d = f"T_{ops['lhs']}", f"T_{ops['rhs']}", f"T_{ops['dst']}"
            vop = "__riscv_vmul_vv_i32m1" if attrs.get("combine") == "mul" else "__riscv_vadd_vv_i32m1"
            relu = "relu" in attrs.get("activation", [])
            lines += [
                f"  for (size_t i = 0, n = {n}; n > 0; ) {{",
                "    size_t vl = __riscv_vsetvl_e32m1(n);",
                f"    vint32m1_t va = __riscv_vle32_v_i32m1(&{a}[i], vl);",
                f"    vint32m1_t vb = __riscv_vle32_v_i32m1(&{b}[i], vl);",
                f"    vint32m1_t vd = {vop}(va, vb, vl);",
            ]
            if relu:
                lines.append("    vd = __riscv_vmax_vx_i32m1(vd, 0, vl);")
            lines += [
                f"    __riscv_vse32_v_i32m1(&{d}[i], vd, vl);",
                "    i += vl; n -= vl;",
                "  }",
            ]
        elif op == "VREDUCE":
            n = sh[ops["src"]]
            s, d = f"T_{ops['src']}", f"T_{ops['dst']}"
            if attrs.get("op", "sum") != "sum":
                raise VecCodegenError(f"unsupported reduce {attrs.get('op')}")
            lines += [
                "  {",
                "    int32_t acc = 0;",
                f"    for (size_t i = 0, n = {n}; n > 0; ) {{",
                "      size_t vl = __riscv_vsetvl_e32m1(n);",
                f"      vint32m1_t vs = __riscv_vle32_v_i32m1(&{s}[i], vl);",
                "      vint32m1_t z = __riscv_vmv_v_x_i32m1(0, vl);",
                "      vint32m1_t r = __riscv_vredsum_vs_i32m1_i32m1(vs, z, vl);",
                "      acc += __riscv_vmv_x_s_i32m1_i32(r);",
                "      i += vl; n -= vl;",
                "    }",
                f"    {d}[0] = acc;",
                "  }",
            ]
        else:
            raise VecCodegenError(f"unsupported opcode {op!r} (vector family is VECTOR_MAP/VREDUCE)")

    lines += ['  asm volatile("csrr %0, mcycle" : "=r"(c1));']
    for name in outputs:
        n = sh[name]
        lines += [
            f'  htif_puts("VOUT {name} {n}");',
            f"  for (long i = 0; i < {n}; i++) {{ htif_putc(' '); htif_putd(T_{name}[i]); }}",
            "  htif_putc('\\n');",
        ]
    lines += [
        '  htif_puts("METRIC cycles "); htif_putd((long)(c1 - c0)); htif_putc(\'\\n\');',
        '  htif_puts("METRIC cycle_window_gemmini_region 0\\n");',
        '  htif_puts("DONE\\n");',
        "  htif_exit(0);",
        "  return 0;",
        "}",
    ]
    return "\n".join(lines) + "\n"
