"""Emit the derived per-target lit suite, plus the coverage ledger that says what it could not derive.

Generated output, so it lands under the ``out/`` root (never tracked): a target-named ``.mlir`` in the
source tree would go stale against the facts cache and is exactly the overfit the repo's register
exists to shrink. The tracked seed suite in ``merlin/tests/data/lit`` is target-INDEPENDENT and stays
hand-authored.

``coverage.json`` is the deliverable for a target that can derive nothing. For a target with no
capability manifest, "0 emitted, here is why" is the honest result and is more useful than an empty
directory.

CLI::

    python -m merlin.targetgen.lit_suite --target <t> --write
    python -m merlin.targetgen.lit_suite --all
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .lit_check_compiler import Compiled, compile_checks

#: Shape the generated module is built at when the target's tile edge is not derivable.
_FALLBACK_SHAPE = (16, 16, 16)


def _shape_for(compiled: Compiled) -> tuple[tuple[int, int, int], str]:
    """The shape to build at, and the SOURCE of that shape.

    Returned together because a shape whose provenance is unknown is not evidence — and the derived
    edge can coincide with the fallback, so equality is not a usable test of where it came from.
    """
    rec = compiled.facts.get("mesh_dim") or {}
    dim = rec.get("value") if rec.get("derived") else None
    if not dim:
        return _FALLBACK_SHAPE, "fallback: tile edge not derivable from RTL facts"
    d = int(dim)
    return (d, d, d), f"mesh_dim={d} (derived from RTL facts)"


def _interface_text(shape: tuple[int, int, int], reuse: int = 2) -> str:
    """The schedule-plane module the generated test feeds to merlin-opt."""
    from merlin.xdsl_dialects import _common
    from merlin.xdsl_dialects.lowering.contract_facts import lower_to_contract
    from merlin.xdsl_dialects.lowering.pipeline import build_input_module, load_curated_contract
    from merlin.xdsl_dialects.lowering.schedule_decisions import lower_to_schedule

    m, k, n = shape
    tc = load_curated_contract("toy_npu")
    mod = build_input_module(reuse=reuse, m=m, k=k, n=n)
    return _common.text(lower_to_schedule(lower_to_contract(mod, tc)))


def render_test(compiled: Compiled, shape: tuple[int, int, int]) -> str:
    """A runnable lit test: ONE RUN line per obligation, each with its own check prefix.

    FileCheck applies directives sequentially over the whole file, so several obligations sharing the
    default CHECK prefix would be read as one ordered sequence and fail spuriously. A prefix per
    obligation is the standard MLIR idiom and keeps each obligation independently attributable — a
    failure names the obligation it broke.
    """
    head = [
        "// GENERATED by merlin.targetgen.lit_suite -- do not edit; regenerate.",
        f"// target: {compiled.target}   shape: {shape[0]}x{shape[1]}x{shape[2]}",
        "//",
        "// Each RUN line below discharges one obligation this target's capability manifest",
        "// DECLARES. Checks run on the target-independent `interface` plane, whose op names are",
        "// defined in-tree; a generated target dialect's invented mnemonics are never matched.",
        "",
    ]
    for i, c in enumerate(compiled.checks):
        prefix = f"OB{i}"
        head.append(f"// RUN: %merlin-opt %s -p merlin-materialize-interface | "
                    f"%filecheck %s --check-prefix={prefix}")
    head.append("")
    for i, c in enumerate(compiled.checks):
        prefix = f"OB{i}"
        head.append(f"// obligation: {c.obligation}")
        head.append(f"// grounded by: {c.grounded_by} (derived={c.derived})")
        for line in c.lines:
            head.append(line.replace("// CHECK", f"// {prefix}"))
        head.append("")
    for o in compiled.omissions:
        head.append(f"// OMITTED {o.obligation}: {o.reason}")
    head.append("")
    return "\n".join(head) + _interface_text(shape)


def emit(target: str, *, write: bool = False) -> dict[str, Any]:
    compiled = compile_checks(target)
    shape, shape_source = _shape_for(compiled)
    coverage = dict(compiled.coverage)
    coverage["shape"] = {"m": shape[0], "k": shape[1], "n": shape[2]}
    coverage["shape_source"] = shape_source

    body = render_test(compiled, shape) if compiled.checks else ""
    coverage["test_emitted"] = bool(body)
    if not body:
        coverage["test_omitted_reason"] = (
            "no obligation could be expressed structurally for this target; see omission_reasons")

    if write:
        from merlin.common.artifacts import artifacts_dir

        out = Path(artifacts_dir()) / "verify" / "lit" / target
        out.mkdir(parents=True, exist_ok=True)
        (out / "coverage.json").write_text(json.dumps(coverage, indent=1), encoding="utf-8")
        test_path = out / "obligations.mlir"
        if body:
            test_path.write_text(body, encoding="utf-8")
        elif test_path.exists():
            # A target that used to emit checks and now cannot must not leave a stale test behind
            # passing on last run's evidence.
            test_path.unlink()
        coverage["written_to"] = str(out)
        _install_lit_cfg(out.parent)
    return coverage


def _install_lit_cfg(root: Path) -> None:
    """Give the generated tree its own lit config, copied from the tracked one.

    The tracked config locates the repo by walking up for ``pyproject.toml``, and the generated tree
    lives inside the repo, so the copy works unchanged — no second implementation to drift.
    """
    from merlin.common.paths import merlin_dir

    src = merlin_dir() / "tests" / "data" / "lit" / "lit.cfg.py"
    if not src.is_file():
        return
    root.mkdir(parents=True, exist_ok=True)
    text = src.read_text(encoding="utf-8").replace(
        'config.name = "merlin-pass-tests"', 'config.name = "merlin-derived-pass-tests"')
    (root / "lit.cfg.py").write_text(text, encoding="utf-8")


#: The pass the derived checks run, and the requirement class they discharge. Named explicitly: a
#: verdict attributed to the wrong pass is worse than no verdict.
CHECKED_PASS = "merlin-materialize-interface"
CHECKED_CLASS = "host-seam"


def record_verdicts(target: str, compiled, *, lit_passed: bool | None) -> None:
    """Write this target's obligations to the shared verification log the obligation gate reads.

    Three outcomes, and the middle one is why the ledger exists:

    ``verified``    a check was emitted AND the suite ran green
    ``unmeasured``  a check was emitted but the suite has not run — emitting is not verifying
    ``abstracted``  the obligation could not be expressed at all; the recorded reason travels with it

    A no-op unless ``MERLIN_VERIFY_LOG`` is set, exactly like invocation recording.
    """
    try:
        from merlin.xdsl_dialects.lowering import passes as P
    except Exception:
        return
    for check in compiled.checks:
        if lit_passed is None:
            verdict = "unmeasured"
        else:
            verdict = "verified" if lit_passed else "refuted"
        try:
            P.record_verification(
                CHECKED_PASS, requirement_class=CHECKED_CLASS, method="filecheck",
                verdict=verdict, target=target,
                evidence={"obligation": check.obligation, "grounded_by": check.grounded_by,
                          "derived": check.derived},
                provenance={"source": "merlin.targetgen.lit_suite"})
        except Exception:
            pass
    for omission in compiled.omissions:
        try:
            P.record_verification(
                CHECKED_PASS, requirement_class=CHECKED_CLASS, method="filecheck",
                verdict="abstracted", target=target,
                evidence={"obligation": omission.obligation, "reason": omission.reason},
                provenance={"source": "merlin.targetgen.lit_suite"})
        except Exception:
            pass


def core_suite_dir() -> Path:
    """The hand-written core lit suite (tracked), as opposed to the derived per-target one."""
    from merlin.common.paths import merlin_dir

    return merlin_dir() / "tests" / "data" / "lit" / "core"


def passes_exercised_by(path: Path) -> list[str]:
    """The pass names a lit file's RUN lines drive, read from the file itself.

    Parsed STRUCTURALLY (token walk, no regex, no hardcoded pass list) so the mapping cannot drift
    from what the test actually runs: a file that stops exercising a pass stops crediting it. A RUN
    line with no ``-p`` drives no catalogued pass and contributes nothing.
    """
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        head, sep, rest = line.partition("RUN:")
        if not sep or not head.strip().startswith("//"):
            continue
        toks = rest.split()
        for i, tok in enumerate(toks):
            if tok == "-p" and i + 1 < len(toks):
                out.append(toks[i + 1].strip("\"'"))
            elif tok.startswith("-p="):
                out.append(tok[3:].strip("\"'"))
    return out


def record_core_verdicts(*, lit_passed: bool | None) -> dict[str, str]:
    """Record a static verdict for every pass the CORE suite exercises, production ones included.

    The derived per-target suite can only ever credit ``merlin-materialize-interface`` — a
    PROTOTYPE-catalog pass — so the obligation gate rightly refused to count it toward production and
    reported ``0 / 4 verified``. The core suite drives production passes too, and nothing was reading
    it. This closes that: the pass under test comes from the RUN line, and its requirement class from
    the catalog, so neither is asserted here.

    ``None`` for ``lit_passed`` means the suite did not run — recorded as ``unmeasured``, never as a
    pass. A no-op unless ``MERLIN_VERIFY_LOG`` is set.
    """
    from merlin.xdsl_dialects.lowering import passes as P

    verdict = "unmeasured" if lit_passed is None else ("verified" if lit_passed else "refuted")
    by_name = {i.name: i for i in P.all_catalogs()}
    out: dict[str, str] = {}
    root = core_suite_dir()
    if not root.is_dir():
        return out
    for path in sorted(root.glob("*.mlir")):
        for name in passes_exercised_by(path):
            info = by_name.get(name)
            if info is None:
                # A RUN line naming a pass the catalog does not define is a broken test, not a
                # verdict; surfaced rather than silently skipped.
                out[name] = "unknown-pass"
                continue
            out[name] = verdict
            try:
                P.record_verification(
                    name, requirement_class=info.obligation, method="filecheck", verdict=verdict,
                    evidence={"check_file": path.name, "suite": "core"},
                    provenance={"source": "merlin.targetgen.lit_suite.record_core_verdicts"})
            except Exception:
                pass
    return out


def run_core_suite() -> bool | None:
    """Run the tracked core lit suite. ``None`` when llvm-lit is unavailable."""
    import subprocess

    from merlin.verify.tools import find_lit

    lit = find_lit()
    root = core_suite_dir()
    if lit is None or not root.is_dir():
        return None
    r = subprocess.run([lit, "-s", str(root)], capture_output=True, text=True, timeout=600)
    return r.returncode == 0


def run_suite(target: str) -> bool | None:
    """Run the derived suite for one target through llvm-lit. ``None`` when it cannot run."""
    import subprocess

    from merlin.common.artifacts import artifacts_dir
    from merlin.verify.tools import find_lit

    lit = find_lit()
    root = Path(artifacts_dir()) / "verify" / "lit" / target
    if lit is None or not (root / "obligations.mlir").is_file():
        return None
    r = subprocess.run([lit, "-s", str(root)], capture_output=True, text=True, timeout=600)
    return r.returncode == 0


def known_targets() -> list[str]:
    """Every target with a capsule corpus, enumerated from the TRACKED contract.

    Read from ``merlin/contract/capsules/profiles/<target>.yaml`` rather than from a per-experiment
    directory: library code must not reach into the experiment tree (``check_structure.py`` enforces
    that), and the profile set is the contract's own statement of which targets have a corpus. The
    ``.synth`` / ``.hidden`` siblings are generated or withheld variants of the same target, and
    ``_perf`` is the shared performance sweep, so neither names a target.
    """
    from merlin.common.paths import repo_root

    root = repo_root() / "merlin" / "contract" / "capsules" / "profiles"
    if not root.is_dir():
        return []
    names = set()
    for path in root.glob("*.yaml"):
        stem = path.name[: -len(".yaml")]
        if stem.startswith("_") or "." in stem:
            continue
        names.add(stem)
    return sorted(names)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--target")
    ap.add_argument("--all", action="store_true", help="every target with a capsule store")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--run", action="store_true",
                    help="run the emitted suite through llvm-lit and record the verdicts")
    args = ap.parse_args(argv)

    if args.all:
        targets = known_targets()
    elif args.target:
        targets = [args.target]
    else:
        ap.error("pass --target <t> or --all")

    records = []
    for t in targets:
        rec = emit(t, write=args.write)
        if args.run:
            from .lit_check_compiler import compile_checks

            passed = run_suite(t) if args.write else None
            rec["suite_passed"] = passed
            record_verdicts(t, compile_checks(t), lit_passed=passed)
        records.append(rec)
    if args.json:
        print(json.dumps(records, indent=1))
    else:
        print(f"{'target':16s} {'declared':>8} {'emitted':>8} {'omitted':>8}  test")
        for r in records:
            print(f"{r['target']:16s} {r['obligations_declared']:>8} {r['emitted']:>8} "
                  f"{r['omitted']:>8}  {'yes' if r['test_emitted'] else 'no'}")
        total_d = sum(r["obligations_declared"] for r in records)
        total_e = sum(r["emitted"] for r in records)
        print(f"\n{total_e} of {total_d} declared obligations are now checked "
              f"({total_d - total_e} omitted with recorded reasons).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
