cmake_minimum_required(VERSION 3.20)
project(iface_irdl_demo C CXX)
find_package(MLIR REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}")
list(APPEND CMAKE_MODULE_PATH "${LLVM_CMAKE_DIR}")
include(AddLLVM)
include(AddMLIR)
include(HandleLLVMOptions)
include_directories(${LLVM_INCLUDE_DIRS})
include_directories(${MLIR_INCLUDE_DIRS})
add_llvm_executable(iface-irdl-demo iface_irdl_demo.cpp)
llvm_update_compile_flags(iface-irdl-demo)
target_link_libraries(iface-irdl-demo PRIVATE MLIRIR MLIRParser MLIRIRDL)
