// Copyright 2026 The IREE Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Bare-metal mxGemmini-on-VCS runner for the mlp_3layer fixture.
//
// Loads a pre-compiled .vmfb (embedded as .incbin in this binary), invokes
// `module.mlp_3layer` through the IREE local-sync HAL driver, and prints
// the i32 result row-by-row through HTIF. The .vmfb's dispatch ELF
// contains volatile MMIO stores at GEMMINI_CTRL=0x40084000 + {0x10, 0x18,
// 0x00} emitted by Merlin's gemmini_mx_vcs target (see
// models/gemmini_mx_vcs.yaml + gemmini_mx_vcs_fp4.yaml). The chipyard
// `RadianceGemminiOnlyConfig` cluster's MMIO-attached Gemmini consumes
// these stores.
//
// Test pattern: the deterministic 1x16 i8 input from
// tests/integration/gemmini_mx_vcs/fixtures/test_pattern.h (auto-
// generated by mlp_3layer_torch.py), so the runner output diffs cleanly
// against expected_{fp8,fp4}.txt.

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "iree/async/util/proactor_pool.h"
#include "iree/base/api.h"
#include "iree/base/threading/thread.h"
#include "iree/hal/api.h"
#include "iree/hal/device.h"
#include "iree/hal/device_group.h"
#include "iree/hal/drivers/local_sync/sync_device.h"
#include "iree/hal/local/executable_loader.h"
#include "iree/hal/local/loaders/embedded_elf_loader.h"
#include "iree/modules/hal/module.h"
#include "iree/vm/api.h"
#include "iree/vm/bytecode/module.h"

// Generated by tests/integration/gemmini_mx_vcs/mlp_3layer_torch.py.
// Compile-time -I path is set by CMake to point at fixtures/.
#include "test_pattern.h"

// Local-sync device factory. Bare-metal: the proactor pool wraps a
// NULL platform proactor (see proactor_platform.c IREE_PLATFORM_GENERIC
// carve-out); local-sync never exercises the proactor.
static iree_status_t create_sample_device(
	iree_allocator_t host_allocator, iree_hal_device_t **out_device) {
	iree_hal_sync_device_params_t params;
	iree_hal_sync_device_params_initialize(&params);

	iree_hal_executable_loader_t *loader = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_embedded_elf_loader_create(
		/*plugin_manager=*/NULL, host_allocator, &loader));

	iree_string_view_t identifier = iree_make_cstring_view("local-sync");
	iree_hal_allocator_t *device_allocator = NULL;
	iree_status_t status = iree_hal_allocator_create_heap(
		identifier, host_allocator, host_allocator, &device_allocator);

	iree_async_proactor_pool_t *proactor_pool = NULL;
	if (iree_status_is_ok(status)) {
		iree_async_proactor_pool_options_t pool_options =
			iree_async_proactor_pool_options_default();
		memset(&pool_options.runner, 0, sizeof(pool_options.runner));
		status = iree_async_proactor_pool_create(
			/*node_count=*/1, /*node_ids=*/NULL, pool_options, host_allocator,
			&proactor_pool);
	}

	iree_hal_device_create_params_t create_params =
		iree_hal_device_create_params_default();
	create_params.proactor_pool = proactor_pool;
	if (iree_status_is_ok(status)) {
		status = iree_hal_sync_device_create(identifier, &params,
			&create_params, /*loader_count=*/1, &loader, device_allocator,
			host_allocator, out_device);
	}
	iree_async_proactor_pool_release(proactor_pool);
	iree_hal_allocator_release(device_allocator);
	iree_hal_executable_loader_release(loader);
	return status;
}

#if defined(IREE_PLATFORM_GENERIC)
iree_status_t iree_thread_create(iree_thread_entry_t entry, void *entry_arg,
	iree_thread_create_params_t params, iree_allocator_t allocator,
	iree_thread_t **out_thread) {
	(void)entry;
	(void)entry_arg;
	(void)params;
	(void)allocator;
	*out_thread = NULL;
	return iree_ok_status();
}
void iree_thread_release(iree_thread_t *thread) {
	(void)thread;
}
#endif

// Symbols from mxgemmini_vmfb_embed.S (.incbin).
extern const uint8_t _binary_mxgemmini_vcs_vmfb_start[];
extern const uint8_t _binary_mxgemmini_vcs_vmfb_end[];

// Initialize mxGemmini scale-factor memories with identity scales
// (0x7f7f7f7f7f7f7f7f per matmul_tiled_fp8.c reference). On
// RadianceGemminiOnlyConfig the SF memories are uninitialized at reset
// (TestMxGemminiRocketConfig preloads them in hardware; we don't have
// that luxury). Without valid SF data, mxGemmini's compute path stalls
// waiting for scale data to flow through, and BUSY never deasserts.
//
// Memory map per matmul_ws_mx_generic.c:
//   GEMMINI_SF_MEM_B = 0x40088000  (B operand scale factors)
//   GEMMINI_SF_MEM_A = 0x4008A000  (A operand scale factors, +0x2000)
// We fill 8 KB at each base, generously covering any operand size up to
// the full scratchpad capacity. 8KB / 8B per dword = 1024 writes each.
static void preflight_init_scale_factors(void) {
	volatile uint64_t *sf_b = (volatile uint64_t *)0x40088000;
	volatile uint64_t *sf_a = (volatile uint64_t *)0x4008A000;
	const uint64_t identity = 0x7f7f7f7f7f7f7f7fULL;

	fprintf(stdout,
		"[preflight] writing identity scale factors to SF_MEM_A "
		"(0x4008A000) and SF_MEM_B (0x40088000)...\n");
	fflush(stdout);

	for (int i = 0; i < 1024; ++i) {
		sf_b[i] = identity;
		sf_a[i] = identity;
	}

	fprintf(stdout, "[preflight] scale-factor memories initialized\n");
	fflush(stdout);
}

// Path A — hand-rolled gold matmul. Issues the same MMIO sequence as
// the upstream matmul_16x16_fp8_ref-baremetal test (which we verified
// runs to PASS on RadianceGemminiOnlyConfig in 19 s) directly from
// inside our IREE runner. Both A and B are static 16×16 arrays of
// 0x40 (= 2.0 in FP8 e4m3) in DRAM, so every output cell should be
// 16 × 2.0 × 2.0 = 64.0 = BF16 0x4280 written to spad address 128.
//
// If, after this returns, the spad readout @ 0x40000800 shows
// 0x4280, the entire IREE-runner runtime context (Zephyr loader,
// ELF placement, cache state, DRAM mapping, gemmini MMIO routing,
// SF memory init) is good and the remaining IREE-driven hang/zero
// is purely about how IREE plumbs the input buffer to the dispatch.
static int8_t gold_A_in[16][16] __attribute__((aligned(64)));
static int8_t gold_B_in[16][16] __attribute__((aligned(64)));

static void mmio_rocc(uint64_t rs1, uint64_t rs2, uint32_t funct) {
	*((volatile uint64_t *)0x40084010) = rs1;
	*((volatile uint64_t *)0x40084018) = rs2;
	*((volatile uint32_t *)0x40084000) =
		0x7BU | (3U << 12) | (1U << 15) | (2U << 20) | (funct << 25);
}

static void preflight_gold_matmul(void) {
	// Paint a wider region of SMEM around the expected C output with
	// a known sentinel pattern. After the matmul, anywhere gemmini
	// wrote will overwrite the sentinel — so we can scan and find
	// where the actual output landed (if anywhere).
	volatile uint32_t *smem_paint = (volatile uint32_t *)0x40000000;
	for (int i = 0; i < 1024; ++i) {
		smem_paint[i] = 0xDEADBEEFU + (uint32_t)i; // unique per-cell
	}
	fprintf(stdout,
		"[preflight-gold] painted SMEM 0x40000000..0x40001000 with sentinel "
		"pattern\n");
	fflush(stdout);

	// Initialise A and B in DRAM with 0x40 each (FP8 e4m3 = 2.0).
	for (int i = 0; i < 16; ++i)
		for (int j = 0; j < 16; ++j) {
			gold_A_in[i][j] = (int8_t)0x40;
			gold_B_in[i][j] = (int8_t)0x40;
		}
	// Force memory ordering so that gemmini's MVIN DMA observes the
	// CPU-side writes. The bare-metal newlib reference doesn't need
	// this (it runs with caches disabled), but our Zephyr-linked
	// runner may have a dirty d-cache hiding our 0x40 writes from
	// the coherent DMA path.
	__sync_synchronize();
	asm volatile("fence rw,rw");

	fprintf(stdout,
		"[preflight-gold] A[0][0]=0x%02x B[0][0]=0x%02x "
		"&A=0x%lx &B=0x%lx\n",
		(unsigned)(unsigned char)gold_A_in[0][0],
		(unsigned)(unsigned char)gold_B_in[0][0],
		(unsigned long)(uintptr_t)&gold_A_in[0][0],
		(unsigned long)(uintptr_t)&gold_B_in[0][0]);
	fprintf(stdout, "[preflight-gold] issuing inline gold matmul...\n");
	fflush(stdout);

	const uint64_t DIM = 16;
	const uint64_t a_base = 0;
	const uint64_t b_base_end = 4 * 2048; // BANK_NUM * BANK_ROWS = 0x2000

	// 1) gemmini_flush(0)
	mmio_rocc(0, 0, /*funct=*/7);

	// 2) CONFIG_EX (mxGemmini full bit pattern; matches
	// matmul_tiled_fp8.c's gemmini_extended3_config_ex):
	//   dataflow=WS(bit2), act=0, accScale=0, A_stride=1,
	//   act_mx=0, wgt_mx=0, out_mx=3.
	const uint64_t configEx_rs1 =
		((uint64_t)0 << 32) | // acc_scale = 0 (identity for MX)
		((uint64_t)1 << 16) | // A_stride
		((uint64_t)3 << 14) | // out_mx_fmt
		((uint64_t)0 << 12) | // wgt_mx_fmt
		((uint64_t)0 << 10) | // act_mx_fmt
		((uint64_t)1 << 2) | // dataflow = WS
		0; // CONFIG_EX cmd_type
	const uint64_t configEx_rs2 = (uint64_t)1 << 48; // C_stride = 1
	mmio_rocc(configEx_rs1, configEx_rs2, /*funct=*/0);

	// 2b) Load scale factors AFTER CONFIG_EX (matches the exact order
	// in matmul_tiled_fp8.c — load_scale_factors is called immediately
	// after gemmini_extended3_config_ex, before any CONFIG_LD/MVIN).
	// 512 bytes each per the reference.
	{
		volatile uint64_t *sf_a = (volatile uint64_t *)0x4008A000;
		volatile uint64_t *sf_b = (volatile uint64_t *)0x40088000;
		for (int i = 0; i < 64; ++i) {
			sf_a[i] = 0x7f7f7f7f7f7f7f7fULL;
			sf_b[i] = 0x7f7f7f7f7f7f7f7fULL;
		}
		__sync_synchronize();
	}

	// 3) CONFIG_LD stride=DIM (= 16 bytes/row for i8 input).
	//   block_mvin_stride = DIM = 16, pixel_repeats = 1, id = 0,
	//   scale = 0.
	const uint64_t configLd_rs1 = ((uint64_t)0 << 32) | // scale = 0
		((uint64_t)16 << 16) | // block_mvin_stride = 16
		((uint64_t)1 << 8) | // pixel_repeats = 1
		((uint64_t)0 << 3) | // id = 0
		0 | 1; // shrunk=0, CONFIG_LD cmd_type
	mmio_rocc(configLd_rs1, /*stride=*/16, /*funct=*/0);

	// 4) MVIN A: dram = &gold_A_in, sp_addr = 0, cols = 16, rows = 16.
	// rs2 layout (ADDR_LEN=32): rows[63:48] | cols[47:32] | sp_addr[31:0].
	const uint64_t mvinA_rs2 =
		((uint64_t)16 << 48) | ((uint64_t)16 << 32) | (uint64_t)0;
	mmio_rocc((uint64_t)gold_A_in, mvinA_rs2, /*funct=*/2);

	// 5) MVIN B: dram = &gold_B_in, sp_addr = b_base = b_base_end - DIM.
	const uint64_t b_base = b_base_end - 1 * 1 * DIM;
	const uint64_t mvinB_rs2 =
		((uint64_t)16 << 48) | ((uint64_t)16 << 32) | b_base;
	mmio_rocc((uint64_t)gold_B_in, mvinB_rs2, /*funct=*/2);

	// 6) CONFIG_ST stride = (M/4)*8 = 32 bytes (bf16 packed 4 per uint64).
	const uint64_t configSt_rs1 = ((uint64_t)0 << 2) | 2; // CONFIG_ST
	const uint64_t configSt_rs2 = ((uint64_t)0 << 32) | (uint64_t)32;
	mmio_rocc(configSt_rs1, configSt_rs2, /*funct=*/0);

	// 7) LOOP_WS_CONFIG_BOUNDS: pads = 0, I=J=K=1.
	const uint64_t bounds_rs1 = 0;
	const uint64_t bounds_rs2 =
		((uint64_t)1 << 32) | ((uint64_t)1 << 16) | (uint64_t)1;
	mmio_rocc(bounds_rs1, bounds_rs2, /*funct=*/9);

	// 8) LOOP_WS_CONFIG_SPAD_AB: A_sp = 0, B_sp_end = 0x2000.
	mmio_rocc(a_base, b_base_end, /*funct=*/24);

	// 9) LOOP_WS: spad_only=1 (rs2[9]), skip=0x38 (skip ldA/ldB/ldD),
	// c_spad_addr=128 in rs2[63:32], no transposes, no resadd, no
	// activation, full_C=0, low_D=0, ex_acc=0, a/b_spad_id=0.
	const uint64_t loopWs_rs1 = 0;
	const uint64_t loopWs_rs2 =
		((uint64_t)128 << 32) | ((uint64_t)1 << 9) | ((uint64_t)0x38) | 0;
	mmio_rocc(loopWs_rs1, loopWs_rs2, /*funct=*/8);

	// Busy-wait for BUSY to clear.
	while (*((volatile uint32_t *)0x40084020))
		;

	volatile uint32_t *smem_scan_gold = (volatile uint32_t *)0x40000000;
	// Tight 5-line print to fit within VCS UART budget. Just the cells
	// that matter: spad_row 0 (A start), 16 (A end / B start ?), 128
	// (expected C output), and total count of changed rows.
	int rows_changed = 0;
	int max_changed_row = -1;
	for (int row = 0; row < 256; ++row) {
		uint32_t v0 = smem_scan_gold[row * 4 + 0];
		uint32_t expected_v0 = 0xDEADBEEFU + (uint32_t)(row * 4);
		if (v0 != expected_v0) {
			rows_changed++;
			if (row > max_changed_row)
				max_changed_row = row;
		}
	}
	fprintf(stdout,
		"[gold] %d/256 rows changed, max_changed=%d, "
		"row0=0x%08x row128=0x%08x row16=0x%08x\n",
		rows_changed, max_changed_row, smem_scan_gold[0 * 4 + 0],
		smem_scan_gold[128 * 4 + 0], smem_scan_gold[16 * 4 + 0]);
	fflush(stdout);
}

// Exp 1b: gemmini MMIO preflight. Issues a FLUSH (funct=7) and waits for
// BUSY to deassert, all from inside the Zephyr-loaded runner ELF context
// before any IREE module invocation. If this prints PASS, the runtime
// load context can talk to gemmini cleanly and the subsequent IREE-driven
// hang is purely a function of the dispatch's MMIO sequence (not of how
// the runner was loaded). If this hangs, the runtime context itself is
// the problem.
//
// Custom-3 instruction word: 0x7B | (3 << 12) | (1 << 15) | (2 << 20) |
// (funct << 25). For funct=7 (FLUSH): 0x0e20b07b.
static void preflight_flush(void) {
	volatile uint64_t *rs1_addr = (uint64_t *)0x40084010;
	volatile uint64_t *rs2_addr = (uint64_t *)0x40084018;
	volatile uint32_t *inst_addr = (uint32_t *)0x40084000;
	volatile uint32_t *busy_addr = (uint32_t *)0x40084020;

	fprintf(stdout, "[preflight] issuing FLUSH (funct=7)...\n");
	fflush(stdout);

	*rs1_addr = 0;
	*rs2_addr = 0;
	*inst_addr = 0x0e20b07bU;

	// Bounded busy-wait: poll up to 1M times so a hang prints diagnostic
	// info instead of starving the simulator's max-cycles. mxGemmini
	// FLUSH should clear in well under 1k cycles.
	uint32_t busy = 0;
	for (uint32_t i = 0; i < 1000000U; ++i) {
		busy = *busy_addr;
		if (busy == 0U) {
			fprintf(stdout,
				"[preflight] FLUSH cleared BUSY after %u polls — gemmini "
				"MMIO is reachable from the IREE runner context\n",
				i);
			fflush(stdout);
			return;
		}
	}
	fprintf(stdout,
		"[preflight] FAIL: BUSY still asserted (=%u) after 1M polls — "
		"gemmini MMIO does NOT respond from the IREE runner context\n",
		busy);
	fflush(stdout);
}

// Shape macros — controlled by -DMX_BATCH= / -DMX_IN_DIM= / -DMX_OUT_DIM=
// passed by CMake (default 16x16). This lets us point the same runner at
// different-shape fixtures (matmul_16x16x16, matmul_32x32x32, etc.) without
// per-shape runner copies.
#ifndef MX_BATCH
#define MX_BATCH 16
#endif
#ifndef MX_IN_DIM
#define MX_IN_DIM 16
#endif
#ifndef MX_OUT_DIM
#define MX_OUT_DIM 16
#endif
#define BATCH MX_BATCH
#define IN_DIM MX_IN_DIM
#define OUT_DIM MX_OUT_DIM

iree_status_t Run(void) {
	// Exp 1b: confirm gemmini MMIO is reachable from this load context
	// before we enter IREE. If this hangs, no IREE-driven hang downstream
	// is meaningful — the runtime load context itself is the issue.
	preflight_flush();

	// Path A: hand-rolled gold matmul (same MMIO sequence as
	// matmul_16x16_fp8_ref-baremetal). Now self-contained — handles
	// its own FLUSH, CONFIG_EX, scale-factor load, and the rest in the
	// exact order the reference uses (so we don't accidentally clobber
	// SF state with a stray FLUSH between init and CONFIG_EX).
	preflight_gold_matmul();

	iree_vm_instance_t *instance = NULL;
	IREE_RETURN_IF_ERROR(iree_vm_instance_create(
		IREE_VM_TYPE_CAPACITY_DEFAULT, iree_allocator_system(), &instance));
	IREE_RETURN_IF_ERROR(iree_hal_module_register_all_types(instance));

	iree_hal_device_t *device = NULL;
	IREE_RETURN_IF_ERROR(
		create_sample_device(iree_allocator_system(), &device));

	iree_hal_device_group_t *device_group = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_device_group_create_from_device(
		device, iree_allocator_system(), &device_group));

	iree_vm_module_t *hal_module = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_module_create(instance,
		iree_hal_module_device_policy_default(), device_group,
		IREE_HAL_MODULE_FLAG_SYNCHRONOUS,
		iree_hal_module_debug_sink_stdio(stderr), iree_allocator_system(),
		&hal_module));
	iree_hal_device_group_release(device_group);

	const iree_const_byte_span_t module_data =
		iree_make_const_byte_span(_binary_mxgemmini_vcs_vmfb_start,
			(size_t)(_binary_mxgemmini_vcs_vmfb_end -
				_binary_mxgemmini_vcs_vmfb_start));
	iree_vm_module_t *bytecode_module = NULL;
	IREE_RETURN_IF_ERROR(iree_vm_bytecode_module_create(instance,
		IREE_VM_BYTECODE_MODULE_FLAG_NONE, module_data, iree_allocator_null(),
		iree_allocator_system(), &bytecode_module));

	iree_vm_context_t *context = NULL;
	iree_vm_module_t *modules[] = {hal_module, bytecode_module};
	IREE_RETURN_IF_ERROR(iree_vm_context_create_with_modules(instance,
		IREE_VM_CONTEXT_FLAG_NONE, IREE_ARRAYSIZE(modules), &modules[0],
		iree_allocator_system(), &context));
	iree_vm_module_release(hal_module);
	iree_vm_module_release(bytecode_module);

	iree_vm_function_t main_function;
	IREE_RETURN_IF_ERROR(iree_vm_context_resolve_function(
		context, iree_make_cstring_view("module.mlp_3layer"), &main_function));

	// Deterministic 16x16 i8 input. Forced to 0x40 (= 2.0 in FP8 e4m3)
	// across the board for the debug fixture so we can compare against
	// the working matmul_16x16_fp8_ref-baremetal reference's known output
	// 0x4280 (= 64.0 = 16 × 2.0 × 2.0). Once the dispatch is verified
	// end-to-end, swap back to kMxGemminiTestInput for the general case.
	int8_t A[BATCH][IN_DIM];
	memset(A, 0x40, sizeof(A));

	iree_hal_dim_t shapeA[2] = {BATCH, IN_DIM};
	iree_hal_buffer_params_t params = {
		.type = IREE_HAL_MEMORY_TYPE_DEVICE_LOCAL,
		.usage = IREE_HAL_BUFFER_USAGE_DEFAULT};

	iree_hal_buffer_view_t *bvA = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_buffer_view_allocate_buffer_copy(device,
		iree_hal_device_allocator(device), 2, shapeA,
		IREE_HAL_ELEMENT_TYPE_SINT_8, IREE_HAL_ENCODING_TYPE_DENSE_ROW_MAJOR,
		params, iree_make_const_byte_span(A, sizeof(A)), &bvA));

	// Diagnostic: bvA address — log so we can compare against the
	// in-band dispatch trace later. NOTE: do NOT overwrite the buffer
	// contents here; allocate_buffer_copy already populated bvA with
	// the 0x40 bytes the matmul needs to see.
	{
		iree_hal_buffer_t *buf = iree_hal_buffer_view_buffer(bvA);
		fprintf(stdout, "[iree-bind] bvA: buf=%p len=%lu\n", (void *)buf,
			(unsigned long)iree_hal_buffer_byte_length(buf));
		iree_hal_buffer_mapping_t mapping;
		iree_status_t map_status = iree_hal_buffer_map_range(buf,
			IREE_HAL_MAPPING_MODE_SCOPED, IREE_HAL_MEMORY_ACCESS_READ, 0,
			IREE_HAL_WHOLE_BUFFER, &mapping);
		if (iree_status_is_ok(map_status)) {
			volatile uint8_t *p = mapping.contents.data;
			fprintf(stdout,
				"[iree-bind] mapped DRAM=%p first8: %02x %02x %02x %02x %02x "
				"%02x %02x %02x\n",
				(void *)p, p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]);
			iree_hal_buffer_unmap_range(&mapping);
		} else {
			fprintf(stdout, "[iree-bind] map failed\n");
			iree_status_free(map_status);
		}
		fflush(stdout);
	}

	// async-external ABI: (input, wait_fence, signal_fence) → (output).
	iree_hal_semaphore_t *sem_wait = NULL;
	IREE_RETURN_IF_ERROR(
		iree_hal_semaphore_create(device, IREE_HAL_QUEUE_AFFINITY_ANY,
			/*initial_value=*/1, IREE_HAL_SEMAPHORE_FLAG_NONE, &sem_wait));
	iree_hal_fence_t *wait_fence = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_fence_create_at(
		sem_wait, /*value=*/1, iree_allocator_system(), &wait_fence));
	iree_hal_semaphore_release(sem_wait);

	iree_hal_semaphore_t *sem_signal = NULL;
	IREE_RETURN_IF_ERROR(
		iree_hal_semaphore_create(device, IREE_HAL_QUEUE_AFFINITY_ANY,
			/*initial_value=*/0, IREE_HAL_SEMAPHORE_FLAG_NONE, &sem_signal));
	iree_hal_fence_t *signal_fence = NULL;
	IREE_RETURN_IF_ERROR(iree_hal_fence_create_at(
		sem_signal, /*value=*/1, iree_allocator_system(), &signal_fence));
	iree_hal_semaphore_release(sem_signal);

	iree_vm_list_t *inputs = NULL;
	IREE_RETURN_IF_ERROR(iree_vm_list_create(iree_vm_make_undefined_type_def(),
		3, iree_allocator_system(), &inputs));
	iree_vm_ref_t refA = iree_hal_buffer_view_move_ref(bvA);
	iree_vm_ref_t refWait = iree_hal_fence_move_ref(wait_fence);
	iree_vm_ref_t refSignal = iree_hal_fence_move_ref(signal_fence);
	iree_vm_list_push_ref_move(inputs, &refA);
	iree_vm_list_push_ref_move(inputs, &refWait);
	iree_vm_list_push_ref_move(inputs, &refSignal);

	iree_vm_list_t *outputs = NULL;
	IREE_RETURN_IF_ERROR(iree_vm_list_create(iree_vm_make_undefined_type_def(),
		1, iree_allocator_system(), &outputs));

	// Force d-cache writeback so gemmini's MVIN (via TileLink DMA) sees
	// the 0x40s the IREE copy wrote. Without this, the buffer contents
	// can sit in L1 dcache while gemmini reads stale zeros from main
	// DRAM.
	__sync_synchronize();
	asm volatile("fence rw,rw");
	asm volatile("fence iorw,iorw");

	// Paint the DRAM trace area at 0x80200000..0x80200020 with a known
	// sentinel BEFORE the dispatch. The compiler emits volatile stores
	// to this region inside the dispatch. After invoke we read back —
	// the only way to see paint values is if the dispatch never ran the
	// trace path; non-zero compiler values mean trace stored real ptrs;
	// zero values mean trace ran but stored zeros (i.e., binding_ptrs were
	// NULL).
	{
		volatile uint64_t *trace_paint = (volatile uint64_t *)0x80200000;
		trace_paint[0] = 0xBEFA1FEBEFA1FEB0ULL;
		trace_paint[1] = 0xBEFA1FEBEFA1FEB1ULL;
		trace_paint[2] = 0xBEFA1FEBEFA1FEB2ULL;
		trace_paint[3] = 0xBEFA1FEBEFA1FEB3ULL;
		__sync_synchronize();
		fprintf(stdout,
			"[iree-paint-dram] painted 0x80200000..0x80200020 with BEFORE "
			"pattern\n");
		fflush(stdout);
	}

	fprintf(stdout, "[mxgemmini-vcs] invoking module.mlp_3layer...\n");
	fflush(stdout);

	IREE_RETURN_IF_ERROR(
		iree_vm_invoke(context, main_function, IREE_VM_INVOCATION_FLAG_NONE,
			NULL, inputs, outputs, iree_allocator_system()));

	IREE_RETURN_IF_ERROR(iree_hal_fence_wait(
		signal_fence, iree_infinite_timeout(), IREE_ASYNC_WAIT_FLAG_NONE));
	iree_hal_fence_release(signal_fence);
	iree_hal_fence_release(wait_fence);

	iree_hal_buffer_view_t *ret_bv =
		iree_vm_list_get_buffer_view_assign(outputs, 0);
	int32_t res[BATCH * OUT_DIM];
	IREE_RETURN_IF_ERROR(iree_hal_device_transfer_d2h(device,
		iree_hal_buffer_view_buffer(ret_bv), 0, res, sizeof(res),
		IREE_HAL_TRANSFER_BUFFER_FLAG_DEFAULT, iree_infinite_timeout()));

	// mxGemmini debug readout: the WS-MX dispatch writes its bf16 result
	// to spad address 128 (the c_spad_addr we set in LOOP_WS). On
	// RadianceGemminiOnlyConfig that spad is memory-mapped into the SoC
	// window at 0x40000000 + spad_addr*16 bytes per row (matmul_tiled_fp8.c
	// references this layout). Print this FIRST so we see it even if the
	// IREE i32 dump hits the sim timeout.
	// Compact post-IREE SMEM probe — same row-128 (C output) and
	// row-0 (A input via MVIN) cells we used post-gold so we can
	// compare. If IREE's MVIN read 0x40s, row0 should be 0x40404040.
	// If IREE's compute landed at the right c_spad, row128 should be
	// 0x42804280 (= bf16 64.0 packed). Anything else tells us where
	// the IREE binding plumbing went wrong.
	{
		volatile uint32_t *p = (volatile uint32_t *)0x40000000;
		fprintf(stdout,
			"[iree] row0=0x%08x row128=0x%08x (expect "
			"row0=0x40404040 row128=0x42804280 if IREE binding works)\n",
			p[0 * 4 + 0], p[128 * 4 + 0]);
		// 2026-05-11 IREE-binding trace: the compiler's
		// tiledMatmulOuterLoopWsSpad emits volatile stores of the
		// runtime A/B/C pointers to SMEM cells 0xFE0/0xFE8/0xFF0
		// right before the A pre-MVIN loop. Read them back to see
		// what binding_ptrs[*] actually resolved to. Compare to the
		// 0x8009ab00 (or whatever) address the IREE allocator gave us.
		volatile uint64_t *trace = (volatile uint64_t *)0x80200000;
		fprintf(stdout,
			"[iree-trace] sentinel=0x%016llx A=0x%016llx B=0x%016llx "
			"C=0x%016llx\n",
			(unsigned long long)trace[0], (unsigned long long)trace[1],
			(unsigned long long)trace[2], (unsigned long long)trace[3]);
		fflush(stdout);
	}

	// Print one i32 value per line; tools/sim.py diff ignores the prefix
	// lines and matches only on numeric lines. Order is row-major
	// across BATCH×OUT_DIM = 256 cells. UART throughput is slow under VCS
	// so this is intentionally minimal: just first 8 values for sanity.
	fprintf(stdout, "[mxgemmini-vcs] IREE result %dx%d (i32), first 8:\n",
		BATCH, OUT_DIM);
	for (int n = 0; n < 8; ++n) {
		fprintf(stdout, "%ld\n", (long)res[n]);
	}
	fflush(stdout);

	iree_vm_list_release(inputs);
	iree_vm_list_release(outputs);
	iree_hal_device_release(device);
	iree_vm_context_release(context);
	iree_vm_instance_release(instance);

	fprintf(stdout, "[mxgemmini-vcs] PASS\n");
	return iree_ok_status();
}

int main(void) {
	const iree_status_t result = Run();
	if (!iree_status_is_ok(result)) {
		iree_status_fprint(stderr, result);
		iree_status_free(result);
		return 1;
	}
	return 0;
}
