builtin.module attributes {prov.level = "linalg-on-tensors"} {
  func.func @forward(%0: tensor<1x1x8x8xbf16>, %1: tensor<1x1x2x2xbf16>) -> tensor<1x1x9x9xbf16> {
    %2 = arith.constant {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} 0.000000e+00 : bf16
    %3 = tensor.splat %2 {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<1x1x10x10xbf16>
    %4 = "tensor.insert_slice"(%0, %3) <{static_offsets = array<i64: 0, 0, 1, 1>, static_sizes = array<i64: 1, 1, 8, 8>, static_strides = array<i64: 1, 1, 1, 1>, operandSegmentSizes = array<i32: 1, 1, 0, 0, 0>}> {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : (tensor<1x1x8x8xbf16>, tensor<1x1x10x10xbf16>) -> tensor<1x1x10x10xbf16>
    %5 = tensor.empty() : tensor<1x2x2x1x9x9xbf16>
    %6 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d0, (d4 + d1), (d5 + d2))>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%4 : tensor<1x1x10x10xbf16>) outs(%5 : tensor<1x2x2x1x9x9xbf16>) attrs =  {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} {
    ^bb0(%7: bf16, %8: bf16):
      linalg.yield %7 : bf16
    } -> tensor<1x2x2x1x9x9xbf16>
    %9 = tensor.collapse_shape %6 [[0 : i64, 1 : i64, 2 : i64, 3 : i64, 4 : i64, 5 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<1x2x2x1x9x9xbf16> into tensor<324xbf16>
    %10 = tensor.expand_shape %9 [[0 : i64, 1 : i64]] output_shape [4, 81] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<324xbf16> into tensor<4x81xbf16>
    %11 = tensor.collapse_shape %1 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<1x1x2x2xbf16> into tensor<4xbf16>
    %12 = tensor.expand_shape %11 [[0 : i64, 1 : i64]] output_shape [1, 4] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<4xbf16> into tensor<1x4xbf16>
    %13 = arith.constant {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} 0.000000e+00 : bf16
    %14 = tensor.splat %13 {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<1x81xbf16>
    %15 = linalg.matmul {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} ins(%12, %10 : tensor<1x4xbf16>, tensor<4x81xbf16>) outs(%14 : tensor<1x81xbf16>) -> tensor<1x81xbf16>
    %16 = tensor.collapse_shape %15 [[0 : i64, 1 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<1x81xbf16> into tensor<81xbf16>
    %17 = tensor.expand_shape %16 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] output_shape [1, 1, 9, 9] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<81xbf16> into tensor<1x1x9x9xbf16>
    func.return %17 : tensor<1x1x9x9xbf16>
  }
}
