# lit configuration for the merlin pass-test suite.
#
# NOTE ON PATH RESOLUTION: this file is executed by llvm-lit's own interpreter, which is NOT the
# repo venv and cannot import merlin. So it locates the repo by walking up for a marker file rather
# than by a fixed parent index -- location-independent for the same reason the test-layout rule
# forbids Path(__file__).parents[N], achieved without importing anything.
#
# A missing tool marks the suite UNSUPPORTED. It must never silently succeed: a verification suite
# that could not run and reported green is the exact failure this layer exists to prevent.
import os
import shutil

import lit.formats

config.name = "merlin-pass-tests"
config.test_format = lit.formats.ShTest(execute_external=False)
config.suffixes = [".mlir"]
config.excludes = ["AGENT.md", "README.md"]


def _repo_root(start):
    cur = os.path.abspath(start)
    while True:
        if os.path.isfile(os.path.join(cur, "pyproject.toml")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            raise RuntimeError("repo root not found (no pyproject.toml above %s)" % start)
        cur = parent


ROOT = _repo_root(os.path.dirname(__file__))
LLVM_BIN = os.path.join(ROOT, "third_party", "llvm-build", "bin")
VENV_PY = os.path.join(ROOT, ".venv", "bin", "python")

config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = config.test_source_root


def _tool(name):
    cand = os.path.join(LLVM_BIN, name)
    return cand if os.path.isfile(cand) else shutil.which(name)


filecheck = _tool("FileCheck")
mlir_opt = _tool("mlir-opt")
python = VENV_PY if os.path.isfile(VENV_PY) else shutil.which("python3")

missing = [n for n, v in (("FileCheck", filecheck), ("mlir-opt", mlir_opt), ("python", python))
           if not v]
if missing:
    config.unsupported = True
else:
    # merlin-opt runs out of THIS checkout. The shared venv may have merlin installed from a
    # different worktree, so PYTHONPATH is pinned rather than inherited.
    #
    # MERLIN_LIT_PYTHONPATH overrides that pin, and exists for exactly one caller: the historical
    # replay (merlin.verify.replay) runs this suite against a SHADOW copy of the package with old
    # files written over it, to find out whether these tests would have rejected a defect that
    # actually shipped. Without the override the suite would silently test the current tree and
    # report a clean pass for every historical defect -- a check that could not run reporting success,
    # which is the failure this whole layer exists to avoid. Unset, behaviour is unchanged.
    config.environment["PYTHONPATH"] = (os.environ.get("MERLIN_LIT_PYTHONPATH")
                                        or os.path.join(ROOT, "merlin", "python"))
    config.environment["HOME"] = os.environ.get("HOME", "/tmp")
    config.substitutions.append(
        ("%merlin-opt", "%s -m merlin.xdsl_dialects.opt" % python))
    config.substitutions.append(("%filecheck", filecheck))
    config.substitutions.append(("%mlir-opt", mlir_opt))
    # %iface-irdl points at a SIGIL-NORMALIZED copy of the frozen grammar's IRDL. The tracked file
    # is generated by tblgen-to-irdl, which writes a custom type's symbol name with its `!` sigil
    # included (irdl.type @"!resident"). That name is unspellable, so mlir-opt rejects every module
    # using !merlin_iface.resident / !merlin_iface.acc -- i.e. every real capsule. The fix belongs in
    # the generator; until then this normalization (idempotent, a no-op once fixed) lets the frozen
    # grammar actually be verified. See docs/design/compiler_verification.md.
    _irdl_src = os.path.join(ROOT, "merlin", "contract", "merlin_iface.irdl.mlir")
    _irdl_dst = os.path.join(ROOT, "out", "artifacts", "cache", "verify",
                             "merlin_iface.normalized.irdl.mlir")
    os.makedirs(os.path.dirname(_irdl_dst), exist_ok=True)
    with open(_irdl_src) as _f:
        _txt = _f.read()
    for _bad, _good in (('irdl.type @"!', 'irdl.type @"'), ('::@"!', '::@"')):
        _txt = _txt.replace(_bad, _good)
    with open(_irdl_dst, "w") as _f:
        _f.write(_txt)
    config.substitutions.append(("%iface-irdl", _irdl_dst))
    mlir_translate = _tool("mlir-translate")
    if mlir_translate:
        config.substitutions.append(("%mlir-translate", mlir_translate))
        config.available_features.add("mlir-translate")
    try:
        import subprocess
        subprocess.run([python, "-c", "import z3"], check=True, capture_output=True)
        config.available_features.add("z3")
    except Exception:
        pass
