"""Ingest OpenBLAS RISC-V vector kernels (``kernel/riscv64/``).

OpenBLAS ships hand- and generator-written RVV kernels in four filename families:
``*_rvv.c`` (RVV 1.0 intrinsics), ``*_vector*.c`` (older intrinsic spellings),
``*_kernel_<MR>x<NR>_zvl{128,256}b.c`` (autogenerated GEMM/TRMM register-blocked kernels)
and ``*_c910v.c`` (T-Head C910). Scalar fallbacks (e.g. plain ``amax.c``) are skipped and
counted. The leading letter(s) of a GEMM-family filename encode the dtype
(``s/d/c/z/sb/sh``); BLAS1/2 kernels are precision-generic via ``DOUBLE`` macros, so their
dtype is honestly ``unknown``. Pure text parsing — nothing is compiled or executed.

The filename convention is a real grammar, so it is *tokenized* here rather than pattern-matched:
each name is split on ``_`` / ``.`` boundaries and each field validated. A name that does not fit
the grammar is never silently dropped — it falls through to the BLAS-family reading, whose op is
reported verbatim, and an op outside the known roots is surfaced in ``diagnostics``.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterator

from merlin.kernels.types import NormalizedKernel

_VECTOR_SUFFIXES = ("_rvv.c", "_c910v.c")

#: Filename tokens naming the vectorization VARIANT rather than the routine. Dropped before the
#: op/dtype decision, but only where the old substitution dropped them: the token must be preceded
#: by ``_`` (so a leading ``vector_...`` survives) and followed by ``_`` or by the ``.c`` extension
#: (so ``_rvvx``/``_vectorish`` survive). ``vector_v2`` is tried before ``vector`` — same as the
#: optional-group ordering it replaces, including the backtrack: ``_vector_v2x`` drops ``_vector``
#: only, because ``_vector_v2`` is not followed by a boundary.
_VARIANT_TOKENS = ("rvv", "c910v", "vector_v2", "vector")

_KERNEL_INFIX = "kernel_"
_VLEN_PREFIX, _VLEN_SUFFIX = "zvl", "b"
_C910V = "c910v"

# dtype letter(s) for the autogenerated GEMM family, longest-first.
_DTYPE_PREFIX = (("sb", "bf16"), ("sh", "f16"), ("s", "f32"), ("d", "f64"),
                 ("c", "c32"), ("z", "c64"))

# BLAS op roots, longest/most-specific first. ncopy/tcopy are the *pack* routines.
_OP_ROOTS = (
    ("gemm_ncopy", "pack"), ("gemm_tcopy", "pack"), ("gemm_beta", "scal"),
    ("omatcopy", "transpose"), ("trmm", "trmm"), ("gemv", "gemv"), ("gemm", "gemm"),
    ("symv", "symv"), ("hemv", "hemv"), ("axpby", "axpby"), ("axpy", "axpy"),
    ("amax", "amax"), ("amin", "amin"), ("asum", "asum"), ("nrm2", "nrm2"),
    ("copy", "copy"), ("dot", "dot"), ("rotm", "rot"), ("rot", "rot"),
    ("scal", "scal"), ("swap", "swap"), ("sum", "sum"), ("max", "max"), ("min", "min"),
)
_KNOWN_OPS = frozenset(op for _root, op in _OP_ROOTS)

# The prefix alphabet of the GEMM family: dtype letters + the routine root, never a separator.
_PREFIX_ALPHABET = frozenset("abcdefghijklmnopqrstuvwxyz0123456789")


def _decimal_run(text: str, start: int) -> int:
    """End index of the decimal-digit run at ``start`` (== ``start`` when there is none).

    ``str.isdecimal()`` is exactly the Unicode Nd category the old ``\\d`` matched, so a
    non-ASCII-digit spelling parses here the same way it did (and ``int()`` still accepts it).
    """
    i = start
    while i < len(text) and text[i].isdecimal():
        i += 1
    return i


def _variant_at(name: str, start: int) -> str | None:
    """The variant token beginning at ``start``, if one is there AND is followed by a boundary."""
    for tok in _VARIANT_TOKENS:
        end = start + len(tok)
        if name.startswith(tok, start):
            rest = name[end:]
            if rest.startswith("_") or rest == ".c":
                return tok
    return None


def _drop_variant_tokens(name: str) -> str:
    """``zaxpy_rvv.c`` -> ``zaxpy.c``; ``gemv_t_vector_v2.c`` -> ``gemv_t.c``.

    Walks the name once, consuming ``_<variant>`` runs; scanning resumes after a dropped run, so
    back-to-back variants (``a_vector_v2_rvv.c``) all go, exactly as the substitution did.
    """
    out: list[str] = []
    i, n = 0, len(name)
    while i < n:
        if name[i] == "_":
            tok = _variant_at(name, i + 1)
            if tok is not None:
                i += 1 + len(tok)
                continue
        out.append(name[i])
        i += 1
    return "".join(out)


def _parse_gemm_kernel(name: str) -> tuple[str, str, dict] | None:
    """Parse ``dgemm_kernel_8x4_zvl128b.c``-style names -> (op, dtype, shape).

    Grammar: ``<prefix>[_]kernel_<MR>x<NR>_(zvl<bits>b|c910v).c`` where ``<prefix>`` is one or more
    lowercase alphanumerics (no separator — so ``d_gemm_kernel_…`` is NOT this family) and the
    trailing field is the whole remainder. The *leftmost* ``kernel_`` that lets the rest parse wins,
    matching the non-greedy prefix it replaces (``kernel_kernel_2x2_zvl256b.c`` -> prefix ``kernel``).
    """
    if not name.endswith(".c"):
        return None
    stem = name[:-2]
    at = stem.find(_KERNEL_INFIX)
    while at != -1:
        prefix = stem[:at]
        if prefix.endswith("_"):          # the optional separator between prefix and "kernel_"
            prefix = prefix[:-1]
        parsed = (_parse_kernel_tail(stem[at + len(_KERNEL_INFIX):])
                  if prefix and all(ch in _PREFIX_ALPHABET for ch in prefix) else None)
        if parsed is not None:
            mr, nr, vlen = parsed
            break
        at = stem.find(_KERNEL_INFIX, at + 1)
    else:
        return None

    dtype = "unknown"
    for letters, dt in _DTYPE_PREFIX:
        if prefix.startswith(letters) and len(prefix) > len(letters):
            dtype, prefix = dt, prefix[len(letters):]
            break
    op = next((op for root, op in _OP_ROOTS if prefix.startswith(root)), prefix or "unknown")
    shape: dict = {"MR": mr, "NR": nr}
    if vlen is not None:
        shape["vlen_bits"] = vlen
    return op, dtype, shape


def _parse_kernel_tail(tail: str) -> tuple[int, int, int | None] | None:
    """``8x4_zvl128b`` -> ``(8, 4, 128)``; ``8x4_c910v`` -> ``(8, 4, None)``; else ``None``."""
    mr_end = _decimal_run(tail, 0)
    if mr_end == 0 or not tail.startswith("x", mr_end):
        return None
    nr_end = _decimal_run(tail, mr_end + 1)
    if nr_end == mr_end + 1 or not tail.startswith("_", nr_end):
        return None
    mr, nr = int(tail[:mr_end]), int(tail[mr_end + 1:nr_end])
    field = tail[nr_end + 1:]
    if field == _C910V:
        return mr, nr, None
    if field.startswith(_VLEN_PREFIX) and field.endswith(_VLEN_SUFFIX):
        bits = field[len(_VLEN_PREFIX):-len(_VLEN_SUFFIX)]
        if bits and _decimal_run(bits, 0) == len(bits):
            return mr, nr, int(bits)
    return None


def _parse_blas(name: str) -> tuple[str, str] | None:
    """Parse ``zaxpy_rvv.c`` / ``gemv_n_vector.c``-style names -> (op, dtype)."""
    stem = _drop_variant_tokens(name)[:-2].rstrip("_")
    # index variants (iamax/izamin) reduce to the same decision as the base op
    if stem.startswith("i"):
        stem = stem[1:]
    dtype = "unknown"
    for letters, dt in (("sb", "bf16"), ("z", "c64"), ("ds", "f32")):
        rest = stem[len(letters):]
        if stem.startswith(letters) and any(rest.startswith(root) for root, _ in _OP_ROOTS):
            dtype, stem = dt, rest
            break
    op = next((op for root, op in _OP_ROOTS if stem.startswith(root)), None)
    return (op, dtype) if op else (stem.split("_")[0] or "unknown", dtype)


def _is_vector_kernel(name: str) -> bool:
    return (name.endswith(_VECTOR_SUFFIXES) or "_vector" in name
            or _parse_gemm_kernel(name) is not None)


def ingest_openblas(repo: str, target: str = "rvv", limit: int | None = None,
                    diagnostics: dict | None = None) -> Iterator[NormalizedKernel]:
    """Yield NormalizedKernels for OpenBLAS vector kernels under ``repo``.

    Globs ``kernel/riscv64/*.c``; scalar fallbacks are skipped (counted in
    ``diagnostics['scalar_skipped']`` when a dict is passed). A vector kernel whose op is not one of
    the known BLAS roots is still ingested — under the routine token read off its own name — and
    listed in ``diagnostics['unrecognized_ops']``, so a spelling this grammar does not know shows up
    as a reported gap instead of a silently mislabelled record.
    """
    root = Path(repo)
    kdir = root / "kernel" / "riscv64"
    if not kdir.is_dir():  # tolerate being pointed at the kernel dir itself
        kdir = root
    count = scalar_skipped = 0
    unrecognized: dict[str, str] = {}
    for path in sorted(kdir.glob("*.c")):
        name = path.name
        if not _is_vector_kernel(name):
            scalar_skipped += 1
            continue
        parsed = _parse_gemm_kernel(name)
        if parsed:
            op, dtype, shape = parsed
        else:
            op, dtype = _parse_blas(name)
            shape = {}
        if op not in _KNOWN_OPS:
            unrecognized[name] = op
        try:
            rel = str(path.relative_to(root))
        except ValueError:
            rel = str(path)
        yield NormalizedKernel(
            source="openblas", target=target, path=rel, op=op, dtype=dtype, shape=shape,
            raw_text=path.read_text(encoding="utf-8", errors="replace"),
        )
        count += 1
        if limit is not None and count >= limit:
            break
    if diagnostics is not None:
        diagnostics["scalar_skipped"] = scalar_skipped
        diagnostics["vector_kernels"] = count
        diagnostics["unrecognized_ops"] = dict(sorted(unrecognized.items()))
