"""GX1 / OV11: gemmini is GENERATABLE as an out-of-tree target package.

gemmini used to be the one reference target that could not go through the deterministic
capability-manifest derive path — it shipped a hand-curated ``target_contract.yaml`` but no
``residual.yaml``, so ``manifest_for("gemmini")`` raised and ``write_oot_target("gemmini", ...)``
was impossible. It now ships ``contracts/residual.yaml`` beside the reference contract, so it is
discovered and regenerated by the SAME target-agnostic path (``capability_manifests``) every other
target uses — the interchange OOT-package format resolvable via ``MERLIN_TARGET_PATH``.

These tests pin two things: (1) the residual stays consistent with the curated reference contract
(the deriver reproduces it field-for-field, adding only the empty ``legality`` default), and (2) the
generated package has the shape the registry + runner require. They need no hardware and no mlc —
gemmini is an all-residual prototype (no ``facts_source``).
"""
from __future__ import annotations

import yaml

from merlin.common.paths import repo_root
from merlin.targetgen import capability_manifests as cm
from merlin.targetgen import target_registry as tr


def _curated() -> dict:
    path = repo_root() / "merlin" / "targets" / "gemmini" / "contracts" / "target_contract.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def test_gemmini_is_discovered_and_in_manifests():
    """The residual makes gemmini appear in the DISCOVERED set (from the curated reference base), so
    ``MANIFESTS`` — derived from discovery, not a hardcoded list — includes it."""
    discovered = cm.discovered_targets()
    assert "gemmini" in discovered
    assert sorted(cm.MANIFESTS) == discovered


def test_manifest_for_gemmini_reproduces_the_curated_contract():
    """All-residual prototype: with no RTL facts to layer, the deriver reproduces the residual (==the
    curated reference contract) field-for-field and adds ONLY the empty ``legality`` default. This pins
    the residual to the committed reference contract so the two cannot silently drift."""
    m = cm.manifest_for("gemmini")
    curated = _curated()
    # ``legality`` plus the per-run capability audit; both are derived, neither is curated (pinning
    # the audit into the reference contract would let a stale evidence block look authoritative).
    assert set(m) - set(curated) == {"legality",
                                     "capability_evidence", "semantic_capabilities_derived",
        "semantic_capabilities_unknown", "unmapped_observations"}
    assert m["legality"] == []
    for key, val in curated.items():
        assert m[key] == val, f"gemmini.{key} drifted from the curated reference contract"
    cm.validate(m)   # schema-valid + compute_units parse (raises on any problem)


def test_write_oot_target_gemmini_produces_the_interchange_package(tmp_path, monkeypatch):
    """``write_oot_target`` materializes the full interchange package (contract + dialect_plan +
    AGENT.md); it resolves via MERLIN_TARGET_PATH as an EXTERNAL target — the OV11 eviction shape —
    with its runtime backend + endpoint derived from the generated contract."""
    root = cm.write_oot_target("gemmini", tmp_path / "gemmini-mlir")
    assert (root / "contracts" / "target_contract.yaml").is_file()
    assert (root / "contracts" / "dialect_plan.yaml").is_file()
    assert (root / "AGENT.md").is_file()

    monkeypatch.setenv("MERLIN_TARGET_PATH", str(root))
    info = tr.resolve("gemmini")
    assert info.kind == "external"
    assert info.contract_path == root / "contracts" / "target_contract.yaml"
    contract = info.load_contract()
    assert contract["endpoint_kind"] == "inline_asm_insn"
    assert info.backend == "baremetal"          # derived from runtime.default_backend, not a name map


def test_gemmini_dialect_plan_derived_from_units():
    """The generated dialect plan is DERIVED from the capability model's compute units — one
    ``<unit>_tensor`` type and the union of the units' ops — not invented."""
    plan = cm.dialect_plan_from_manifest(cm.manifest_for("gemmini"))
    assert plan["target"] == "gemmini" and plan["dialect_name"] == "gemmini"
    assert {t["name"] for t in plan["types"]} == {"systolic_mesh_tensor"}
    assert {o["name"] for o in plan["ops"]} == {"matmul"}
