"""The capsule contract's vocabularies must not be closed lists that go stale.

Three vocabularies in ``capsule.schema.json`` were closed enums written when gemmini was the only
target, and each rejected a LATER target's whole corpus at load time — not one capsule, all of them,
before any grading could happen:

* ``dtype`` — 7 tokens, missing every MX format the corpus builder emits and spelling half precision
  ``f16``, a spelling the builder never writes;
* ``operation.op`` — missing ``rmsnorm``, which ``corpus_spec.BUILDERS`` has a builder for;
* ``expected.modes`` — gemmini's eight modes with ``additionalProperties: false``.

The corpora were generated by this repo's own tooling, so the generator and the validator disagreed
with nothing tying them together. These tests tie them together.
"""
from __future__ import annotations

import pytest

from merlin.common import quant_formats as qf
from merlin.common.paths import repo_root
from merlin.targetgen import coverage_report as CV
from merlin.targetgen.capsule_common import discover_capsules, load_capsule
from merlin.targetgen.contract.schemas import (ContractViolation, load_schema,
                                               validate_capsule)
from merlin.targetgen.corpus_spec import BUILDERS

CAPSULES = repo_root() / "merlin" / "contract" / "capsules"

#: Corpus dirs that exist in this checkout. A per-target corpus is a directory of capsule dirs split by
#: kind; the shared parent also holds schemas/profiles, so it is not itself a corpus.
CORPORA = sorted(p.name for p in CAPSULES.iterdir()
                 if p.is_dir() and any(p.rglob("capsule.yaml")))


@pytest.mark.parametrize("corpus", CORPORA)
def test_every_corpus_in_the_tree_loads(corpus):
    """A tracked corpus must load. This is the regression: two of them could not, so their targets
    could not be graded at all, and the failure surfaced only when a run was launched."""
    caps = discover_capsules(CAPSULES / corpus)
    assert caps, f"corpus {corpus} has capsule.yaml files but discover_capsules returned none"


def _a_capsule() -> dict:
    """Any real capsule, as the base for mutation tests."""
    one = sorted(CAPSULES.rglob("capsule.yaml"))[0]
    cap = load_capsule(one.parent)
    cap.pop("__dir__", None)
    return cap


def test_an_unregistered_dtype_is_still_rejected():
    """Opening the enum must not open the door: the vocabulary moved to the registry, it did not go
    away. A typo has to fail closed, or a capsule could be graded in a format nothing can size."""
    cap = _a_capsule()
    cap["inputs"][0]["dtype"] = "bfl16"          # transposed letters, a plausible typo
    with pytest.raises(ContractViolation) as e:
        validate_capsule(cap)
    assert "bfl16" in str(e.value)


def test_the_numeric_policy_dtype_is_checked_too():
    """The second dtype site. It had its own copy of the same enum, so it needs its own check."""
    cap = _a_capsule()
    cap["numeric_policy"]["dtype"] = "not_a_format"
    with pytest.raises(ContractViolation):
        validate_capsule(cap)


@pytest.mark.parametrize("token", ["mxfp8", "mxfp6", "mxfp4", "fp16", "bf16", "fp8_e4m3", "i8", "i32"])
def test_the_formats_the_corpus_builder_emits_are_accepted(token):
    """Every dtype a generated corpus actually contains must validate — registry formats and the plain
    machine accumulator widths beside them."""
    assert qf.is_element_dtype(token)
    cap = _a_capsule()
    cap["inputs"][0]["dtype"] = token
    validate_capsule(cap)


def test_the_op_enum_covers_every_builder():
    """The op vocabulary IS closed (an op is only expressible if the tooling can build it), so the
    closed list has to be pinned against the builders. Adding a builder without adding it here is what
    made radiance's corpus unloadable over `rmsnorm`."""
    enum = set(load_schema("capsule")["properties"]["operation"]["properties"]["op"]["enum"])
    missing = sorted(set(BUILDERS) - enum)
    assert not missing, f"corpus_spec.BUILDERS can emit {missing}, which capsule.schema.json rejects"


def test_a_corpus_declared_mode_is_counted_not_dropped():
    """A mode outside gemmini's eight must appear in the coverage report of the corpus that declares
    it. The aggregator used to filter on the baseline list, so such a mode was declared, graded, and
    then silently absent from its own coverage row."""
    cap = _a_capsule()
    cap["name"] = "MODE_PROBE"
    cap["expected"]["modes"] = {"rmsnorm": True}
    validate_capsule(cap)          # open vocabulary: this must pass validation at all

    results = [{"capsule": "MODE_PROBE", "status": "pass", "kind": "isa", "label": "public"}]
    cov = CV.aggregate(results, capsules=[cap])
    assert cov["mode_coverage"]["rmsnorm"] == 1
    # ...and ONLY what this corpus declares. The baseline list is one target's mode vocabulary, so
    # seeding it here reported `conv2d` / `padded_edge` as not-covered holes on a SIMT target and on a
    # command-buffer OPU -- the same category error the class axis had.
    assert set(cov["mode_coverage"]) == {"rmsnorm"}
    assert "| rmsnorm | 1 |" in CV.render_markdown(cov, results)


def test_a_traced_class_outside_the_baseline_is_counted():
    """Same fail-open on the instruction-class axis: a self-hosted-ISA target names its classes
    nothing like gemmini's RoCC ones, so filtering on the baseline reports 0 for everything it ran."""
    cap = _a_capsule()
    cap["name"] = "CLASS_PROBE"
    results = [{"capsule": "CLASS_PROBE", "status": "pass", "kind": "isa", "label": "public"}]
    traces = {"CLASS_PROBE": {"instructions": [{"class": "MXUMatMul"}, {"class": "MVIN"}]}}
    cov = CV.aggregate(results, capsules=[cap], traces=traces)
    assert cov["instruction_class_coverage"]["MXUMatMul"] == 1
    assert cov["instruction_class_coverage"]["MVIN"] == 1
    # No target resolves here, so the axes are exactly what the traces exercised -- never a baseline
    # seed. `FLUSH` belongs to one specific machine; reporting it as "not covered" for a target that
    # cannot execute it states a coverage gap where there is a category error.
    assert set(cov["instruction_class_coverage"]) == {"MXUMatMul", "MVIN"}


def test_the_aggregate_still_validates_against_the_coverage_schema(tmp_path):
    """Widening the axes must not produce an artifact the contract rejects."""
    cap = _a_capsule()
    cap["name"] = "SCHEMA_PROBE"
    cap["expected"]["modes"] = {"rmsnorm": True}
    results = [{"capsule": "SCHEMA_PROBE", "status": "pass", "kind": "isa", "label": "public"}]
    cov = CV.aggregate(results, capsules=[cap],
                       traces={"SCHEMA_PROBE": {"instructions": [{"class": "MXUMatMul"}]}})
    CV.write(cov, tmp_path / "coverage.json", tmp_path / "report.md", results)
    assert (tmp_path / "coverage.json").is_file()


def test_the_registry_is_the_source_and_the_schema_names_it():
    """The schema must point a reader at the vocabulary's real home rather than implying it is here."""
    schema = load_schema("capsule")
    desc = schema["properties"]["inputs"]["items"]["properties"]["dtype"]["description"]
    assert "quant_formats.registry.yaml" in desc
    assert "mxfp8" in qf.names()


def test_a_machine_width_is_parsed_structurally_and_a_float_spelling_is_not_guessed():
    """`machine_bits` must recognize the accumulator spellings and refuse the MLIR float ones, which
    name registry formats — guessing a width from a prefix is how a wrong element size gets silently
    baked into every downstream buffer offset."""
    assert qf.machine_bits("i32") == 32
    assert qf.machine_bits("int8") == 8
    assert qf.machine_bits("f32") == 32
    assert qf.machine_bits("f8E4M3FN") is None
    assert qf.machine_bits("fp16") is None       # a registry name, not a machine width
    assert qf.machine_bits("i") is None


def test_the_address_map_can_size_every_dtype_in_the_tree():
    """The third copy of the dtype table lived in capsule_dram, and it knew neither the MX formats nor
    `fp16` — so an mx_gemmini/radiance capsule that LOADED would still die at address-map time, which is
    later and much less obviously the same bug."""
    from merlin.targetgen import capsule_dram as DR
    for corpus in CORPORA:
        for cap in discover_capsules(CAPSULES / corpus):
            for t in cap.get("inputs") or []:
                assert DR.tensor_nbytes(t["shape"], t["dtype"]) > 0, (corpus, cap["name"], t["dtype"])


@pytest.mark.parametrize("token,bits", [("mxfp8", 8), ("mxfp6", 6), ("mxfp4", 4), ("fp16", 16),
                                        ("i32", 32), ("f8E4M3FN", 8), ("torch.bfloat16", 16)])
def test_storage_bits_come_from_the_registry(token, bits):
    from merlin.targetgen import capsule_dram as DR
    assert DR.dtype_bits(token) == bits


def test_a_sub_byte_tensor_is_sized_packed_not_padded():
    """mxfp6 declares `pack: {bits: 6}`, so a 16x32 operand occupies 384 bytes. Rounding each element up
    to a byte would over-stride by a third and mis-place every following tensor."""
    from merlin.targetgen import capsule_dram as DR
    assert DR.tensor_nbytes([16, 32], "mxfp6") == 384
    assert DR.tensor_nbytes([16, 32], "mxfp4") == 256
    with pytest.raises(KeyError):          # "bytes per element" has no integer answer at 6 bits
        DR.dtype_bytes("mxfp6")


def test_an_unsizable_dtype_still_fails_closed():
    from merlin.targetgen import capsule_dram as DR
    with pytest.raises(KeyError) as e:
        DR.dtype_bits("nonesuch")
    assert "quant_formats.registry.yaml" in str(e.value)


@pytest.mark.parametrize("token,expected_bytes", [
    ("i8", 1), ("int8", 1), ("u8", 1), ("fp8_e4m3", 1), ("fp8_e5m2", 1), ("f8E4M3FN", 1), ("f8E5M2", 1),
    ("i16", 2), ("int16", 2), ("f16", 2), ("float16", 2), ("bf16", 2), ("bfloat16", 2),
    ("torch.bfloat16", 2), ("i32", 4), ("int32", 4), ("torch.int32", 4), ("f32", 4), ("float32", 4),
    ("i64", 8), ("int64", 8), ("f64", 8), ("float64", 8)])
def test_the_replaced_literal_table_is_reproduced_exactly(token, expected_bytes):
    """Every token the hand-written `_DTYPE_BYTES` carried must derive to the SAME width. The point of
    replacing a literal table with a derivation is to widen it, never to move an existing address."""
    from merlin.targetgen import capsule_dram as DR
    assert DR.dtype_bytes(token) == expected_bytes
