"""Whole-model observability: every output in full, and a cycle bracket around every device group.

Two opt-in additions to the bare-metal whole-model image, both generated from the build's own
artifacts and both printed on the console the image already uses.

FULL READBACK. The default console protocol prints the first output's leading 4096 words, which
cannot grade a program with several outputs (a prefix and its cache, logits and a key/value cache) or
one large output. With full readback the image prints every forward result, complete, as an
``OUT_BIN v1`` frame (:mod:`merlin.runtime.out_bin`): a text header naming the output, its row/column
shape, element width and signedness, the raw little-endian bytes, and an FNV-1a checksum footer. The
output table is generated from the module's own forward signature.

GROUP PROFILE. Each call the compiled model makes to a routed device group goes through one external
symbol per kernel signature. The build wraps every such symbol the model object references
(``ld --wrap``) with a C function of the identical prototype that reads the cycle counter before and
after the call. The image then prints, after the outputs::

    GROUP_ID <i> <name>     the i-th group call, named after the routed group in program order
    GROUP <i> <cycles>      cycles inside that call
    GAP <i> <cycles>        cycles between the previous call's return (or the forward's start) and it
    GAP <n> <cycles>        cycles from the last call's return to the forward's end

The lines are target-neutral and printed in that order (all GROUP_IDs, then GROUP/GAP interleaved),
so a consumer joins per-group cycles to the model's groups and rooflines. Nothing here names a target,
an instruction or a counter: the cycle counter is the standard RISC-V ``rdcycle``.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

#: Trace capacity: calls beyond it are counted as dropped, never silently lost.
TRACE_CAPACITY = 8192

#: (element bytes, signed) per forward-result dtype, the OUT_BIN container format.
_FORMAT = {
    "f32": (4, False),
    "f64": (8, False),
    "f16": (2, False),
    "bf16": (2, False),
    "i64": (8, True),
    "i32": (4, True),
    "i16": (2, True),
    "i8": (1, True),
    "i1": (1, False),
}

#: Floating-point dtypes travel as raw bits (unsigned words) and are reinterpreted on the host.
FLOAT_BITS = {"f32": "<u4", "f64": "<u8", "f16": "<u2", "bf16": "<u2"}


class ReadbackError(ValueError):
    """The image cannot state its outputs or its group calls in full."""


def output_name(index: int) -> str:
    return f"out{int(index)}"


def render_outputs_header(out_specs: Sequence[tuple[Sequence[int], str]]) -> str:
    """``model_outputs.h``: name, rows, cols, element width, signedness and byte count per result."""
    if not out_specs:
        raise ReadbackError("the forward has no result to read back")
    names, rows, cols, widths, signs, sizes = [], [], [], [], [], []
    for index, (shape, dtype) in enumerate(out_specs):
        if dtype not in _FORMAT:
            raise ReadbackError(f"result {index} has dtype {dtype!r}, which full readback cannot carry")
        width, signed = _FORMAT[dtype]
        dims = [int(d) for d in shape]
        count = 1
        for d in dims:
            count *= d
        if count < 1:
            raise ReadbackError(f"result {index} has no elements")
        col = dims[-1] if dims else 1
        names.append(f'"{output_name(index)}"')
        rows.append(str(count // col))
        cols.append(str(col))
        widths.append(str(width))
        signs.append("'s'" if signed else "'u'")
        sizes.append(f"{count * width}ULL")
    return "\n".join(
        [
            "/* Generated by merlin.runtime.whole_model_readback. Do not edit. */",
            "#ifndef MERLIN_MODEL_OUTPUTS_H",
            "#define MERLIN_MODEL_OUTPUTS_H",
            f"static const char *const MERLIN_OUTPUT_NAMES[{len(names)}] = {{{', '.join(names)}}};",
            f"static const unsigned long long MERLIN_OUTPUT_ROWS[{len(names)}] = {{{', '.join(rows)}}};",
            f"static const unsigned long long MERLIN_OUTPUT_COLS[{len(names)}] = {{{', '.join(cols)}}};",
            f"static const unsigned MERLIN_OUTPUT_WIDTH[{len(names)}] = {{{', '.join(widths)}}};",
            f"static const char MERLIN_OUTPUT_SIGN[{len(names)}] = {{{', '.join(signs)}}};",
            f"static const unsigned long long MERLIN_OUTPUT_BYTES[{len(names)}] = {{{', '.join(sizes)}}};",
            "#endif",
            "",
        ]
    )


@dataclass(frozen=True)
class GroupCallee:
    """One external group symbol the model object calls, with the prototype it is called through."""

    symbol: str
    #: ``expanded`` (three rank-r memrefs passed field by field, a rank-r memref returned) or
    #: ``c_interface`` (result pointer, then three descriptor pointers).
    abi: str
    rank: int


def callees(routed: Sequence[Mapping[str, Any]], signatures: Mapping[str, Sequence[int]], undefined: set[str]):
    """The group callees the model object actually references, in a stable order.

    ``undefined`` is the model object's undefined-symbol list; only a referenced name can be wrapped.
    A routed symbol referenced under neither name is refused: its calls would go unbracketed."""
    out: list[GroupCallee] = []
    for symbol in sorted({str(row.get("symbol")) for row in routed if row.get("symbol")}):
        key = signatures.get(symbol)
        if key is None or len(key) not in (3, 4):
            raise ReadbackError(f"routed symbol {symbol} has no 3- or 4-extent signature")
        rank = len(key) - 1
        if symbol in undefined:
            out.append(GroupCallee(symbol, "expanded", rank))
        elif f"_mlir_ciface_{symbol}" in undefined:
            out.append(GroupCallee(f"_mlir_ciface_{symbol}", "c_interface", rank))
        else:
            raise ReadbackError(f"the model object references routed symbol {symbol} under no known name")
    return out


def group_names(routed: Sequence[Mapping[str, Any]]) -> list[tuple[str, str]]:
    """``(g<group index>_<symbol>, symbol)`` per routed group, in program order (the order calls are issued)."""
    names = []
    for row in routed:
        group, symbol = row.get("group"), str(row.get("symbol"))
        names.append((f"g{int(group)}_{symbol}" if group is not None else symbol, symbol))
    return names


def _memref(rank: int) -> str:
    return f"merlin_profile_memref_{rank}d"


def _expanded_params(rank: int) -> tuple[str, str]:
    params, args = [], []
    for letter in "abc":
        fields = [("void *", "alloc"), ("void *", "aligned"), ("intptr_t ", "off")]
        fields += [("intptr_t ", f"s{i}") for i in range(rank)]
        fields += [("intptr_t ", f"st{i}") for i in range(rank)]
        for ctype, field in fields:
            params.append(f"{ctype}{letter}_{field}")
            args.append(f"{letter}_{field}")
    return ", ".join(params), ", ".join(args)


def render_group_profile(callees_: Sequence[GroupCallee], names: Sequence[tuple[str, str]]) -> str:
    """``merlin_group_profile.c``: the wrappers, the trace and the print routine ``model_main`` calls.

    A call is named after the routed group in the same program-order position only when that group
    calls the same symbol; otherwise (a loop, a branch) it is named by its callee, never mislabelled."""
    symbols = [c.symbol for c in callees_]
    base = {c.symbol.removeprefix("_mlir_ciface_"): i for i, c in enumerate(callees_)}
    name_callee = [base.get(symbol, -1) for _name, symbol in names]
    names = [name for name, _symbol in names]
    lines = [
        "/* Generated by merlin.runtime.whole_model_readback. Do not edit. */",
        "#include <stdint.h>",
        "void htif_puts(const char *);",
        "void htif_putc(char);",
        f"#define MERLIN_GROUP_TRACE_CAP {TRACE_CAPACITY}",
        "static uint64_t merlin_group_start[MERLIN_GROUP_TRACE_CAP];",
        "static uint64_t merlin_group_end[MERLIN_GROUP_TRACE_CAP];",
        "static uint16_t merlin_group_callee[MERLIN_GROUP_TRACE_CAP];",
        "static uint64_t merlin_group_count, merlin_group_dropped;",
        "static inline uint64_t merlin_rdcycle(void) {",
        "  uint64_t c;",
        '  __asm__ volatile("rdcycle %0" : "=r"(c));',
        "  return c;",
        "}",
        "static void merlin_group_record(unsigned callee, uint64_t start, uint64_t end) {",
        "  if (merlin_group_count < MERLIN_GROUP_TRACE_CAP) {",
        "    merlin_group_start[merlin_group_count] = start;",
        "    merlin_group_end[merlin_group_count] = end;",
        "    merlin_group_callee[merlin_group_count] = (uint16_t)callee;",
        "    merlin_group_count++;",
        "  } else {",
        "    merlin_group_dropped++;",
        "  }",
        "}",
    ]
    for rank in sorted({c.rank for c in callees_}):
        lines += [
            "typedef struct {",
            "  void *allocated;",
            "  void *aligned;",
            "  intptr_t offset;",
            f"  intptr_t sizes[{rank}];",
            f"  intptr_t strides[{rank}];",
            f"}} {_memref(rank)};",
        ]
    for index, callee in enumerate(callees_):
        memref = _memref(callee.rank)
        if callee.abi == "expanded":
            params, args = _expanded_params(callee.rank)
            lines += [
                f"{memref} __real_{callee.symbol}({params});",
                f"{memref} __wrap_{callee.symbol}({params}) {{",
                "  uint64_t start = merlin_rdcycle();",
                f"  {memref} result = __real_{callee.symbol}({args});",
                f"  merlin_group_record({index}u, start, merlin_rdcycle());",
                "  return result;",
                "}",
            ]
        else:
            proto = f"{memref} *result, const {memref} *a, const {memref} *b, const {memref} *c"
            lines += [
                f"void __real_{callee.symbol}({proto});",
                f"void __wrap_{callee.symbol}({proto}) {{",
                "  uint64_t start = merlin_rdcycle();",
                f"  __real_{callee.symbol}(result, a, b, c);",
                f"  merlin_group_record({index}u, start, merlin_rdcycle());",
                "}",
            ]
    callee_names = ", ".join(f'"{s}"' for s in symbols) or '""'
    group_list = ", ".join(f'"{n}"' for n in names) or '""'
    lines += [
        f"static const char *const merlin_callee_names[] = {{{callee_names}}};",
        f"static const char *const merlin_group_names[] = {{{group_list}}};",
        f"static const unsigned long long merlin_group_name_count = {len(names)}ULL;",
        "static const int merlin_group_name_callee[] = {" + (", ".join(str(i) for i in name_callee) or "-1") + "};",
        "static void merlin_put_u64(uint64_t v) {",
        "  char buf[24];",
        "  int i = 0;",
        "  do { buf[i++] = (char)('0' + (v % 10)); v /= 10; } while (v);",
        "  while (i) htif_putc(buf[--i]);",
        "}",
        "static void merlin_line(const char *tag, uint64_t index, uint64_t value) {",
        "  htif_puts(tag); htif_putc(' '); merlin_put_u64(index); htif_putc(' '); merlin_put_u64(value);",
        "  htif_putc('\\n');",
        "}",
        "uint64_t merlin_group_profile_now(void) { return merlin_rdcycle(); }",
        "void merlin_group_profile_dump(uint64_t forward_start, uint64_t forward_end) {",
        "  for (uint64_t i = 0; i < merlin_group_count; i++) {",
        "    htif_puts(\"GROUP_ID \"); merlin_put_u64(i); htif_putc(' ');",
        "    int named = i < merlin_group_name_count && merlin_group_name_callee[i] == (int)merlin_group_callee[i];",
        "    htif_puts(named ? merlin_group_names[i] : merlin_callee_names[merlin_group_callee[i]]);",
        "    htif_putc('\\n');",
        "  }",
        "  uint64_t previous = forward_start;",
        "  for (uint64_t i = 0; i < merlin_group_count; i++) {",
        '    merlin_line("GAP", i, merlin_group_start[i] - previous);',
        '    merlin_line("GROUP", i, merlin_group_end[i] - merlin_group_start[i]);',
        "    previous = merlin_group_end[i];",
        "  }",
        '  merlin_line("GAP", merlin_group_count, forward_end - previous);',
        "  htif_puts(\"METRIC group_calls \"); merlin_put_u64(merlin_group_count); htif_putc('\\n');",
        "  htif_puts(\"METRIC group_calls_dropped \"); merlin_put_u64(merlin_group_dropped); htif_putc('\\n');",
        "}",
    ]
    return "\n".join(lines) + "\n"


def wrap_flags(callees_: Sequence[GroupCallee]) -> list[str]:
    return [f"-Wl,--wrap={c.symbol}" for c in callees_]


def parse_group_profile(text: str) -> dict[str, Any] | None:
    """``{groups: [{index, name, cycles, gap_before}], tail_gap, calls, dropped}`` or ``None`` when absent.

    Refuses an inconsistent record: every GROUP needs its GROUP_ID and its preceding GAP, indices run
    from zero without holes, and the tail GAP closes the list."""
    names: dict[int, str] = {}
    cycles: dict[int, int] = {}
    gaps: dict[int, int] = {}
    metrics: dict[str, int] = {}
    seen = False
    for line in text.splitlines():
        parts = line.split()
        if not parts:
            continue
        tag = parts[0]
        if tag == "GROUP_ID" and len(parts) == 3:
            seen = True
            names[int(parts[1])] = parts[2]
        elif tag in ("GROUP", "GAP") and len(parts) == 3:
            seen = True
            index, value = int(parts[1]), int(parts[2])
            (cycles if tag == "GROUP" else gaps)[index] = value
        elif tag == "METRIC" and len(parts) == 3 and parts[1] in ("group_calls", "group_calls_dropped"):
            metrics[parts[1]] = int(parts[2])
    if not seen:
        return None
    count = len(cycles)
    if set(cycles) != set(range(count)) or set(names) != set(range(count)) or set(gaps) != set(range(count + 1)):
        raise ReadbackError("the group profile is incomplete: GROUP, GROUP_ID and GAP indices disagree")
    if metrics.get("group_calls", count) != count:
        raise ReadbackError("the group profile's call count disagrees with its records")
    return {
        "groups": [{"index": i, "name": names[i], "cycles": cycles[i], "gap_before": gaps[i]} for i in range(count)],
        "tail_gap": gaps[count],
        "calls": count,
        "dropped": metrics.get("group_calls_dropped", 0),
    }


def decode_outputs(
    outputs: Mapping[str, list], frames: Mapping[str, Any], out_specs: Sequence[tuple[Sequence[int], str]]
):
    """The decoded OUT_BIN frames as ``[numpy array]`` in forward-result order, in their own dtypes."""
    import numpy as np

    arrays = []
    for index, (shape, dtype) in enumerate(out_specs):
        name = output_name(index)
        if name not in outputs or name not in frames:
            raise ReadbackError(f"the console carries no complete frame for result {index}")
        width, signed = _FORMAT[dtype]
        frame = frames[name]
        if frame.word_bytes != width or bool(frame.signed) != signed:
            raise ReadbackError(f"result {index}'s frame format differs from its declared dtype {dtype}")
        words = np.asarray(outputs[name], dtype=np.int64 if signed else np.uint64).reshape(-1)
        if dtype in FLOAT_BITS:
            raw = words.astype(np.dtype(FLOAT_BITS[dtype]))
            if dtype == "bf16":
                value = (raw.astype(np.uint32) << 16).view(np.float32)
            else:
                value = raw.view({"f32": np.float32, "f64": np.float64, "f16": np.float16}[dtype])
        elif dtype == "i1":
            value = words.astype(np.uint8)
        else:
            value = words.astype({"i64": np.int64, "i32": np.int32, "i16": np.int16, "i8": np.int8}[dtype])
        expected = 1
        for d in shape:
            expected *= int(d)
        if value.size != expected:
            raise ReadbackError(f"result {index} printed {value.size} of {expected} elements")
        arrays.append(value.reshape([int(d) for d in shape]) if shape else value.reshape(()))
    if set(outputs) - {output_name(i) for i in range(len(out_specs))}:
        raise ReadbackError("the console carries frames for results the forward does not have")
    return arrays


__all__ = [
    "GroupCallee",
    "ReadbackError",
    "callees",
    "decode_outputs",
    "group_names",
    "output_name",
    "parse_group_profile",
    "render_group_profile",
    "render_outputs_header",
    "wrap_flags",
]
