"""The C adapter between compiled host code and a device kernel.

The host side of an offloaded contraction is an MLIR function call. Its lowered private declaration
passes a memref as ``(allocated, aligned, offset, sizes..., strides...)`` -- seven scalars for a rank-2
operand -- but calls the external ``_mlir_ciface_*`` as a result-descriptor pointer followed by one
pointer per operand descriptor. The device side is the target's own kernel. Under the logical
kernel ABI (the default, ``logical_kernel_abi`` in the OOT backend contract) it takes dense row-major
logical tensors in the order the group's interface declares them; a support that selects the
version-1 resident ABI (``harness_abi.kernel_abi_version: 1``) gets
``void {target}_kernel(weight, lhs_0.., out_0..)`` with edge tiles zero-padded to the tile edge.
Neither side can call the other directly, so something has to unpack one convention into the other.
That is all this emits.

Deliberately NOT emitted here: the kernel itself. The device kernel is the target's own backend
artifact -- the thing its OOT package builds and the thing the capsule ladder certifies -- and
regenerating a transcription of it here would mean a model executes code no oracle ever graded. The
shim declares the kernel ``extern`` and the archive supplies it.

One structural choice worth stating: a single ``void*``-based descriptor serves every element type.
The shim only passes pointers through -- it never reads an element -- and pointer fields have the same
size and alignment whatever they point at, so the struct is ABI-identical for i8, i32, f32 or a
microscaled format alike. The alternative, a typedef per dtype, is what forces the existing
matrix-unit shim to know which dtypes exist.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, replace
from typing import Any

__all__ = ["KernelAbi", "ShimUnit", "emit_translation_unit", "emit_dense_translation_unit", "kernel_abi_for"]

_PREAMBLE = """/* Generated by merlin.llvmlower.device_shim for device {device!r}. Do not edit.
 *
 * Adapts the MLIR lowered-memref calling convention to {device!r}'s kernel ABI. The kernel is
 * declared extern: it is the target's own backend artifact and is supplied by the archive, so what
 * a model executes is the code the capsule ladder certified rather than a transcription of it.
 */
#include <stdint.h>

/* MLIR passes a memref as (allocated, aligned, offset, sizes..., strides...) and returns it as a
 * struct of the same shape. Pointer fields have one size and alignment whatever they point at, so
 * one void*-based descriptor is ABI-identical for every element type. */
typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[2];
  intptr_t strides[2];
}} merlin_memref_2d;

typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[3];
  intptr_t strides[3];
}} merlin_memref_3d;

{pointer_guard}

/* The device kernels, per the OOT backend contract's kernel_abi. Supplied by the archive.
 * One per signature: the package emits its entry under a single contract-declared name, so a model
 * with several distinct extents produces several objects that all define it. They are renamed apart
 * at build time and declared apart here; sharing one name links, and silently binds every call to
 * whichever object the linker happened to resolve first. */
{externs}

{entries}
/* {n} entry point(s) emitted. */
"""

_RANK2_POINTER_GUARD = """
/* The resident kernel takes flat row-major buffers.  An overlapping output or
 * strided descriptor cannot be repaired by reinterpreting its pointer. */
static int merlin_span(const void *aligned, intptr_t offset, intptr_t rows, intptr_t cols,
                       uintptr_t elem_bytes, uintptr_t *start, uintptr_t *length) {
  if (!aligned || offset < 0 || rows <= 0 || cols <= 0 || !elem_bytes) return 0;
  uintptr_t base = (uintptr_t)aligned, off = (uintptr_t)offset;
  uintptr_t r = (uintptr_t)rows, c = (uintptr_t)cols;
  if (r > UINTPTR_MAX / c || off > UINTPTR_MAX / elem_bytes) return 0;
  uintptr_t elements = r * c;
  /* MLIR descriptor indexing is signed intptr_t, including byte scaling. */
  uintptr_t index_limit = (uintptr_t)INTPTR_MAX / elem_bytes;
  if (elements > index_limit || off > index_limit - elements) return 0;
  if (elements > UINTPTR_MAX / elem_bytes) return 0;
  uintptr_t delta = off * elem_bytes, bytes = elements * elem_bytes;
  if (delta > UINTPTR_MAX - base) return 0;
  uintptr_t address = base + delta;
  if (bytes > UINTPTR_MAX - address) return 0;
  *start = address; *length = bytes;
  return 1;
}

static int merlin_disjoint(const void *a, uintptr_t a_bytes, const void *b, uintptr_t b_bytes) {
  uintptr_t x = (uintptr_t)a, y = (uintptr_t)b;
  if (!x || !y || a_bytes > UINTPTR_MAX - x || b_bytes > UINTPTR_MAX - y) return 0;
  return x + a_bytes <= y || y + b_bytes <= x;
}
"""

# A catalog with this ABI owns its edge tiles internally. Passing a padded copy would change
# its row pitch, and looping over batch slices here would repeat its own batched loop.
_DENSE_ENTRY = """
merlin_memref_{rank} {symbol}(
    {args})
{{
  if ({shape_check}) {{
    merlin_memref_{rank} bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    {bad_fields}
    return bad;
  }}
  if ({stride_check}) __builtin_trap();
  (void)a_alloc; (void)b_alloc;
  uintptr_t a_addr, b_addr, c_addr, a_bytes, b_bytes, c_bytes;
  if (!merlin_span(a_aligned, a_off, {a_rows}, {a_cols}, {lhs_bytes}u, &a_addr, &a_bytes) ||
      !merlin_span(b_aligned, b_off, {b_rows}, {b_cols}, {rhs_bytes}u, &b_addr, &b_bytes) ||
      !merlin_span(c_aligned, c_off, {c_rows}, {c_cols}, {out_bytes}u, &c_addr, &c_bytes) ||
      !merlin_disjoint((void *)a_addr, a_bytes, (void *)c_addr, c_bytes) ||
      !merlin_disjoint((void *)b_addr, b_bytes, (void *)c_addr, c_bytes))
    __builtin_trap();
  {kernel}((void *)a_addr, (void *)b_addr, (void *)c_addr);
  merlin_memref_{rank} r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  {return_fields}
  return r;
}}
"""

_ENTRY_2D = """
/* {symbol}: M={m} N={n} K={k}, datapath {dtypes}. Extents are re-read from the descriptors, so this
 * entry stays correct if it is ever called with others. */
merlin_memref_2d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1,
    intptr_t a_st0, intptr_t a_st1,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1,
    intptr_t b_st0, intptr_t b_st1,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1,
    intptr_t c_st0, intptr_t c_st1)
{{
  /* The generated-time extents are a CHECK, never the arithmetic: the entry reads its shape from the
   * descriptors so it stays correct if it is ever called with others, and refuses loudly if the
   * caller's shape contradicts the kernel this entry was specialized for. Silently computing the
   * wrong extent is the failure this prevents. */
  if (a_s0 != {m} || a_s1 != {k} || b_s0 != {k} || b_s1 != {n} || c_s0 != {m} || c_s1 != {n}) {{
    merlin_memref_2d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.strides[0] = 0; bad.strides[1] = 0;
    return bad;
  }}
  if (a_st0 != {k} || a_st1 != 1 || b_st0 != {n} || b_st1 != 1 ||
      c_st0 != {n} || c_st1 != 1) __builtin_trap();
  (void)a_alloc; (void)b_alloc;
  uintptr_t a_addr, b_addr, c_addr, a_bytes, b_bytes, c_bytes;
  if (!merlin_span(a_aligned, a_off, a_s0, a_s1, {lhs_bytes}u, &a_addr, &a_bytes) ||
      !merlin_span(b_aligned, b_off, b_s0, b_s1, {rhs_bytes}u, &b_addr, &b_bytes) ||
      !merlin_span(c_aligned, c_off, c_s0, c_s1, {out_bytes}u, &c_addr, &c_bytes) ||
      !merlin_disjoint((void *)a_addr, a_bytes, (void *)c_addr, c_bytes) ||
      !merlin_disjoint((void *)b_addr, b_bytes, (void *)c_addr, c_bytes))
    __builtin_trap();
  {call}
  merlin_memref_2d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1;
  r.strides[0] = c_st0; r.strides[1] = c_st1;
  return r;
}}
"""


_ENTRY_2D_PADDED = """
/* {symbol}: M={m} N={n} K={k}, datapath {dtypes}, tile edge {edge}.
 *
 * The kernel ABI states its operands are row-major with edge tiles ZERO-PADDED to a multiple of the
 * tile edge. These extents are not, so the raw buffers cannot be handed over: the kernel would stride
 * by the padded width through unpadded data and read a neighbouring row as if it were its own. That
 * does not fault -- it returns plausible, wrong numbers.
 *
 * Padded staging is therefore part of the contract, not an optimisation. Copies are byte-wise so this
 * stays independent of the element type; the row loop is the only place the extents appear. */
static unsigned char {symbol}_a[{mp} * {kp} * {lhs_bytes}];
static unsigned char {symbol}_b[{kp} * {np_} * {rhs_bytes}];
static unsigned char {symbol}_c[{mp} * {np_} * {out_bytes}];

merlin_memref_2d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1,
    intptr_t a_st0, intptr_t a_st1,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1,
    intptr_t b_st0, intptr_t b_st1,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1,
    intptr_t c_st0, intptr_t c_st1)
{{
  if (a_s0 != {m} || a_s1 != {k} || b_s0 != {k} || b_s1 != {n} || c_s0 != {m} || c_s1 != {n}) {{
    merlin_memref_2d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.strides[0] = 0; bad.strides[1] = 0;
    return bad;
  }}
  if (a_st0 != {k} || a_st1 != 1 || b_st0 != {n} || b_st1 != 1 ||
      c_st0 != {n} || c_st1 != 1) __builtin_trap();
  (void)a_alloc; (void)b_alloc;
  {{
    uintptr_t a_addr, b_addr, c_addr, a_bytes, b_bytes, c_bytes;
    if (!merlin_span(a_aligned, a_off, a_s0, a_s1, {lhs_bytes}u, &a_addr, &a_bytes) ||
        !merlin_span(b_aligned, b_off, b_s0, b_s1, {rhs_bytes}u, &b_addr, &b_bytes) ||
        !merlin_span(c_aligned, c_off, c_s0, c_s1, {out_bytes}u, &c_addr, &c_bytes) ||
        !merlin_disjoint((void *)a_addr, a_bytes, (void *)c_addr, c_bytes) ||
        !merlin_disjoint((void *)b_addr, b_bytes, (void *)c_addr, c_bytes))
      __builtin_trap();
    const unsigned char *src_a = (const unsigned char *)a_addr;
    const unsigned char *src_b = (const unsigned char *)b_addr;
    unsigned char *dst_c = (unsigned char *)c_addr;
    long i, j;
    for (i = 0; i < {mp} * {kp} * {lhs_bytes}; ++i) {symbol}_a[i] = 0;
    for (i = 0; i < {kp} * {np_} * {rhs_bytes}; ++i) {symbol}_b[i] = 0;
    for (i = 0; i < {mp} * {np_} * {out_bytes}; ++i) {symbol}_c[i] = 0;
    for (i = 0; i < {m}; ++i)
      for (j = 0; j < {k} * {lhs_bytes}; ++j)
        {symbol}_a[i * {kp} * {lhs_bytes} + j] = src_a[i * {k} * {lhs_bytes} + j];
    for (i = 0; i < {k}; ++i)
      for (j = 0; j < {n} * {rhs_bytes}; ++j)
        {symbol}_b[i * {np_} * {rhs_bytes} + j] = src_b[i * {n} * {rhs_bytes} + j];
    {kernel}({symbol}_b, {symbol}_a, {symbol}_c);
    for (i = 0; i < {m}; ++i)
      for (j = 0; j < {n} * {out_bytes}; ++j)
        dst_c[i * {n} * {out_bytes} + j] = {symbol}_c[i * {np_} * {out_bytes} + j];
  }}
  merlin_memref_2d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1;
  r.strides[0] = c_st0; r.strides[1] = c_st1;
  return r;
}}
"""


_ENTRY_3D = """
/* {symbol}: B={b} M={m} N={n} K={k}, datapath {dtypes}{padnote}.
 *
 * A batch is a LOOP, not a third tile axis. The device contracts two dimensions and reduces a third;
 * a batch is many of those, and each slice's operands and result are disjoint, so the batched form is
 * the same kernel called B times with the leading offset advanced. Growing a second kernel for it
 * would need its own legality and its own certification to say anything.
 *
 * The staging buffers are reused across slices, which is sound only because the slices run in
 * sequence -- that is a property of this loop, not of the buffers. */
{staging}
merlin_memref_3d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1, intptr_t a_s2,
    intptr_t a_st0, intptr_t a_st1, intptr_t a_st2,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1, intptr_t b_s2,
    intptr_t b_st0, intptr_t b_st1, intptr_t b_st2,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1, intptr_t c_s2,
    intptr_t c_st0, intptr_t c_st1, intptr_t c_st2)
{{
  if (a_s0 != {b} || a_s1 != {m} || a_s2 != {k} || b_s0 != {b} || b_s1 != {k} || b_s2 != {n}
      || c_s0 != {b} || c_s1 != {m} || c_s2 != {n}) {{
    merlin_memref_3d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.sizes[2] = 0;
    bad.strides[0] = 0; bad.strides[1] = 0; bad.strides[2] = 0;
    return bad;
  }}
  /* One command per disjoint dense slice, never a guessed broadcast or stride. */
  if (a_st0 != {a_slice} || a_st1 != {k} || a_st2 != 1 ||
      b_st0 != {b_slice} || b_st1 != {n} || b_st2 != 1 ||
      c_st0 != {c_slice} || c_st1 != {n} || c_st2 != 1) __builtin_trap();
  (void)a_alloc; (void)b_alloc;
  uintptr_t a_addr, b_addr, c_addr, a_bytes, b_bytes, c_bytes;
  if (!merlin_span(a_aligned, a_off, {a_rows}, {k}, {lhs_bytes}u, &a_addr, &a_bytes) ||
      !merlin_span(b_aligned, b_off, {b_rows}, {n}, {rhs_bytes}u, &b_addr, &b_bytes) ||
      !merlin_span(c_aligned, c_off, {c_rows}, {n}, {out_bytes}u, &c_addr, &c_bytes) ||
      !merlin_disjoint((void *)a_addr, a_bytes, (void *)c_addr, c_bytes) ||
      !merlin_disjoint((void *)b_addr, b_bytes, (void *)c_addr, c_bytes)) __builtin_trap();
  {{
    long slice;
    for (slice = 0; slice < {b}; ++slice) {{
      const unsigned char *src_a = (const unsigned char *)(a_addr + (uintptr_t)slice * {a_slice} * {lhs_bytes});
      const unsigned char *src_b = (const unsigned char *)(b_addr + (uintptr_t)slice * {b_slice} * {rhs_bytes});
      unsigned char *dst_c = (unsigned char *)(c_addr + (uintptr_t)slice * {c_slice} * {out_bytes});
{body}
    }}
  }}
  merlin_memref_3d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1; r.sizes[2] = c_s2;
  r.strides[0] = c_st0; r.strides[1] = c_st1; r.strides[2] = c_st2;
  return r;
}}
"""

#: Direct call, when every extent already sits on the tile edge.
_BODY_3D_DIRECT = """      {kernel}({call_args});"""

#: Staged call, when an extent misses the edge. Same contract as the rank-2 padded entry.
_BODY_3D_STAGED = """      {{
        long i, j;
        for (i = 0; i < {mp} * {kp} * {lhs_bytes}; ++i) {symbol}_a[i] = 0;
        for (i = 0; i < {kp} * {np_} * {rhs_bytes}; ++i) {symbol}_b[i] = 0;
        for (i = 0; i < {mp} * {np_} * {out_bytes}; ++i) {symbol}_c[i] = 0;
        for (i = 0; i < {m}; ++i)
          for (j = 0; j < {k} * {lhs_bytes}; ++j)
            {symbol}_a[i * {kp} * {lhs_bytes} + j] = src_a[i * {k} * {lhs_bytes} + j];
        for (i = 0; i < {k}; ++i)
          for (j = 0; j < {n} * {rhs_bytes}; ++j)
            {symbol}_b[i * {np_} * {rhs_bytes} + j] = src_b[i * {n} * {rhs_bytes} + j];
        {kernel}({symbol}_b, {symbol}_a, {symbol}_c);
        for (i = 0; i < {m}; ++i)
          for (j = 0; j < {n} * {out_bytes}; ++j)
            dst_c[i * {n} * {out_bytes} + j] = {symbol}_c[i * {np_} * {out_bytes} + j];
      }}"""

_STAGING_3D = """static unsigned char {symbol}_a[{mp} * {kp} * {lhs_bytes}];
static unsigned char {symbol}_b[{kp} * {np_} * {rhs_bytes}];
static unsigned char {symbol}_c[{mp} * {np_} * {out_bytes}];"""


def _c_interface_wrapper(symbol: str, rank: int) -> str:
    """Bridge the exact MLIR C interface to this shim's flattened descriptor entry.

    ``llvm.emit_c_interface`` lowers an external result-bearing memref function to
    ``void _mlir_ciface_name(result*, arg0*, arg1*, arg2*)``. The private MLIR
    function builds these descriptors and reads the result back after the call.
    """
    descriptor = f"merlin_memref_{rank}d"
    groups = []
    for name in ("a", "b", "c"):
        fields = [f"{name}->{field}" for field in ("allocated", "aligned", "offset")]
        fields.extend(f"{name}->sizes[{axis}]" for axis in range(rank))
        fields.extend(f"{name}->strides[{axis}]" for axis in range(rank))
        groups.append(", ".join(fields))
    call = ",\n      ".join(groups)
    return (
        f"\n/* MLIR's emitted external C interface: result first, then descriptor pointers. */\n"
        f"void _mlir_ciface_{symbol}({descriptor} *result, const {descriptor} *a,\n"
        f"                          const {descriptor} *b, const {descriptor} *c)\n"
        f"{{\n  *result = {symbol}(\n      {call});\n}}\n"
    )


@dataclass(frozen=True)
class KernelAbi:
    """The device kernel's symbol, argument order and pointee layout under the selected kernel ABI."""

    symbol: str
    arg_order: str = ""
    pointee_layout: str = ""
    #: 2 = the logical ABI (dense logical tensors, interface declaration order); 1 = the resident ABI.
    version: int = 1


@dataclass(frozen=True)
class ShimUnit:
    """The emitted translation unit, and what it declined."""

    text: str
    symbols: tuple[str, ...] = ()
    #: The contract's base kernel name (what the package emits before renaming).
    kernel: str = ""
    #: Every distinct kernel symbol this unit calls, i.e. what the archive must define.
    kernels: tuple[str, ...] = ()
    skipped: tuple[tuple[str, str], ...] = ()
    #: Explicit emitter-owned identity plus caller-proved complete kernel writes.
    writer_contracts: tuple[dict, ...] = ()


def kernel_abi_for(device: str) -> KernelAbi | None:
    """The device's kernel ABI, or None when the contract cannot be read.

    The version is the selected support's (``harness_abi.kernel_abi_version``, default the logical ABI).
    The symbol pattern lives in the shared contract rather than here, so a target that names its entry
    differently changes a declaration and not this emitter.
    """
    try:
        from merlin.targetgen.contract.harness_abi import LEGACY_KERNEL_ABI_VERSION, kernel_abi_version_for

        if kernel_abi_version_for(device) == LEGACY_KERNEL_ABI_VERSION:
            from merlin.targetgen.contract.schemas import render_legacy_kernel_abi

            blk = render_legacy_kernel_abi(device)
            sym = str(blk.get("symbol") or "")
            if not sym:
                return None
            return KernelAbi(
                symbol=sym,
                arg_order=str(blk.get("arg_order") or ""),
                pointee_layout=str(blk.get("pointee_layout") or ""),
                version=1,
            )
        import yaml

        from merlin.targetgen.contract.schemas import render_contract_text

        doc = yaml.safe_load(render_contract_text("mlir_oot_backend_contract.yaml", device)) or {}
        blk = doc.get("logical_kernel_abi") or {}
        sym = str(blk.get("symbol") or "")
        if not sym or blk.get("version") != 2:
            return None
        order = blk.get("argument_order") or {}
        return KernelAbi(
            symbol=sym,
            arg_order=" ++ ".join(str(t) for t in order.get("default") or ()),
            pointee_layout=str((blk.get("pointee") or {}).get("layout") or ""),
            version=2,
        )
    except Exception:  # noqa: BLE001 -- an unreadable contract is a real answer: decline
        return None


#: The three memrefs a shim entry receives from the host call, by role.
SHIM_ROLES = ("lhs", "rhs", "out")
#: The version-1 resident ABI's fixed order over those roles: the weight (rhs) first.
_LEGACY_ROLE_ORDER = ("rhs", "lhs", "out")


def _call_args(roles: Sequence[str], names: Mapping[str, str]) -> str:
    return ", ".join(names[role] for role in roles)


#: Operand keys naming a contraction's activation-side and weight-side input, per the command-buffer ABI.
_LHS_KEYS = ("lhs", "a", "q", "p", "ifm", "src")
_RHS_KEYS = ("rhs", "w", "k", "v", "weight")


def logical_argument_roles(interface: str) -> tuple[tuple[str, ...] | None, str]:
    """``(roles, "")`` -- the logical kernel ABI's pointer order for one group interface, over
    :data:`SHIM_ROLES` -- or ``(None, reason)``.

    The order is :func:`merlin.targetgen.contract.harness_render.kernel_arg_order` of the interface,
    the same order a runner-owned capsule harness passes. Each pointer is then named by the role the
    host call supplies it in: the contraction's activation-side input (``lhs``), its weight-side input
    (``rhs``, through a resident handle when the weight is made resident) and the single result
    (``out``). An interface whose logical pointers are not exactly those three -- a fused bias, a
    second result -- has no entry this shim can express and is refused, never called with a guess.
    """
    from merlin.targetgen.contract import harness_render as HR
    from merlin.targetgen.contract.interface_emit import parse_interface_mlir

    try:
        cb = parse_interface_mlir(interface)
        names = HR.kernel_arg_order(cb)
    except Exception as exc:  # noqa: BLE001 -- an interface the logical ABI cannot describe is a refusal
        return None, f"the logical kernel ABI does not resolve this interface ({type(exc).__name__}: {exc})"
    if len(names) != len(SHIM_ROLES):
        return None, f"the logical kernel ABI passes {len(names)} pointers ({names}); this shim adapts (lhs, rhs, out)"
    resident = {
        (cmd.get("operands") or {}).get("dst"): (cmd.get("operands") or {}).get("src")
        for cmd in cb.get("commands") or []
        if cmd.get("opcode") == "RES_PACK"
    }
    role_of: dict[str, str] = {}
    for cmd in cb.get("commands") or []:
        ops = cmd.get("operands") or {}
        lhs = next((ops[key] for key in _LHS_KEYS if isinstance(ops.get(key), str)), None)
        rhs = next((ops[key] for key in _RHS_KEYS if isinstance(ops.get(key), str)), None)
        if lhs is not None and rhs is not None:
            role_of = {lhs: "lhs", resident.get(rhs, rhs): "rhs"}
            break
    outputs = set(HR.logical_outputs(cb, HR.logical_abi().published_by))
    role_of.update({name: "out" for name in names if name in outputs})
    roles = tuple(role_of.get(name, "") for name in names)
    if sorted(roles) != sorted(SHIM_ROLES):
        return None, f"the logical pointers {names} are not one activation, one weight and one result"
    return roles, ""


def _entry_call(kernel: str, roles: Sequence[str], *, logical: bool) -> str:
    """The rank-2 entry's kernel call; the version-1 text is kept byte-identical."""
    if not logical:
        return (
            "/* arg_order is [the single resident weight] ++ [lhs] ++ [outputs]: the rhs is the weight. */\n"
            f"  {kernel}((void *)b_addr, (void *)a_addr, (void *)c_addr);"
        )
    args = _call_args(roles, {"lhs": "(void *)a_addr", "rhs": "(void *)b_addr", "out": "(void *)c_addr"})
    return f"/* pointer order of the logical kernel ABI for this group: {', '.join(roles)} */\n  {kernel}({args});"


def tile_edge_for(device: str) -> int | None:
    """The device's mesh tile edge, derived from its own RTL facts; None when not derivable.

    None is a real answer and the caller must then refuse to emit a padded entry: padding to a guessed
    edge is worse than not padding, because it produces a differently-wrong buffer.
    """
    try:
        from merlin.targetgen.rtl import facts as _f

        body = _f.body_if_present(device)
    except Exception:  # noqa: BLE001
        return None
    edges = set()
    for arr in body.get("arrays") or ():
        if not isinstance(arr, dict):
            return None
        rows, cols = arr.get("rows"), arr.get("cols")
        if type(rows) is not int or type(cols) is not int or rows <= 0 or rows != cols:
            # The current shim stages square tiles. A rectangular mesh cannot
            # safely be represented by choosing its smaller dimension.
            return None
        edges.add(rows)
    return edges.pop() if len(edges) == 1 else None


def _elem_bytes(token: str) -> int | None:
    """Bytes per element, or None for a sub-byte format (whose offset arithmetic is not a byte count)."""
    try:
        from merlin.targetgen.corpus_spec import dtype_info

        return dtype_info(str(token))[2]
    except Exception:  # noqa: BLE001
        return None


def emit_dense_translation_unit(
    device: str,
    signatures: Mapping[str, Sequence[int]],
    dtypes: Mapping[str, Sequence[str]],
    *,
    kernel_symbol_for: Callable[[str], str],
    kernel_fully_written_arguments: tuple[int, ...] | None = None,
) -> ShimUnit:
    """Adapt contiguous MLIR memrefs to catalog kernels taking (lhs, rhs, out).

    The catalog's stated ABI is exact dense row-major input and output, with edge handling
    inside the kernel and a single call for the entire batch. Reject unsupported ranks,
    precisions, strides, overlapping output, and shape drift before calling it.
    """
    if kernel_fully_written_arguments not in (None, (2,)):
        raise ValueError("dense writer contract requires explicit complete output write")
    entries: list[str] = []
    emitted: list[str] = []
    skipped: list[tuple[str, str]] = []
    for sym in sorted(signatures):
        key = tuple(int(v) for v in signatures[sym])
        dt = tuple(str(v) for v in (dtypes.get(sym) or ()))
        if len(key) not in (3, 4) or any(v <= 0 for v in key):
            skipped.append((sym, f"unsupported dense signature {key}"))
            continue
        if len(dt) != 3 or any(_elem_bytes(v) is None for v in dt):
            skipped.append((sym, f"unsupported dense element widths {dt}"))
            continue
        rank = len(key) - 1
        batch, m, n, k = (1, *key) if rank == 2 else key
        dims = ((m, k), (k, n), (m, n)) if rank == 2 else ((batch, m, k), (batch, k, n), (batch, m, n))
        pieces: list[str] = []
        shape_checks: list[str] = []
        stride_checks: list[str] = []
        return_fields: list[str] = []
        bad_fields: list[str] = []
        for letter, shape in zip("abc", dims, strict=True):
            pieces.extend((f"void *{letter}_alloc", f"void *{letter}_aligned", f"intptr_t {letter}_off"))
            pieces.extend(f"intptr_t {letter}_s{i}" for i in range(rank))
            pieces.extend(f"intptr_t {letter}_st{i}" for i in range(rank))
            for i, extent in enumerate(shape):
                shape_checks.append(f"{letter}_s{i} != {extent}")
                pitch = 1
                for trailing in shape[i + 1 :]:
                    pitch *= trailing
                stride_checks.append(f"{letter}_st{i} != {pitch}")
                if letter == "c":
                    return_fields.append(f"r.sizes[{i}] = c_s{i}; r.strides[{i}] = c_st{i};")
                    bad_fields.append(f"bad.sizes[{i}] = 0; bad.strides[{i}] = 0;")
        widths = [_elem_bytes(v) for v in dt]
        entries.append(
            _DENSE_ENTRY.format(
                rank=f"{rank}d",
                symbol=sym,
                args=",\n    ".join(pieces),
                shape_check=" || ".join(shape_checks),
                stride_check=" || ".join(stride_checks),
                a_rows=batch * m,
                a_cols=k,
                b_rows=batch * k,
                b_cols=n,
                c_rows=batch * m,
                c_cols=n,
                lhs_bytes=widths[0],
                rhs_bytes=widths[1],
                out_bytes=widths[2],
                kernel=kernel_symbol_for(sym),
                return_fields="\n  ".join(return_fields),
                bad_fields="\n    ".join(bad_fields),
            )
        )
        emitted.append(sym)
    kernels = tuple(sorted({kernel_symbol_for(sym) for sym in emitted}))
    externs = "\n".join(f"extern void {k}(void *lhs, void *rhs, void *out);" for k in kernels)
    text = (
        _PREAMBLE.format(
            device=device,
            pointer_guard=_RANK2_POINTER_GUARD,
            externs=externs,
            entries="".join(entries),
            n=len(emitted),
        )
        if emitted
        else ""
    )
    writer_contracts = (
        tuple(
            {
                "symbol": sym,
                "declaration_abi": "expanded_memref",
                "result_argument": 2,
                "fully_written_arguments": [2],
                "argument_ranks": [len(signatures[sym]) - 1] * 3,
                "shape": list(signatures[sym]),
                "dtypes": list(dtypes[sym]),
            }
            for sym in emitted
        )
        if kernel_fully_written_arguments is not None
        else ()
    )
    return ShimUnit(
        text=text, symbols=tuple(emitted), kernels=kernels, skipped=tuple(skipped), writer_contracts=writer_contracts
    )


def emit_translation_unit(
    device: str,
    signatures: Mapping[str, Sequence[int]],
    dtypes: Mapping[str, Sequence[str]],
    *,
    kernel_symbol_for: Callable[[str], str] | None = None,
    tile_edge: int | None = None,
    argument_roles: Mapping[str, Sequence[str]] | None = None,
) -> ShimUnit:
    """One entry per signature, adapting the MLIR ABI to ``device``'s kernel.

    Under the logical kernel ABI (version 2) the kernel takes the dense logical tensors, so no entry
    stages or pads, and ``argument_roles[symbol]`` gives the kernel's pointer order over
    :data:`SHIM_ROLES`, resolved from the group's own interface (:func:`logical_argument_roles`). A
    symbol with no resolved order is DECLINED. Under the version-1 resident ABI the order is fixed
    (weight first) and edge tiles are staged to the tile edge.

    ``signatures`` is ``{symbol: (M, N, K)}``, or ``(B, M, N, K)`` for
    independent dense matrix slices, as minted by the offload rewrite; ``dtypes`` is
    ``{symbol: (lhs, rhs, acc)}`` from the same rewrite. They exist as separate symbols only because
    MLIR function types are monomorphic.

    A signature this cannot express -- a sub-byte format, whose element offset is not a byte count, or
    a rank this emitter has no entry shape for -- is DECLINED and reported. Emitting an entry with
    guessed pointer arithmetic would compile, link, and read the wrong bytes.
    """
    abi = kernel_abi_for(device)
    if abi is None:
        return ShimUnit(text="", skipped=(("all", "no readable kernel_abi in the backend contract"),))
    # One kernel per signature by default is WRONG for a package that emits a single contract-named
    # entry, and one shared kernel is wrong for a model with several extents. The caller decides,
    # because only the caller knows how the objects were built and renamed.
    kernel_for = kernel_symbol_for or (lambda _sym: abi.symbol)

    entries: list[str] = []
    emitted: list[str] = []
    skipped: list[tuple[str, str]] = []
    for sym in sorted(signatures):
        key = tuple(int(v) for v in signatures[sym])
        dt = tuple(str(d) for d in (dtypes.get(sym) or ()))
        if len(key) not in (3, 4):
            skipped.append((sym, f"signature {key} has neither 3 nor 4 extents; no entry shape for it"))
            continue
        if len(dt) != 3:
            skipped.append((sym, f"no datapath recorded for {sym}"))
            continue
        widths = [_elem_bytes(d) for d in dt]
        if any(w is None for w in widths):
            skipped.append((sym, f"sub-byte or unknown element width in {dt}; offset arithmetic would be a guess"))
            continue
        batch, (m, n, k) = (None, key) if len(key) == 3 else (key[0], key[1:])
        logical = getattr(abi, "version", 1) == 2
        roles = tuple((argument_roles or {}).get(sym) or ()) if logical else _LEGACY_ROLE_ORDER
        if sorted(roles) != sorted(SHIM_ROLES):
            skipped.append((sym, "no logical kernel argument order over (lhs, rhs, out) was resolved for this symbol"))
            continue
        edge = 1 if logical else (tile_edge if tile_edge is not None else tile_edge_for(device))
        if not edge:
            # Without the edge we cannot know whether this entry needs staging, and emitting the
            # unpadded form "because we did not find out" is the exact failure that produced a model
            # scoring cos 0.9847 where it should score 0.99993. Not knowing is a decline.
            skipped.append(
                (
                    sym,
                    "no derivable tile edge, so whether these extents need padded "
                    "staging is unknown; declining rather than emitting the raw form",
                )
            )
            continue
        needs_pad = any(int(x) % int(edge) for x in (m, n, k))

        def _up(v):
            return ((int(v) + int(edge) - 1) // int(edge)) * int(edge)

        shape = dict(
            symbol=sym,
            m=m,
            n=n,
            k=k,
            dtypes=dt,
            kernel=kernel_for(sym),
            mp=_up(m),
            np_=_up(n),
            kp=_up(k),
            lhs_bytes=widths[0],
            rhs_bytes=widths[1],
            out_bytes=widths[2],
            call_args=_call_args(roles, {"lhs": "(void *)src_a", "rhs": "(void *)src_b", "out": "(void *)dst_c"}),
            call=_entry_call(kernel_for(sym), roles, logical=logical),
        )
        if batch is None:
            entries.append((_ENTRY_2D_PADDED if needs_pad else _ENTRY_2D).format(edge=int(edge), **shape))
        else:
            body = (_BODY_3D_STAGED if needs_pad else _BODY_3D_DIRECT).format(**shape)
            staging = _STAGING_3D.format(**shape) if needs_pad else ""
            entries.append(
                _ENTRY_3D.format(
                    b=int(batch),
                    a_slice=m * k,
                    b_slice=k * n,
                    c_slice=m * n,
                    a_rows=int(batch) * m,
                    b_rows=int(batch) * k,
                    c_rows=int(batch) * m,
                    staging=staging,
                    body=body,
                    padnote=(f", tile edge {int(edge)} (staged)" if needs_pad else ""),
                    **shape,
                )
            )
        entries.append(_c_interface_wrapper(sym, 2 if batch is None else 3))
        emitted.append(sym)

    kernels = sorted({kernel_for(sym) for sym in emitted})
    params = (
        "void *arg_0, void *arg_1, void *arg_2"
        if getattr(abi, "version", 1) == 2
        else "void *weight, void *lhs_0, void *out_0"
    )
    externs = "\n".join(f"extern void {k}({params});" for k in kernels)
    pointer_guard = _RANK2_POINTER_GUARD
    text = (
        _PREAMBLE.format(
            device=device, pointer_guard=pointer_guard, externs=externs, entries="".join(entries), n=len(emitted)
        )
        if emitted
        else ""
    )
    return ShimUnit(
        text=text, symbols=tuple(emitted), kernel=abi.symbol, kernels=tuple(kernels), skipped=tuple(skipped)
    )


# ------------------------------------------------------------------ the logical ABI's general entry
@dataclass(frozen=True)
class LogicalBuffer:
    """One pointer of a kernel's logical interface: its name, direction, host role, shape and dtype.

    ``role`` is how the host call supplies it: ``input_<k>`` / ``weight_<k>`` / ``bias_<k>`` (the
    interface's own tensor roles, numbered in order) and ``out_<k>`` (the k-th result). A role the host
    call does not carry is a value with no host source."""

    name: str
    kind: str
    role: str
    shape: tuple[int, ...]
    dtype: str


def logical_buffers(interface: str) -> tuple[tuple[LogicalBuffer, ...] | None, str]:
    """``(buffers in kernel_arg_order, "")`` for one interface, or ``(None, reason)``.

    The order, shapes and dtypes are :func:`merlin.targetgen.contract.harness_render.logical_interface`'s
    -- what a runner-owned capsule harness passes. Inputs are numbered within their declared role;
    activations (role ``input``) in the order the commands read them (a contraction's left operand
    first), weights and biases in declaration order; results in result order.
    """
    from merlin.targetgen.contract import harness_render as HR
    from merlin.targetgen.contract.interface_emit import parse_interface_mlir

    try:
        cb = parse_interface_mlir(interface)
        ordered = HR.logical_interface(cb, HR.logical_abi())
    except Exception as exc:  # noqa: BLE001 -- an interface the logical ABI cannot describe is a refusal
        return None, f"the logical kernel ABI does not resolve this interface ({type(exc).__name__}: {exc})"
    tensors = cb.get("tensors") or {}
    resident = {
        (cmd.get("operands") or {}).get("dst"): (cmd.get("operands") or {}).get("src")
        for cmd in cb.get("commands") or []
        if cmd.get("opcode") == "RES_PACK"
    }
    read_order: list[str] = []
    for cmd in cb.get("commands") or []:
        ops = cmd.get("operands") or {}
        for key in (*_LHS_KEYS, *_RHS_KEYS):
            value = ops.get(key)
            value = resident.get(value, value) if isinstance(value, str) else None
            if value is not None and value not in read_order:
                read_order.append(value)
    counters: dict[str, int] = {}
    position = {name: index for index, name in enumerate(read_order)}
    inputs = sorted(
        (b.name for b in ordered if b.kind == "input" and (tensors.get(b.name) or {}).get("role", "input") == "input"),
        key=lambda name: position.get(name, len(position)),
    )
    role_of = {name: f"input_{index}" for index, name in enumerate(inputs)}
    out: list[LogicalBuffer] = []
    for buffer in ordered:
        if buffer.kind not in ("input", "output"):
            return None, f"interface value {buffer.name!r} is {buffer.kind}; a group call passes inputs and results"
        if buffer.kind == "output":
            role = f"out_{counters.get('out', 0)}"
            counters["out"] = counters.get("out", 0) + 1
        elif buffer.name in role_of:
            role = role_of[buffer.name]
        else:
            declared = str((tensors.get(buffer.name) or {}).get("role") or "input")
            role = f"{declared}_{counters.get(declared, 0)}"
            counters[declared] = counters.get(declared, 0) + 1
        if _elem_bytes(buffer.dtype) is None:
            return None, f"interface value {buffer.name!r} has a sub-byte or unknown element type {buffer.dtype!r}"
        out.append(
            LogicalBuffer(
                name=buffer.name,
                kind=buffer.kind,
                role=role,
                shape=tuple(int(v) for v in buffer.shape),
                dtype=buffer.dtype,
            )
        )
    return tuple(out), ""


def _memref_typedef(rank: int) -> str:
    if rank == 0:
        return "typedef struct { void *allocated; void *aligned; intptr_t offset; } merlin_lmemref_0d;"
    return (
        f"typedef struct {{ void *allocated; void *aligned; intptr_t offset; intptr_t sizes[{rank}]; "
        f"intptr_t strides[{rank}]; }} merlin_lmemref_{rank}d;"
    )


def _logical_entry(
    symbol: str,
    kernel: str,
    call: Sequence[LogicalBuffer],
    order: Sequence[LogicalBuffer],
    batch: int | None = None,
) -> str:
    """The expanded-memref entry for one call, plus its C-interface wrapper.

    Parameters arrive in the HOST CALL's order (``call`` carries the host shapes); the kernel is called
    in the logical ABI's order. Every buffer is checked against its shape (a contradiction returns an
    empty result rather than reaching the kernel) and must be dense row-major (otherwise trap), and no
    result may overlap another buffer. With ``batch`` every host buffer is ``batch`` disjoint slices of
    the kernel's logical tensor, and the kernel is called once per slice."""
    params: list[str] = []
    shape_checks: list[str] = []
    stride_checks: list[str] = []
    spans: list[str] = []
    voids: list[str] = []
    for index, buf in enumerate(call):
        p = f"p{index}"
        rank = len(buf.shape)
        params += [f"void *{p}_alloc", f"void *{p}_aligned", f"intptr_t {p}_off"]
        params += [f"intptr_t {p}_s{d}" for d in range(rank)] + [f"intptr_t {p}_st{d}" for d in range(rank)]
        pitch = 1
        for d in reversed(range(rank)):
            shape_checks.append(f"{p}_s{d} != {buf.shape[d]}")
            stride_checks.append(f"{p}_st{d} != {pitch}")
            pitch *= buf.shape[d]
        rows = 1
        for extent in buf.shape[:-1]:
            rows *= extent
        cols = buf.shape[-1] if rank else 1
        spans.append(
            f"!merlin_span({p}_aligned, {p}_off, {rows}, {cols}, {_elem_bytes(buf.dtype)}u, &{p}_addr, &{p}_bytes)"
        )
        voids.append(f"(void){p}_alloc;")
    index_of = {buf.role: index for index, buf in enumerate(call)}
    outputs = [index for index, buf in enumerate(call) if buf.kind == "output"]
    disjoint = [
        f"!merlin_disjoint((void *)p{o}_addr, p{o}_bytes, (void *)p{other}_addr, p{other}_bytes)"
        for o in outputs
        for other in range(len(call))
        if other != o and not (call[other].kind == "output" and other < o)
    ]
    single = len(outputs) == 1
    result_t = f"merlin_lmemref_{len(call[outputs[0]].shape)}d" if single else f"{symbol}_results"
    lines: list[str] = []
    if not single:
        fields = " ".join(f"merlin_lmemref_{len(call[o].shape)}d r{k};" for k, o in enumerate(outputs))
        lines.append(f"typedef struct {{ {fields} }} {symbol}_results;")
    addr_decl = ", ".join(f"p{i}_addr, p{i}_bytes" for i in range(len(call)))
    lines.append(f"/* {symbol}: logical kernel ABI, pointer order {', '.join(b.name for b in order)}. */")
    lines.append(f"{result_t} {symbol}(\n    " + ",\n    ".join(params) + ")\n{")
    lines.append(f"  {result_t} r;\n  memset(&r, 0, sizeof r);")
    if shape_checks:
        lines.append(f"  if ({' || '.join(shape_checks)}) return r;")
        lines.append(f"  if ({' || '.join(stride_checks)}) __builtin_trap();")
    lines.append("  " + " ".join(voids))
    lines.append(f"  uintptr_t {addr_decl};")
    guard = " ||\n      ".join(spans + disjoint)
    lines.append(f"  if ({guard})\n    __builtin_trap();")
    if batch is None:
        args = ", ".join(f"(void *)p{index_of[buf.role]}_addr" for buf in order)
        lines.append(f"  {kernel}({args});")
    else:
        args = ", ".join(
            f"(void *)(p{index_of[buf.role]}_addr + (uintptr_t)slice * (p{index_of[buf.role]}_bytes / {batch}u))"
            for buf in order
        )
        lines.append(f"  for (long slice = 0; slice < {batch}; ++slice)\n    {kernel}({args});")
    for k, o in enumerate(outputs):
        target = "r" if single else f"r.r{k}"
        lines.append(f"  {target}.allocated = p{o}_alloc; {target}.aligned = p{o}_aligned; {target}.offset = p{o}_off;")
        for d in range(len(call[o].shape)):
            lines.append(f"  {target}.sizes[{d}] = p{o}_s{d}; {target}.strides[{d}] = p{o}_st{d};")
    lines.append("  return r;\n}")
    descriptors = ", ".join(f"const merlin_lmemref_{len(buf.shape)}d *d{i}" for i, buf in enumerate(call))
    fields: list[str] = []
    for i, buf in enumerate(call):
        fields += [f"d{i}->allocated", f"d{i}->aligned", f"d{i}->offset"]
        fields += [f"d{i}->sizes[{d}]" for d in range(len(buf.shape))]
        fields += [f"d{i}->strides[{d}]" for d in range(len(buf.shape))]
    lines.append(
        f"void _mlir_ciface_{symbol}({result_t} *result, {descriptors})\n"
        f"{{\n  *result = {symbol}(\n      " + ",\n      ".join(fields) + ");\n}"
    )
    return "\n".join(lines) + "\n"


def emit_logical_translation_unit(
    device: str,
    symbols: Mapping[str, tuple[Sequence[LogicalBuffer], Sequence[Mapping[str, Any]]]],
    *,
    kernel_symbol_for: Callable[[str], str],
) -> ShimUnit:
    """One entry per symbol, passing EVERY pointer of the kernel's logical interface.

    ``symbols[s] = (buffers, call)``: the kernel's logical buffers (:func:`logical_buffers`, kernel
    order) and the host call's operands in call order, each ``{"role", "shape", "dtype"}`` -- what the
    rewrite that minted the call supplies (activation, stored weight, folded bias, destinations). Each
    buffer is matched to the call operand with its role; an interface value no operand supplies, or one
    whose host operand has another shape or dtype, is DECLINED by name, never called with a guess.
    """
    entries: list[str] = []
    emitted: list[str] = []
    skipped: list[tuple[str, str]] = []
    ranks: set[int] = set()
    kernels: dict[str, int] = {}
    for sym in sorted(symbols):
        buffers, call = symbols[sym]
        by_role = {buf.role: buf for buf in buffers}
        supplied = {str(op.get("role")): op for op in call}
        missing = [buf for buf in buffers if buf.role not in supplied]
        if missing:
            skipped.append(
                (sym, "; ".join(f"interface value {b.name!r} ({b.role}) has no host source" for b in missing))
            )
            continue
        extra = [role for role in supplied if role not in by_role]
        if extra or len(supplied) != len(call):
            skipped.append(
                (sym, f"the host call passes {sorted(extra) or 'duplicate'} roles the interface does not take")
            )
            continue
        host = {r: tuple(int(v) for v in op.get("shape") or ()) for r, op in supplied.items()}
        # A BATCH IS A LOOP over disjoint slices: every host buffer is the same count of the kernel's
        # logical tensor, so the shim calls the one per-slice kernel once per slice.
        leading = {shape[0] for r, shape in host.items() if len(shape) == len(by_role[r].shape) + 1}
        batch = (
            next(iter(leading))
            if len(leading) == 1
            and all(
                len(shape) == len(by_role[r].shape) + 1 and shape[1:] == by_role[r].shape for r, shape in host.items()
            )
            else None
        )
        disagree = [
            f"interface value {by_role[r].name!r} is {list(by_role[r].shape)} {by_role[r].dtype}, "
            f"the host supplies {list(host[r])} {op.get('dtype')}"
            for r, op in supplied.items()
            if (batch is None and host[r] != by_role[r].shape) or str(op.get("dtype")) != by_role[r].dtype
        ]
        if disagree:
            skipped.append((sym, "; ".join(disagree)))
            continue
        if not any(buf.kind == "output" for buf in buffers):
            skipped.append((sym, "the interface declares no result"))
            continue
        call_buffers = [replace(by_role[str(op["role"])], shape=host[str(op["role"])]) for op in call]
        ranks.update(len(buf.shape) for buf in call_buffers)
        kernel = kernel_symbol_for(sym)
        kernels[kernel] = len(buffers)
        entries.append(_logical_entry(sym, kernel, call_buffers, buffers, batch))
        emitted.append(sym)
    if not emitted:
        return ShimUnit(text="", skipped=tuple(skipped))
    typedefs = "\n".join(_memref_typedef(rank) for rank in sorted(ranks))
    externs = "\n".join(
        f"extern void {k}({', '.join(f'void *arg_{i}' for i in range(n))});" for k, n in sorted(kernels.items())
    )
    text = (
        f"/* Generated by merlin.llvmlower.device_shim for device {device!r} (logical kernel ABI). Do not edit.\n"
        " * Each entry hands the kernel every pointer of its logical interface, dense row-major, in the\n"
        " * interface's own order; the kernels are supplied by the archive. */\n"
        "#include <stdint.h>\n#include <string.h>\n\n"
        f"{typedefs}\n{_RANK2_POINTER_GUARD}\n{externs}\n\n"
        + "\n".join(entries)
        + f"/* {len(emitted)} entry point(s) emitted. */\n"
    )
    return ShimUnit(text=text, symbols=tuple(emitted), kernels=tuple(sorted(kernels)), skipped=tuple(skipped))
