builtin.module attributes {prov.weights_file = "/tmp/capsule_m2m_ak_9btoh/weights.safetensors", prov.level = "linalg-on-tensors"} {
  func.func @forward(%0: tensor<1x3x8x8xbf16>, %1: tensor<16x3x2x2xbf16>) -> tensor<1x16x4x4xbf16> {
    %2 = tensor.empty() : tensor<3x2x2x1x4x4xbf16>
    %3 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d0, ((d4 * 2) + d1), ((d5 * 2) + d2))>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%0 : tensor<1x3x8x8xbf16>) outs(%2 : tensor<3x2x2x1x4x4xbf16>) attrs =  {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} {
    ^bb0(%4: bf16, %5: bf16):
      linalg.yield %4 : bf16
    } -> tensor<3x2x2x1x4x4xbf16>
    %6 = tensor.collapse_shape %3 [[0 : i64, 1 : i64, 2 : i64, 3 : i64, 4 : i64, 5 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<3x2x2x1x4x4xbf16> into tensor<192xbf16>
    %7 = tensor.expand_shape %6 [[0 : i64, 1 : i64]] output_shape [12, 16] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<192xbf16> into tensor<12x16xbf16>
    %8 = tensor.collapse_shape %1 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<16x3x2x2xbf16> into tensor<192xbf16>
    %9 = tensor.expand_shape %8 [[0 : i64, 1 : i64]] output_shape [16, 12] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<192xbf16> into tensor<16x12xbf16>
    %10 = arith.constant {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} 0.000000e+00 : bf16
    %11 = tensor.splat %10 {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<16x16xbf16>
    %12 = linalg.matmul {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} ins(%9, %7 : tensor<16x12xbf16>, tensor<12x16xbf16>) outs(%11 : tensor<16x16xbf16>) -> tensor<16x16xbf16>
    %13 = tensor.collapse_shape %12 [[0 : i64, 1 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<16x16xbf16> into tensor<256xbf16>
    %14 = tensor.expand_shape %13 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] output_shape [16, 1, 4, 4] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<256xbf16> into tensor<16x1x4x4xbf16>
    %15 = tensor.collapse_shape %14 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<16x1x4x4xbf16> into tensor<256xbf16>
    %16 = tensor.expand_shape %15 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] output_shape [1, 16, 4, 4] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "bfloat16"} : tensor<256xbf16> into tensor<1x16x4x4xbf16>
    func.return %16 : tensor<1x16x4x4xbf16>
  }
}
