"""A generated, header-free, length-taking console write for a bare-metal HTIF runtime.

The binary full-value readback transport writes its payload with ``printbuf(data, length)`` because
embedded NUL bytes are part of it (``printstr`` stops at the first one, and ``putchar`` buffers out of
order with ``printstr``). A runtime that ships no such routine gets one generated from its
ISA-headers spec's ``console_write`` block: the front-end-server proxy syscall protocol over the
runtime's own host mailbox symbols, which is exactly how that runtime's ``printf`` already reaches the
console on every engine. The protocol, the syscall number and the symbol names are data; nothing here
names a target. The source is content-addressed under ``out/build/isa_headers/<target>/`` and linked
as one more support source, so its bytes enter the build-cache key like the CRT's.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from pathlib import Path
from typing import Any

GENERATOR = "merlin.runtime.backends._chipyard_console.v1"


def render(block: Mapping[str, Any]) -> str:
    request = block["host_symbols"]["request"]
    response = block["host_symbols"]["response"]
    symbol = block["symbol"]
    return f"""/* GENERATED by {GENERATOR}. DO NOT EDIT. Length-taking console write over the HTIF proxy
 * syscall protocol ({request}/{response} mailbox); embedded NUL bytes are payload. */
#include <stddef.h>
#include <stdint.h>

extern volatile uint64_t {request};
extern volatile uint64_t {response};

int {symbol}(const void *data, size_t length) {{
  volatile uint64_t mailbox[8] __attribute__((aligned(64)));
  if (length == 0) return 0;
  mailbox[0] = {int(block["write_syscall"])};
  mailbox[1] = 1;
  mailbox[2] = (uint64_t)(uintptr_t)data;
  mailbox[3] = (uint64_t)length;
  __sync_synchronize();
  {request} = (uint64_t)(uintptr_t)mailbox;
  while ({response} == 0)
    ;
  {response} = 0;
  __sync_synchronize();
  return mailbox[0] == (uint64_t)length;
}}
"""


def materialize(target: str, block: Mapping[str, Any]) -> Path:
    """Write the source once per content and return it."""
    from merlin.common.paths import build_dir

    text = render(block)
    digest = hashlib.sha256(text.encode()).hexdigest()
    out = build_dir() / "isa_headers" / target / digest[:16] / "merlin_console_write.c"
    if out.is_file() and hashlib.sha256(out.read_bytes()).hexdigest() == digest:
        return out
    if out.exists() or out.is_symlink():
        raise ValueError(f"{out} exists with different bytes; refusing to rewrite a content-addressed source")
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(f".{digest[:8]}.tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(out)
    return out
