"""Locating the external binaries the verification layers need.

One resolver, shared by the lit harness and the SMT exporter, so a tool is never found by one layer
and missed by another. ``None`` is a first-class answer: the caller reports "unavailable" and skips.
It must never silently degrade into a pass.

``FileCheck`` resolution delegates to the existing RTL screen's candidate list rather than starting a
second one — that resolver already knows the in-tree LLVM build and the chipyard toolchain.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from merlin.common.paths import repo_root


def _llvm_bin() -> Path:
    """The in-tree LLVM build's bin dir (FileCheck/llvm-lit live here; the install tree omits them —
    it is configured with LLVM_INSTALL_UTILS=OFF)."""
    return repo_root() / "third_party" / "llvm-build" / "bin"


def find_filecheck() -> str | None:
    """Reuse the RTL screen's resolver; fall back to our own candidates if it is unavailable."""
    try:
        from merlin.targetgen.rtl_check_runner import find_filecheck as _fc
        found = _fc()
        if found:
            return found
    except Exception:
        pass
    cand = _llvm_bin() / "FileCheck"
    return str(cand) if cand.is_file() else shutil.which("FileCheck")


def find_lit() -> str | None:
    cand = _llvm_bin() / "llvm-lit"
    return str(cand) if cand.is_file() else shutil.which("llvm-lit") or shutil.which("lit")


def find_mlir_tool(name: str) -> str | None:
    """Resolve an MLIR binary (``mlir-opt``, ``mlir-translate``) from the in-tree build or install."""
    for base in (_llvm_bin(), repo_root() / "third_party" / "llvm-install" / "bin"):
        cand = base / name
        if cand.is_file():
            return str(cand)
    return shutil.which(name)


def iface_irdl() -> Path:
    """The IRDL definition of the frozen ``merlin_iface`` grammar.

    Registering this into upstream ``mlir-opt --irdl-file`` gives a structural verifier for the one
    dialect that is contractually frozen, with no code of ours in the checking path.
    """
    return repo_root() / "merlin" / "contract" / "merlin_iface.irdl.mlir"


def availability() -> dict[str, str | None]:
    """Everything the verification layers depend on, resolved. For reporting a skip honestly."""
    return {
        "FileCheck": find_filecheck(),
        "llvm-lit": find_lit(),
        "mlir-opt": find_mlir_tool("mlir-opt"),
        "mlir-translate": find_mlir_tool("mlir-translate"),
    }

# --- merlin_iface IRDL normalization (WORKAROUND, see docs/design/compiler_verification.md) --------
# The tracked IRDL is generated by `tblgen-to-irdl`, which emits a custom type's symbol name WITH its
# `!` sigil: `irdl.type @"!resident"`. That name is unspellable in MLIR text, so `mlir-opt
# --irdl-file` rejects EVERY module using `!merlin_iface.resident` or `!merlin_iface.acc` -- which is
# every real capsule interface module. The generator already normalizes a different tblgen artifact
# (`irdl.base "!builtin.string"` -> `irdl.any`) but not this one.
#
# Stripping the sigil from the declarations AND the `::@` references restores full verification,
# operand type checking included (measured: an `evict` handed a tensor is rejected with
# "expected base type 'merlin_iface.resident' but got 'builtin.tensor'").
#
# This normalization is IDEMPOTENT and becomes a no-op the moment the generator is fixed, so it can
# stay until then without hiding the defect. Fixing the generator is tracked separately; it lives
# under a package this work does not own.
_SIGIL_FIXES = (('irdl.type @"!', 'irdl.type @"'), ('::@"!', '::@"'))


def normalize_irdl_text(text: str) -> tuple[str, int]:
    """Return ``(normalized, n_substitutions)``. Zero substitutions means the source is already
    clean -- report it rather than assuming the workaround is still needed."""
    n = 0
    for bad, good in _SIGIL_FIXES:
        n += text.count(bad)
        text = text.replace(bad, good)
    return text, n


def normalized_iface_irdl() -> Path:
    """The frozen grammar's IRDL, sigil-normalized, cached under the generated-output root."""
    from merlin.common.artifacts import cache_dir

    src = iface_irdl()
    out = Path(cache_dir("verify")) / "merlin_iface.normalized.irdl.mlir"
    text, _ = normalize_irdl_text(src.read_text(encoding="utf-8"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out
