// GENERATED by merlin.targetgen.rtl.gen_iface_irdl from the reference merlin_iface ODS.
// Do not hand-edit; regenerate.
//
// Every constraint in this file is one the IRDL interpreter actually evaluates. ODS
// constraints IRDL cannot express are NOT carried here as `irdl.c_pred`: mlir-opt drops a
// c_pred from its enclosing `irdl.all_of` without a diagnostic, so such a constraint can
// never fail, and one that cannot fail reads as enforcement while providing none. These
// are what this file does NOT check; the grader does:
//   * the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
//     on: commit, conv2d, matmul, movement, resident_pack, tensor
//   * each element of the array must be a string -- IRDL has no element-wise constraint over a builtin ArrayAttr
//     on: commit, conv2d
//   * each element of the array must be a signless i64 -- IRDL has no element-wise constraint over a builtin ArrayAttr
//     on: conv2d
module {
  irdl.dialect @merlin_iface {
    irdl.type @"acc" {
      %param0 = irdl.any
      irdl.parameters(elemtype: %param0)
    }
    irdl.type @"resident" 
    irdl.operation @commit {
      %0 = irdl.base @merlin_iface::@"acc" 
      %1 = irdl.base "!builtin.tensor"
      %2 = irdl.all_of(%1)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %4 = irdl.all_of(%2)
      %5 = irdl.base "#builtin.string" 
      %6 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a string -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %8 = irdl.all_of(%6)
      %9 = irdl.base "#builtin.string" 
      irdl.operands(src: %0)
      irdl.results(result: %4)
      irdl.attributes {"name" = %5, "epilogue" = %8, "output_dtype" = %9}
    }
    irdl.operation @conv2d {
      %0 = irdl.base "!builtin.tensor"
      %1 = irdl.all_of(%0)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %3 = irdl.all_of(%1)
      %4 = irdl.base @merlin_iface::@"resident" 
      %5 = irdl.base "!builtin.tensor"
      %6 = irdl.all_of(%5)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %8 = irdl.all_of(%6)
      %9 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a signless i64 -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %11 = irdl.all_of(%9)
      %12 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a signless i64 -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %14 = irdl.all_of(%12)
      %15 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a signless i64 -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %17 = irdl.all_of(%15)
      %18 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a signless i64 -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %20 = irdl.all_of(%18)
      %21 = irdl.base "#builtin.string" 
      %22 = irdl.base "#builtin.array"
      // NOT CHECKED -- each element of the array must be a string -- IRDL has no element-wise constraint over a builtin ArrayAttr
      %24 = irdl.all_of(%22)
      %25 = irdl.base "#builtin.string" 
      %26 = irdl.base "#builtin.string" 
      irdl.operands(ifm: %3, weight: %4)
      irdl.results(result: %8)
      irdl.attributes {"kernel" = %11, "stride" = %14, "padding" = %17, "dilation" = %20, "name" = %21, "epilogue" = %24, "output_dtype" = %25, "layout" = %26}
    }
    irdl.operation @evict {
      %0 = irdl.base @merlin_iface::@"resident" 
      irdl.operands(handle: %0)
    }
    irdl.operation @matmul {
      %0 = irdl.base "!builtin.tensor"
      %1 = irdl.all_of(%0)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %3 = irdl.all_of(%1)
      %4 = irdl.base @merlin_iface::@"resident" 
      %5 = irdl.base @merlin_iface::@"acc" 
      irdl.operands(lhs: %3, rhs: %4)
      irdl.results(result: %5)
    }
    irdl.operation @movement {
      %0 = irdl.base "!builtin.tensor"
      %1 = irdl.all_of(%0)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %3 = irdl.all_of(%1)
      %4 = irdl.base "!builtin.tensor"
      %5 = irdl.all_of(%4)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %7 = irdl.all_of(%5)
      %8 = irdl.base "#builtin.string" 
      irdl.operands(src: %3)
      irdl.results(result: %7)
      irdl.attributes {"name" = %8}
    }
    irdl.operation @resident_pack {
      %0 = irdl.base "!builtin.tensor"
      %1 = irdl.all_of(%0)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %3 = irdl.all_of(%1)
      %4 = irdl.base @merlin_iface::@"resident" 
      %5 = irdl.base "#builtin.string" 
      irdl.operands(src: %3)
      irdl.results(result: %4)
      irdl.attributes {"layout" = %5}
    }
    irdl.operation @tensor {
      %0 = irdl.base "!builtin.tensor"
      %1 = irdl.all_of(%0)
      // NOT CHECKED -- the tensor element type must not be a token -- `irdl.parametric` reaches the parameters of IRDL-declared types only, not a builtin tensor's, and IRDL has no negation
      %3 = irdl.all_of(%1)
      %4 = irdl.base "#builtin.string" 
      %5 = irdl.base "#builtin.string" 
      irdl.results(result: %3)
      irdl.attributes {"name" = %4, "role" = %5}
    }
  }
}
