builtin.module attributes {prov.level = "linalg-on-tensors"} {
  func.func @forward(%0: tensor<1x1x8x8xf32>, %1: tensor<1x1x2x2xf32>) -> tensor<1x1x9x9xf32> {
    %2 = arith.constant {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} 0.000000e+00 : f32
    %3 = tensor.splat %2 {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<1x1x10x10xf32>
    %4 = "tensor.insert_slice"(%0, %3) <{static_offsets = array<i64: 0, 0, 1, 1>, static_sizes = array<i64: 1, 1, 8, 8>, static_strides = array<i64: 1, 1, 1, 1>, operandSegmentSizes = array<i32: 1, 1, 0, 0, 0>}> {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : (tensor<1x1x8x8xf32>, tensor<1x1x10x10xf32>) -> tensor<1x1x10x10xf32>
    %5 = tensor.empty() : tensor<1x2x2x1x9x9xf32>
    %6 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d3, d0, (d4 + d1), (d5 + d2))>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%4 : tensor<1x1x10x10xf32>) outs(%5 : tensor<1x2x2x1x9x9xf32>) attrs =  {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} {
    ^bb0(%7: f32, %8: f32):
      linalg.yield %7 : f32
    } -> tensor<1x2x2x1x9x9xf32>
    %9 = tensor.collapse_shape %6 [[0 : i64, 1 : i64, 2 : i64, 3 : i64, 4 : i64, 5 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<1x2x2x1x9x9xf32> into tensor<324xf32>
    %10 = tensor.expand_shape %9 [[0 : i64, 1 : i64]] output_shape [4, 81] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<324xf32> into tensor<4x81xf32>
    %11 = tensor.collapse_shape %1 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<1x1x2x2xf32> into tensor<4xf32>
    %12 = tensor.expand_shape %11 [[0 : i64, 1 : i64]] output_shape [1, 4] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<4xf32> into tensor<1x4xf32>
    %13 = arith.constant {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} 0.000000e+00 : f32
    %14 = tensor.splat %13 {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<1x81xf32>
    %15 = linalg.matmul {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} ins(%12, %10 : tensor<1x4xf32>, tensor<4x81xf32>) outs(%14 : tensor<1x81xf32>) -> tensor<1x81xf32>
    %16 = tensor.collapse_shape %15 [[0 : i64, 1 : i64]] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<1x81xf32> into tensor<81xf32>
    %17 = tensor.expand_shape %16 [[0 : i64, 1 : i64, 2 : i64, 3 : i64]] output_shape [1, 1, 9, 9] {prov.region_id = "conv_0", prov.family = "contraction", prov.conv_path = "im2col_matmul", prov._pattern_hint = "convolution_im2col_matmul", prov.op = "convolution_im2col_matmul", prov.aten = "aten.convolution.default", prov.orig_dtype = "float32"} : tensor<81xf32> into tensor<1x1x9x9xf32>
    func.return %17 : tensor<1x1x9x9xf32>
  }
}
