"""``merlin-opt`` — an MLIR opt-style driver for merlin's dialects and passes.

Why this exists: every ``// RUN:`` line in this repo named a tool that did not exist, so the
lit-shaped tests in the tree could never execute and the "MLIR standard verification flow" was
aspirational. This is that tool. It is a thin subclass of xDSL's :class:`xDSLOptMain`, so merlin's
dialects and passes are driven by exactly the machinery upstream uses.

Two design rules, both load-bearing:

**The catalog is the source of truth, not a list here.** Passes are generated by reflecting over
:func:`merlin.xdsl_dialects.lowering.passes.all_catalogs`. A pass added to the catalog appears here
with no edit; a catalog entry whose ``entry`` dotted path fails to import is a STARTUP FAILURE, never
a silent skip.

**Not every catalogued transform is an MLIR pass, and we say which.** Two entries consume a
serialized dispatch program rather than IR (their declared dialects say so:
``func -> <dispatch-program>`` and ``<dispatch-program> -> <dispatch-program>``); they take an
``OutlineResult``/``DispatchProgram``, not a ``ModuleOp``. They are reported by
``--list-merlin-passes`` as unregistrable WITH THE REASON rather than omitted, because a tool that
quietly shows 10 of 12 passes is indistinguishable from one that has 10.

Target dialects are resolved at run time from a dialect plan (``--dialect-plan`` / ``--merlin-target``)
through :mod:`merlin.xdsl_dialects.targets.factory`. The target name is a CLI value, never a literal
in this file — a target name baked into shared code is exactly the overfit the repo's gates reject.

Usage::

    merlin-opt --list-merlin-passes
    merlin-opt input.mlir -p merlin-apply-schedule
    merlin-opt input.mlir --merlin-target toy_npu -p merlin-lower-to-target
"""
from __future__ import annotations

import argparse
import importlib
import inspect
import sys
from typing import Any, Callable

from ._common import HAS_XDSL

#: Catalog entries that cannot be an MLIR pass, with the reason reported to the user. Keyed by the
#: catalog's own pass name. The reason is derived from the signature, not asserted: an entry whose
#: first parameter is not a module cannot be a ModulePass, whatever it is called.
_NOT_A_MODULE_PASS = "consumes a serialized dispatch program, not a ModuleOp"


def _resolve(entry: str) -> Callable[..., Any]:
    """Import a catalog entry's dotted path. Raises — an unimportable pass fails startup."""
    mod, _, fn = entry.rpartition(".")
    return getattr(importlib.import_module(mod), fn)


def _takes_module(fn: Callable[..., Any]) -> bool:
    """True when the callable's first positional parameter is the IR module.

    Decided from the signature's own parameter name rather than a hand list, so a new catalog entry
    classifies itself. ``module``/``op`` are IR; ``outlined``/``prog`` are the dispatch-program
    objects that cannot be a ModulePass.
    """
    params = list(inspect.signature(fn).parameters)
    return bool(params) and params[0] in ("module", "op")


def _emit_dispatch_program(module) -> str:
    """Run outline -> build_dispatch_program and print the program as stable JSON.

    `merlin-emit-dispatch-program` consumes an ``OutlineResult`` and produces a ``DispatchProgram`` --
    Python objects at both ends -- so it can never be a ModulePass and `--list-merlin-passes` reports
    it as unregistrable. That is true of the PASS, not of its OUTPUT: the program has a stable
    ``to_dict`` and printing it gives FileCheck something to read. Without this seam the obligation
    gate could never rise above 2 of 4, not because the pass is unverifiable but because nothing
    exposed its result as text.

    Sorted keys so the output is diffable and a check cannot depend on dict ordering.
    """
    import json

    from .lowering.dispatch_program import build_dispatch_program
    from .lowering.outline import outline_dispatches

    prog = build_dispatch_program(outline_dispatches(module))
    return json.dumps(prog.to_dict(), indent=2, sort_keys=True) + "\n"


def _emit_schedule(module) -> str:
    """Run the chain through partition_dispatches and print the C schedule table it renders.

    `merlin-partition-dispatches` is the same shape -- ``DispatchProgram`` in, ``PartitionResult``
    out -- but it already had a text renderer nobody had connected to a driver. Its invariant is the
    strongest of the three unverified passes (``validate`` proves every dependency edge crosses a
    level barrier upward), so exposing the table is what lets a check assert it.
    """
    from .lowering.dispatch_program import build_dispatch_program
    from .lowering.outline import outline_dispatches
    from .lowering.schedule_dispatch import emit_schedule_c, partition_dispatches

    prog = build_dispatch_program(outline_dispatches(module))
    result = partition_dispatches(prog)
    sched = getattr(result, "schedule", result)
    return emit_schedule_c(prog, sched)


#: Non-MLIR stages whose OUTPUT is stable text. Keyed by the ``--emit`` value.
EMITTERS = {
    "dispatch-program": _emit_dispatch_program,
    "schedule": _emit_schedule,
}


def _replace_body(dst, src) -> None:
    """Move ``src``'s module body into ``dst`` in place.

    The staged passes CLONE and return a new module (``lower_to_schedule`` etc.), while xDSL's pass
    API mutates the op it is given. This transplants one into the other. Ops are erased in reverse
    so an op is never erased while a later op in the same block still uses its results.
    """
    for op in reversed(list(dst.body.block.ops)):
        dst.body.block.detach_op(op)
        op.erase()
    for op in list(src.body.block.ops):
        src.body.block.detach_op(op)
        dst.body.block.add_op(op)
    dst.attributes.clear()
    dst.attributes.update(src.attributes)


def _make_pass(info) -> type:
    """Build a :class:`ModulePass` subclass for one catalog entry.

    Handles both shapes the catalog contains: an in-place mutator returning a count, and a
    clone-and-return transformer whose result must be transplanted back into ``op``.
    """
    from dataclasses import dataclass

    from xdsl.context import Context
    from xdsl.dialects import builtin
    from xdsl.passes import ModulePass

    fn = _resolve(info.entry)
    pass_name = info.name

    @dataclass(frozen=True)
    class _CatalogPass(ModulePass):
        name = pass_name

        def apply(self, ctx: Context, op: builtin.ModuleOp) -> None:
            kwargs: dict[str, Any] = {}
            params = inspect.signature(fn).parameters
            # A target-parameterized pass takes its target/plan from the driver, never a default
            # baked in here. If the driver has none, the pass's own default applies and the tool
            # says so rather than inventing one.
            plan = getattr(sys.modules[__name__], "_ACTIVE_PLAN", None)
            target = getattr(sys.modules[__name__], "_ACTIVE_TARGET", None)
            if "dialect_plan" in params and plan is not None:
                kwargs["dialect_plan"] = plan
            if "target" in params and target is not None:
                kwargs["target"] = target
            result = fn(op, **kwargs)
            if result is not None and hasattr(result, "body"):
                _replace_body(op, result)
            elif result is not None and hasattr(result, "module"):
                _replace_body(op, result.module)

    _CatalogPass.__name__ = f"MerlinPass_{pass_name.replace('-', '_')}"
    _CatalogPass.__doc__ = f"{info.summary} (obligation: {info.obligation})"
    return _CatalogPass


def merlin_passes() -> tuple[dict[str, Any], list[tuple[str, str]]]:
    """Return ``(registrable, unregistrable)``.

    ``registrable`` maps pass name -> factory. ``unregistrable`` is a list of
    ``(pass name, reason)`` — reported, never dropped.
    """
    from .lowering import passes as P

    ok: dict[str, Any] = {}
    skipped: list[tuple[str, str]] = []
    for info in P.all_catalogs():
        fn = _resolve(info.entry)          # raises on a broken catalog entry, by design
        if not _takes_module(fn):
            skipped.append((info.name, _NOT_A_MODULE_PASS))
            continue
        cls = _make_pass(info)
        ok[info.name] = (lambda c=cls: c)
    return ok, skipped


if HAS_XDSL:
    from xdsl.xdsl_opt_main import xDSLOptMain

    class MerlinOptMain(xDSLOptMain):
        """xDSL's opt driver, plus merlin's core dialects, target dialects, and pass catalog."""

        def __init__(self, args: list[str] | None = None):
            # Dialect registration happens inside super().__init__(), BEFORE arguments are parsed,
            # so the plan must be resolved from argv first. Pre-scanning is the only way a
            # run-time-resolved target dialect can be registered at all.
            self._plan, self._target = _prescan(args if args is not None else sys.argv[1:])
            global _ACTIVE_PLAN, _ACTIVE_TARGET
            _ACTIVE_PLAN, _ACTIVE_TARGET = self._plan, self._target
            self._unregistrable: list[tuple[str, str]] = []
            super().__init__(description="merlin modular optimizer driver", args=args)

        def register_all_dialects(self):
            super().register_all_dialects()
            from . import CORE_DIALECT_MODULES, fp8

            if hasattr(fp8, "register_fp8_types"):
                fp8.register_fp8_types()
            for mod in CORE_DIALECT_MODULES:
                name = mod.DIALECT_NAME
                self.ctx.register_dialect(name, (lambda m=mod: m.get_dialect()))
            if self._plan is not None or self._target is not None:
                self._register_target_dialect()

        def _register_target_dialect(self) -> None:
            """Register the target dialect named by the plan. Never a literal: the name comes from
            the plan the caller supplied."""
            from .targets import factory

            built = factory.build_dialect(self._target or "", plan=self._plan)
            dialect = getattr(built, "dialect", None)
            if dialect is not None:
                self.ctx.register_dialect(dialect.name, (lambda d=dialect: d))

        def register_all_passes(self):
            super().register_all_passes()
            ok, skipped = merlin_passes()
            self._unregistrable = skipped
            for name, factory in ok.items():
                self.register_pass(name, factory)
            # A lit run is a real pass invocation; recording it feeds the SAME evidence log the
            # obligation gate reads, so the static layer measures exercise for free.
            from .lowering import passes as P

            P.install_pass_recorder()

        def register_all_arguments(self, arg_parser: argparse.ArgumentParser):
            super().register_all_arguments(arg_parser)
            # NOTE: -t/--target is taken by xDSLOptMain (output target), hence --merlin-target.
            arg_parser.add_argument("--dialect-plan", default=None,
                                    help="path to a dialect_plan.yaml naming the target dialect")
            arg_parser.add_argument("--merlin-target", default=None,
                                    help="target name whose dialect plan to load")
            arg_parser.add_argument("--list-merlin-passes", action="store_true",
                                    help="list merlin catalog passes (and any that cannot be an "
                                         "MLIR pass, with the reason) and exit")
            arg_parser.add_argument("--emit", default=None, choices=sorted(EMITTERS),
                                    help="run a NON-MLIR stage of the dispatch chain and print its "
                                         "text. These stages consume and produce Python objects "
                                         "rather than IR, so they can never be ModulePasses -- but "
                                         "their output is stable text, which is all FileCheck needs.")

        def setup_pipeline(self):
            """Skip pipeline construction in ``--emit`` mode.

            The RUN line still carries ``-p <pass-name>`` there, and deliberately so: the verdict
            recorder credits a pass by reading that token, and a check whose subject is invisible to
            the gate discharges nothing. But these stages are not ModulePasses, so handing the name to
            ``PassPipeline.parse_spec`` raises ``Unrecognized passes``. The emit path runs the stage
            itself and never touches the pipeline, so there is nothing to build.
            """
            if getattr(self.args, "emit", None):
                from xdsl.passes import PassPipeline

                self.pipeline = PassPipeline(())
                return
            super().setup_pipeline()

        def run(self):
            if getattr(self.args, "list_merlin_passes", False):
                self._print_passes()
                return
            emit = getattr(self.args, "emit", None)
            if emit:
                print(EMITTERS[emit](self._parse_single_module()), end="")
                return
            super().run()

        def _parse_single_module(self):
            """The input module, parsed once, for the non-MLIR emitters."""
            chunks, extension = self.prepare_input()
            stream, offset = chunks[0]
            module = self.parse_chunk(stream, extension, offset)
            for extra, _ in chunks[1:]:
                extra.close()
            if module is None:
                raise SystemExit("input did not parse to a module")
            return module

        def _print_passes(self) -> None:
            from .lowering import passes as P

            by_name = {p.name: p for p in P.all_catalogs()}
            skipped = dict(self._unregistrable)
            print("merlin catalog passes:")
            for name in sorted(by_name):
                info = by_name[name]
                if name in skipped:
                    continue
                print(f"  {name:34s} {info.input_dialect} -> {info.output_dialect}"
                      f"   [{info.obligation}]")
            if skipped:
                print("\nNOT registrable as an MLIR pass (reported, not dropped):")
                for name, reason in sorted(skipped.items()):
                    print(f"  {name:34s} {reason}")


def _prescan(argv: list[str]) -> tuple[dict | None, str | None]:
    """Extract ``--dialect-plan`` / ``--merlin-target`` before the real parser runs."""
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--dialect-plan", default=None)
    pre.add_argument("--merlin-target", default=None)
    known, _ = pre.parse_known_args(argv)
    plan = None
    if known.dialect_plan:
        import yaml
        from pathlib import Path

        plan = yaml.safe_load(Path(known.dialect_plan).read_text(encoding="utf-8"))
    return plan, known.merlin_target


_ACTIVE_PLAN: dict | None = None
_ACTIVE_TARGET: str | None = None


def main() -> int:
    if not HAS_XDSL:
        sys.stderr.write("merlin-opt requires xDSL (pip install 'merlin[xdsl]')\n")
        return 2
    MerlinOptMain().run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
