#ifndef IREE_RADIANCE_COMPILER_DIALECT_RADIANCE_IR_RADIANCEDIALECT_H_
#define IREE_RADIANCE_COMPILER_DIALECT_RADIANCE_IR_RADIANCEDIALECT_H_

#include "mlir/IR/Dialect.h"

#include "compiler/src/merlin/Dialect/Radiance/IR/RadianceDialect.h.inc"

#endif // IREE_RADIANCE_COMPILER_DIALECT_RADIANCE_IR_RADIANCEDIALECT_H_
