"""The C adapter between compiled host code and a device kernel.

The host side of an offloaded contraction is an MLIR function call, and MLIR's lowered convention
passes a memref as ``(allocated, aligned, offset, sizes..., strides...)`` -- seven scalars for a rank-2
operand. The device side is the target's own kernel, whose ABI the OOT backend contract states:
``void {target}_kernel(weight, lhs_0.., out_0..)``, row-major, edge tiles zero-padded to the tile edge.
Neither side can call the other directly, so something has to unpack one convention into the other.
That is all this emits.

Deliberately NOT emitted here: the kernel itself. The device kernel is the target's own backend
artifact -- the thing its OOT package builds and the thing the capsule ladder certifies -- and
regenerating a transcription of it here would mean a model executes code no oracle ever graded. The
shim declares the kernel ``extern`` and the archive supplies it.

One structural choice worth stating: a single ``void*``-based descriptor serves every element type.
The shim only passes pointers through -- it never reads an element -- and pointer fields have the same
size and alignment whatever they point at, so the struct is ABI-identical for i8, i32, f32 or a
microscaled format alike. The alternative, a typedef per dtype, is what forces the existing
matrix-unit shim to know which dtypes exist.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

__all__ = ["KernelAbi", "ShimUnit", "emit_translation_unit", "kernel_abi_for"]

_PREAMBLE = """/* Generated by merlin.llvmlower.device_shim for device {device!r}. Do not edit.
 *
 * Adapts the MLIR lowered-memref calling convention to {device!r}'s kernel ABI. The kernel is
 * declared extern: it is the target's own backend artifact and is supplied by the archive, so what
 * a model executes is the code the capsule ladder certified rather than a transcription of it.
 */
#include <stdint.h>

/* MLIR passes a memref as (allocated, aligned, offset, sizes..., strides...) and returns it as a
 * struct of the same shape. Pointer fields have one size and alignment whatever they point at, so
 * one void*-based descriptor is ABI-identical for every element type. */
typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[2];
  intptr_t strides[2];
}} merlin_memref_2d;

typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[3];
  intptr_t strides[3];
}} merlin_memref_3d;

/* The device kernel, per the OOT backend contract's kernel_abi. Supplied by the archive. */
extern void {kernel}(void *weight, void *lhs_0, void *out_0);

{entries}
/* {n} entry point(s) emitted. */
"""

_ENTRY_2D = """
/* {symbol}: M={m} N={n} K={k}, datapath {dtypes}. Extents are re-read from the descriptors, so this
 * entry stays correct if it is ever called with others. */
merlin_memref_2d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1,
    intptr_t a_st0, intptr_t a_st1,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1,
    intptr_t b_st0, intptr_t b_st1,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1,
    intptr_t c_st0, intptr_t c_st1)
{{
  /* The generated-time extents are a CHECK, never the arithmetic: the entry reads its shape from the
   * descriptors so it stays correct if it is ever called with others, and refuses loudly if the
   * caller's shape contradicts the kernel this entry was specialized for. Silently computing the
   * wrong extent is the failure this prevents. */
  if (a_s0 != {m} || a_s1 != {k} || b_s0 != {k} || b_s1 != {n} || c_s0 != {m} || c_s1 != {n}) {{
    merlin_memref_2d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.strides[0] = 0; bad.strides[1] = 0;
    return bad;
  }}
  (void)a_alloc; (void)b_alloc; (void)a_st0; (void)a_st1; (void)b_st0; (void)b_st1;
  /* arg_order is [the single resident weight] ++ [lhs] ++ [outputs]: the rhs is the weight. */
  {kernel}((char *)b_aligned + b_off * {rhs_bytes},
           (char *)a_aligned + a_off * {lhs_bytes},
           (char *)c_aligned + c_off * {out_bytes});
  merlin_memref_2d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1;
  r.strides[0] = c_st0; r.strides[1] = c_st1;
  return r;
}}
"""


@dataclass(frozen=True)
class KernelAbi:
    """The device kernel's symbol and argument order, from the OOT backend contract."""

    symbol: str
    arg_order: str = ""
    pointee_layout: str = ""


@dataclass(frozen=True)
class ShimUnit:
    """The emitted translation unit, and what it declined."""

    text: str
    symbols: tuple[str, ...] = ()
    kernel: str = ""
    skipped: tuple[tuple[str, str], ...] = ()


def kernel_abi_for(device: str) -> KernelAbi | None:
    """The device's kernel ABI, or None when the contract cannot be read.

    The symbol pattern lives in the shared OOT backend contract rather than here, so a target that
    names its entry differently changes a declaration and not this emitter.
    """
    try:
        import yaml as _yaml

        from merlin.common.paths import merlin_dir
        path = merlin_dir() / "contract/mlir_oot_backend_contract.yaml"
        blk = ((_yaml.safe_load(path.read_text(encoding="utf-8")) or {}).get("kernel_abi") or {})
        sym = str(blk.get("symbol") or "")
        if not sym:
            return None
        return KernelAbi(symbol=sym.replace("{target}", str(device)),
                         arg_order=str(blk.get("arg_order") or ""),
                         pointee_layout=str(blk.get("pointee_layout") or ""))
    except Exception:            # noqa: BLE001 -- an unreadable contract is a real answer: decline
        return None


def _elem_bytes(token: str) -> int | None:
    """Bytes per element, or None for a sub-byte format (whose offset arithmetic is not a byte count)."""
    try:
        from merlin.targetgen.corpus_spec import dtype_info
        return dtype_info(str(token))[2]
    except Exception:            # noqa: BLE001
        return None


def emit_translation_unit(device: str,
                          signatures: Mapping[str, Sequence[int]],
                          dtypes: Mapping[str, Sequence[str]]) -> ShimUnit:
    """One entry per signature, adapting the MLIR ABI to ``device``'s kernel.

    ``signatures`` is ``{symbol: (M, N, K)}`` as minted by the offload rewrite; ``dtypes`` is
    ``{symbol: (lhs, rhs, acc)}`` from the same rewrite. They exist as separate symbols only because
    MLIR function types are monomorphic.

    A signature this cannot express -- a sub-byte format, whose element offset is not a byte count, or
    a rank this emitter has no entry shape for -- is DECLINED and reported. Emitting an entry with
    guessed pointer arithmetic would compile, link, and read the wrong bytes.
    """
    abi = kernel_abi_for(device)
    if abi is None:
        return ShimUnit(text="", skipped=(("all", "no readable kernel_abi in the backend contract"),))

    entries: list[str] = []
    emitted: list[str] = []
    skipped: list[tuple[str, str]] = []
    for sym in sorted(signatures):
        key = tuple(int(v) for v in signatures[sym])
        dt = tuple(str(d) for d in (dtypes.get(sym) or ()))
        if len(key) != 3:
            skipped.append((sym, f"rank-{len(key) - 1} signature {key}; only rank-2 entries are emitted"))
            continue
        if len(dt) != 3:
            skipped.append((sym, f"no datapath recorded for {sym}"))
            continue
        widths = [_elem_bytes(d) for d in dt]
        if any(w is None for w in widths):
            skipped.append((sym, f"sub-byte or unknown element width in {dt}; offset arithmetic "
                                 f"would be a guess"))
            continue
        m, n, k = key
        entries.append(_ENTRY_2D.format(symbol=sym, m=m, n=n, k=k, dtypes=dt, kernel=abi.symbol,
                                        lhs_bytes=widths[0], rhs_bytes=widths[1], out_bytes=widths[2]))
        emitted.append(sym)

    text = (_PREAMBLE.format(device=device, kernel=abi.symbol, entries="".join(entries),
                             n=len(emitted)) if emitted else "")
    return ShimUnit(text=text, symbols=tuple(emitted), kernel=abi.symbol, skipped=tuple(skipped))
