"""The C adapter between compiled host code and a device kernel.

The host side of an offloaded contraction is an MLIR function call, and MLIR's lowered convention
passes a memref as ``(allocated, aligned, offset, sizes..., strides...)`` -- seven scalars for a rank-2
operand. The device side is the target's own kernel, whose ABI the OOT backend contract states:
``void {target}_kernel(weight, lhs_0.., out_0..)``, row-major, edge tiles zero-padded to the tile edge.
Neither side can call the other directly, so something has to unpack one convention into the other.
That is all this emits.

Deliberately NOT emitted here: the kernel itself. The device kernel is the target's own backend
artifact -- the thing its OOT package builds and the thing the capsule ladder certifies -- and
regenerating a transcription of it here would mean a model executes code no oracle ever graded. The
shim declares the kernel ``extern`` and the archive supplies it.

One structural choice worth stating: a single ``void*``-based descriptor serves every element type.
The shim only passes pointers through -- it never reads an element -- and pointer fields have the same
size and alignment whatever they point at, so the struct is ABI-identical for i8, i32, f32 or a
microscaled format alike. The alternative, a typedef per dtype, is what forces the existing
matrix-unit shim to know which dtypes exist.
"""
from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass

__all__ = ["KernelAbi", "ShimUnit", "emit_translation_unit", "kernel_abi_for"]

_PREAMBLE = """/* Generated by merlin.llvmlower.device_shim for device {device!r}. Do not edit.
 *
 * Adapts the MLIR lowered-memref calling convention to {device!r}'s kernel ABI. The kernel is
 * declared extern: it is the target's own backend artifact and is supplied by the archive, so what
 * a model executes is the code the capsule ladder certified rather than a transcription of it.
 */
#include <stdint.h>

/* MLIR passes a memref as (allocated, aligned, offset, sizes..., strides...) and returns it as a
 * struct of the same shape. Pointer fields have one size and alignment whatever they point at, so
 * one void*-based descriptor is ABI-identical for every element type. */
typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[2];
  intptr_t strides[2];
}} merlin_memref_2d;

typedef struct {{
  void *allocated;
  void *aligned;
  intptr_t offset;
  intptr_t sizes[3];
  intptr_t strides[3];
}} merlin_memref_3d;

/* The device kernels, per the OOT backend contract's kernel_abi. Supplied by the archive.
 * One per signature: the package emits its entry under a single contract-declared name, so a model
 * with several distinct extents produces several objects that all define it. They are renamed apart
 * at build time and declared apart here; sharing one name links, and silently binds every call to
 * whichever object the linker happened to resolve first. */
{externs}

{entries}
/* {n} entry point(s) emitted. */
"""

_ENTRY_2D = """
/* {symbol}: M={m} N={n} K={k}, datapath {dtypes}. Extents are re-read from the descriptors, so this
 * entry stays correct if it is ever called with others. */
merlin_memref_2d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1,
    intptr_t a_st0, intptr_t a_st1,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1,
    intptr_t b_st0, intptr_t b_st1,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1,
    intptr_t c_st0, intptr_t c_st1)
{{
  /* The generated-time extents are a CHECK, never the arithmetic: the entry reads its shape from the
   * descriptors so it stays correct if it is ever called with others, and refuses loudly if the
   * caller's shape contradicts the kernel this entry was specialized for. Silently computing the
   * wrong extent is the failure this prevents. */
  if (a_s0 != {m} || a_s1 != {k} || b_s0 != {k} || b_s1 != {n} || c_s0 != {m} || c_s1 != {n}) {{
    merlin_memref_2d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.strides[0] = 0; bad.strides[1] = 0;
    return bad;
  }}
  (void)a_alloc; (void)b_alloc; (void)a_st0; (void)a_st1; (void)b_st0; (void)b_st1;
  /* arg_order is [the single resident weight] ++ [lhs] ++ [outputs]: the rhs is the weight. */
  {kernel}((char *)b_aligned + b_off * {rhs_bytes},
           (char *)a_aligned + a_off * {lhs_bytes},
           (char *)c_aligned + c_off * {out_bytes});
  merlin_memref_2d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1;
  r.strides[0] = c_st0; r.strides[1] = c_st1;
  return r;
}}
"""


_ENTRY_2D_PADDED = """
/* {symbol}: M={m} N={n} K={k}, datapath {dtypes}, tile edge {edge}.
 *
 * The kernel ABI states its operands are row-major with edge tiles ZERO-PADDED to a multiple of the
 * tile edge. These extents are not, so the raw buffers cannot be handed over: the kernel would stride
 * by the padded width through unpadded data and read a neighbouring row as if it were its own. That
 * does not fault -- it returns plausible, wrong numbers.
 *
 * Padded staging is therefore part of the contract, not an optimisation. Copies are byte-wise so this
 * stays independent of the element type; the row loop is the only place the extents appear. */
static unsigned char {symbol}_a[{mp} * {kp} * {lhs_bytes}];
static unsigned char {symbol}_b[{kp} * {np_} * {rhs_bytes}];
static unsigned char {symbol}_c[{mp} * {np_} * {out_bytes}];

merlin_memref_2d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1,
    intptr_t a_st0, intptr_t a_st1,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1,
    intptr_t b_st0, intptr_t b_st1,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1,
    intptr_t c_st0, intptr_t c_st1)
{{
  if (a_s0 != {m} || a_s1 != {k} || b_s0 != {k} || b_s1 != {n} || c_s0 != {m} || c_s1 != {n}) {{
    merlin_memref_2d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.strides[0] = 0; bad.strides[1] = 0;
    return bad;
  }}
  (void)a_alloc; (void)b_alloc; (void)a_st0; (void)a_st1; (void)b_st0; (void)b_st1;
  {{
    const unsigned char *src_a = (const unsigned char *)a_aligned + a_off * {lhs_bytes};
    const unsigned char *src_b = (const unsigned char *)b_aligned + b_off * {rhs_bytes};
    unsigned char *dst_c = (unsigned char *)c_aligned + c_off * {out_bytes};
    long i, j;
    for (i = 0; i < {mp} * {kp} * {lhs_bytes}; ++i) {symbol}_a[i] = 0;
    for (i = 0; i < {kp} * {np_} * {rhs_bytes}; ++i) {symbol}_b[i] = 0;
    for (i = 0; i < {mp} * {np_} * {out_bytes}; ++i) {symbol}_c[i] = 0;
    for (i = 0; i < {m}; ++i)
      for (j = 0; j < {k} * {lhs_bytes}; ++j)
        {symbol}_a[i * {kp} * {lhs_bytes} + j] = src_a[i * {k} * {lhs_bytes} + j];
    for (i = 0; i < {k}; ++i)
      for (j = 0; j < {n} * {rhs_bytes}; ++j)
        {symbol}_b[i * {np_} * {rhs_bytes} + j] = src_b[i * {n} * {rhs_bytes} + j];
    {kernel}({symbol}_b, {symbol}_a, {symbol}_c);
    for (i = 0; i < {m}; ++i)
      for (j = 0; j < {n} * {out_bytes}; ++j)
        dst_c[i * {n} * {out_bytes} + j] = {symbol}_c[i * {np_} * {out_bytes} + j];
  }}
  merlin_memref_2d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1;
  r.strides[0] = c_st0; r.strides[1] = c_st1;
  return r;
}}
"""


_ENTRY_3D = """
/* {symbol}: B={b} M={m} N={n} K={k}, datapath {dtypes}{padnote}.
 *
 * A batch is a LOOP, not a third tile axis. The device contracts two dimensions and reduces a third;
 * a batch is many of those, and each slice's operands and result are disjoint, so the batched form is
 * the same kernel called B times with the leading offset advanced. Growing a second kernel for it
 * would need its own legality and its own certification to say anything.
 *
 * The staging buffers are reused across slices, which is sound only because the slices run in
 * sequence -- that is a property of this loop, not of the buffers. */
{staging}
merlin_memref_3d {symbol}(
    void *a_alloc, void *a_aligned, intptr_t a_off, intptr_t a_s0, intptr_t a_s1, intptr_t a_s2,
    intptr_t a_st0, intptr_t a_st1, intptr_t a_st2,
    void *b_alloc, void *b_aligned, intptr_t b_off, intptr_t b_s0, intptr_t b_s1, intptr_t b_s2,
    intptr_t b_st0, intptr_t b_st1, intptr_t b_st2,
    void *c_alloc, void *c_aligned, intptr_t c_off, intptr_t c_s0, intptr_t c_s1, intptr_t c_s2,
    intptr_t c_st0, intptr_t c_st1, intptr_t c_st2)
{{
  if (a_s0 != {b} || a_s1 != {m} || a_s2 != {k} || b_s1 != {k} || b_s2 != {n}
      || c_s0 != {b} || c_s1 != {m} || c_s2 != {n}) {{
    merlin_memref_3d bad;
    bad.allocated = 0; bad.aligned = 0; bad.offset = 0;
    bad.sizes[0] = 0; bad.sizes[1] = 0; bad.sizes[2] = 0;
    bad.strides[0] = 0; bad.strides[1] = 0; bad.strides[2] = 0;
    return bad;
  }}
  (void)a_alloc; (void)b_alloc; (void)b_s0; (void)a_st1; (void)a_st2;
  (void)b_st1; (void)b_st2; (void)c_st1; (void)c_st2;
  {{
    long slice;
    for (slice = 0; slice < {b}; ++slice) {{
      const unsigned char *src_a = (const unsigned char *)a_aligned
                                 + (a_off + slice * a_st0) * {lhs_bytes};
      const unsigned char *src_b = (const unsigned char *)b_aligned
                                 + (b_off + slice * b_st0) * {rhs_bytes};
      unsigned char *dst_c = (unsigned char *)c_aligned + (c_off + slice * c_st0) * {out_bytes};
{body}
    }}
  }}
  merlin_memref_3d r;
  r.allocated = c_alloc; r.aligned = c_aligned; r.offset = c_off;
  r.sizes[0] = c_s0; r.sizes[1] = c_s1; r.sizes[2] = c_s2;
  r.strides[0] = c_st0; r.strides[1] = c_st1; r.strides[2] = c_st2;
  return r;
}}
"""

#: Direct call, when every extent already sits on the tile edge.
_BODY_3D_DIRECT = """      {kernel}((void *)src_b, (void *)src_a, (void *)dst_c);"""

#: Staged call, when an extent misses the edge. Same contract as the rank-2 padded entry.
_BODY_3D_STAGED = """      {{
        long i, j;
        for (i = 0; i < {mp} * {kp} * {lhs_bytes}; ++i) {symbol}_a[i] = 0;
        for (i = 0; i < {kp} * {np_} * {rhs_bytes}; ++i) {symbol}_b[i] = 0;
        for (i = 0; i < {mp} * {np_} * {out_bytes}; ++i) {symbol}_c[i] = 0;
        for (i = 0; i < {m}; ++i)
          for (j = 0; j < {k} * {lhs_bytes}; ++j)
            {symbol}_a[i * {kp} * {lhs_bytes} + j] = src_a[i * {k} * {lhs_bytes} + j];
        for (i = 0; i < {k}; ++i)
          for (j = 0; j < {n} * {rhs_bytes}; ++j)
            {symbol}_b[i * {np_} * {rhs_bytes} + j] = src_b[i * {n} * {rhs_bytes} + j];
        {kernel}({symbol}_b, {symbol}_a, {symbol}_c);
        for (i = 0; i < {m}; ++i)
          for (j = 0; j < {n} * {out_bytes}; ++j)
            dst_c[i * {n} * {out_bytes} + j] = {symbol}_c[i * {np_} * {out_bytes} + j];
      }}"""

_STAGING_3D = """static unsigned char {symbol}_a[{mp} * {kp} * {lhs_bytes}];
static unsigned char {symbol}_b[{kp} * {np_} * {rhs_bytes}];
static unsigned char {symbol}_c[{mp} * {np_} * {out_bytes}];"""


@dataclass(frozen=True)
class KernelAbi:
    """The device kernel's symbol and argument order, from the OOT backend contract."""

    symbol: str
    arg_order: str = ""
    pointee_layout: str = ""


@dataclass(frozen=True)
class ShimUnit:
    """The emitted translation unit, and what it declined."""

    text: str
    symbols: tuple[str, ...] = ()
    #: The contract's base kernel name (what the package emits before renaming).
    kernel: str = ""
    #: Every distinct kernel symbol this unit calls, i.e. what the archive must define.
    kernels: tuple[str, ...] = ()
    skipped: tuple[tuple[str, str], ...] = ()


def kernel_abi_for(device: str) -> KernelAbi | None:
    """The device's kernel ABI, or None when the contract cannot be read.

    The symbol pattern lives in the shared OOT backend contract rather than here, so a target that
    names its entry differently changes a declaration and not this emitter.
    """
    try:
        import yaml as _yaml

        from merlin.common.paths import merlin_dir
        path = merlin_dir() / "contract/mlir_oot_backend_contract.yaml"
        blk = ((_yaml.safe_load(path.read_text(encoding="utf-8")) or {}).get("kernel_abi") or {})
        sym = str(blk.get("symbol") or "")
        if not sym:
            return None
        return KernelAbi(symbol=sym.replace("{target}", str(device)),
                         arg_order=str(blk.get("arg_order") or ""),
                         pointee_layout=str(blk.get("pointee_layout") or ""))
    except Exception:            # noqa: BLE001 -- an unreadable contract is a real answer: decline
        return None


def tile_edge_for(device: str) -> int | None:
    """The device's mesh tile edge, derived from its own RTL facts; None when not derivable.

    None is a real answer and the caller must then refuse to emit a padded entry: padding to a guessed
    edge is worse than not padding, because it produces a differently-wrong buffer.
    """
    try:
        from merlin.targetgen.rtl import facts as _f
        body = (_f.load_facts(device) or {}).get("facts") or {}
    except Exception:            # noqa: BLE001
        return None
    for arr in (body.get("arrays") or ()):
        rows, cols = arr.get("rows"), arr.get("cols")
        if rows and cols:
            return int(min(int(rows), int(cols)))
    return None


def _elem_bytes(token: str) -> int | None:
    """Bytes per element, or None for a sub-byte format (whose offset arithmetic is not a byte count)."""
    try:
        from merlin.targetgen.corpus_spec import dtype_info
        return dtype_info(str(token))[2]
    except Exception:            # noqa: BLE001
        return None


def emit_translation_unit(device: str,
                          signatures: Mapping[str, Sequence[int]],
                          dtypes: Mapping[str, Sequence[str]],
                          *,
                          kernel_symbol_for: "Callable[[str], str] | None" = None,
                          tile_edge: int | None = None) -> ShimUnit:
    """One entry per signature, adapting the MLIR ABI to ``device``'s kernel.

    ``signatures`` is ``{symbol: (M, N, K)}`` as minted by the offload rewrite; ``dtypes`` is
    ``{symbol: (lhs, rhs, acc)}`` from the same rewrite. They exist as separate symbols only because
    MLIR function types are monomorphic.

    A signature this cannot express -- a sub-byte format, whose element offset is not a byte count, or
    a rank this emitter has no entry shape for -- is DECLINED and reported. Emitting an entry with
    guessed pointer arithmetic would compile, link, and read the wrong bytes.
    """
    abi = kernel_abi_for(device)
    if abi is None:
        return ShimUnit(text="", skipped=(("all", "no readable kernel_abi in the backend contract"),))
    # One kernel per signature by default is WRONG for a package that emits a single contract-named
    # entry, and one shared kernel is wrong for a model with several extents. The caller decides,
    # because only the caller knows how the objects were built and renamed.
    kernel_for = kernel_symbol_for or (lambda _sym: abi.symbol)

    entries: list[str] = []
    emitted: list[str] = []
    skipped: list[tuple[str, str]] = []
    for sym in sorted(signatures):
        key = tuple(int(v) for v in signatures[sym])
        dt = tuple(str(d) for d in (dtypes.get(sym) or ()))
        if len(key) not in (3, 4):
            skipped.append((sym, f"signature {key} has neither 3 nor 4 extents; no entry shape for it"))
            continue
        if len(dt) != 3:
            skipped.append((sym, f"no datapath recorded for {sym}"))
            continue
        widths = [_elem_bytes(d) for d in dt]
        if any(w is None for w in widths):
            skipped.append((sym, f"sub-byte or unknown element width in {dt}; offset arithmetic "
                                 f"would be a guess"))
            continue
        batch, (m, n, k) = ((None, key) if len(key) == 3 else (key[0], key[1:]))
        edge = tile_edge if tile_edge is not None else tile_edge_for(device)
        if not edge:
            # Without the edge we cannot know whether this entry needs staging, and emitting the
            # unpadded form "because we did not find out" is the exact failure that produced a model
            # scoring cos 0.9847 where it should score 0.99993. Not knowing is a decline.
            skipped.append((sym, "no derivable tile edge, so whether these extents need padded "
                                 "staging is unknown; declining rather than emitting the raw form"))
            continue
        needs_pad = any(int(x) % int(edge) for x in (m, n, k))
        def _up(v):
            return ((int(v) + int(edge) - 1) // int(edge)) * int(edge)

        shape = dict(symbol=sym, m=m, n=n, k=k, dtypes=dt, kernel=kernel_for(sym),
                     mp=_up(m), np_=_up(n), kp=_up(k),
                     lhs_bytes=widths[0], rhs_bytes=widths[1], out_bytes=widths[2])
        if batch is None:
            entries.append((_ENTRY_2D_PADDED if needs_pad else _ENTRY_2D).format(
                edge=int(edge), **shape))
        else:
            body = (_BODY_3D_STAGED if needs_pad else _BODY_3D_DIRECT).format(**shape)
            staging = _STAGING_3D.format(**shape) if needs_pad else ""
            entries.append(_ENTRY_3D.format(
                b=int(batch), staging=staging, body=body,
                padnote=(f", tile edge {int(edge)} (staged)" if needs_pad else ""), **shape))
        emitted.append(sym)

    kernels = sorted({kernel_for(sym) for sym in emitted})
    externs = "\n".join(f"extern void {k}(void *weight, void *lhs_0, void *out_0);" for k in kernels)
    text = (_PREAMBLE.format(device=device, externs=externs, entries="".join(entries),
                             n=len(emitted)) if emitted else "")
    return ShimUnit(text=text, symbols=tuple(emitted), kernel=abi.symbol,
                    kernels=tuple(kernels), skipped=tuple(skipped))
