"""Bind existing harvester observations to public bytes without promoting their fidelity.

The host supplies the explicitly public workload allowlist and pinned raw artifacts. This module
does not discover files, read hidden grades, execute a target, fit rates, or authorize target timing.
Unlike an isolated-latency bound, a historical program count needs no assumption that removing
contention can only reduce latency. It remains a reference for that program and measurement window.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence
import hashlib
import json
import math
from typing import Any

from .harvest import Observation
from .work_volume import work_from_command_buffer


def _digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _document_digest(doc: Mapping[str, Any]) -> str:
    return _digest(json.dumps(doc, sort_keys=True, separators=(",", ":"), allow_nan=False).encode())


def _sha(value: Any) -> bool:
    return isinstance(value, str) and len(value) == 64 and all(c in "0123456789abcdef" for c in value)


def _object(raw: bytes) -> dict[str, Any]:
    def pairs(items):
        out = {}
        for key, value in items:
            if key in out:
                raise ValueError("duplicate JSON field in historical evidence")
            out[key] = value
        return out
    doc = json.loads(raw, object_pairs_hook=pairs)
    if not isinstance(doc, dict):
        raise ValueError("historical evidence must be a JSON object")
    _document_digest(doc)  # Reject non-finite values, even outside the selected tier.
    return doc


def bind_historical_reference(observation: Observation, *, target: str, receipt: bytes,
        receipt_sha256: str, receipt_path: str, public_workloads: set[str] | frozenset[str],
        artifacts: Mapping[str, bytes], artifact_sha256: Mapping[str, str],
        executable_names: Sequence[str], harness_name: str,
        command_buffer_name: str | None = None) -> dict[str, Any]:
    """Recheck an admitted harvester row against exact public receipt and generated bytes.

    ``public_workloads`` is host-derived from the frozen public grade, not candidate input.
    Artifact hashes establish retained bytes, not an independent proof that this ELF was executed.
    Historical execution lineage remains named explicitly; no old certificate is rewritten.
    """
    if not isinstance(target, str) or not target or not receipt_path:
        raise ValueError("target and public receipt identity are required")
    if not isinstance(receipt, bytes) or not _sha(receipt_sha256) or _digest(receipt) != receipt_sha256:
        raise ValueError("historical receipt bytes differ from their host pin")
    doc = _object(receipt)
    if (doc.get("label") not in {"public", "dev"} or doc.get("capsule") not in public_workloads
            or doc.get("capsule") != observation.workload):
        raise ValueError("observation is not the explicitly allowed public workload")
    if doc.get("target") not in (None, target):
        raise ValueError("historical receipt target differs from the host-bound target")
    stages = doc.get("tiers")
    row = stages.get(observation.stage) if isinstance(stages, Mapping) else None
    cycles = row.get("cycles") if isinstance(row, Mapping) else None
    if (observation.quantity != "total_cycles" or observation.unit != "cycles"
            or observation.status != "pass" or not isinstance(row, Mapping)
            or row.get("status") != "pass" or isinstance(cycles, bool)
            or not isinstance(cycles, (int, float)) or not math.isfinite(cycles) or cycles <= 0
            or isinstance(observation.value, bool) or observation.value != cycles):
        raise ValueError("historical observation does not match a positive passing raw cycle row")
    if (set(artifacts) != set(artifact_sha256) or not executable_names
            or isinstance(executable_names, (str, bytes))
            or len(set(executable_names)) != len(executable_names)):
        raise ValueError("exact artifact pins and unique executable names are required")
    required = {*executable_names, harness_name}
    if command_buffer_name is not None:
        required.add(command_buffer_name)
    if not required <= set(artifacts):
        raise ValueError("historical executable, harness or command buffer bytes are missing")
    for name, raw in artifacts.items():
        if not isinstance(raw, bytes) or not _sha(artifact_sha256[name]) or _digest(raw) != artifact_sha256[name]:
            raise ValueError("historical artifact bytes differ from their host pin")

    work: dict[str, Any] | None = None
    command_buffer = None
    work_location = None
    if command_buffer_name is not None:
        command_buffer = _object(artifacts[command_buffer_name])
        work_location = command_buffer_name
    elif isinstance(doc.get("command_buffer_artifact"), Mapping):
        embedded = doc["command_buffer_artifact"]
        if isinstance(embedded.get("command_buffer"), Mapping):
            command_buffer = embedded["command_buffer"]
            if embedded.get("artifact_sha256") != _document_digest(command_buffer):
                raise ValueError("embedded historical command buffer identity changed")
            work_location = "receipt#/command_buffer_artifact/command_buffer"
    if command_buffer is not None:
        work = work_from_command_buffer(command_buffer).to_dict()
        historical_work = doc.get("work_volume") or {}
        if historical_work.get("artifact_sha256") != work["artifact_sha256"]:
            raise ValueError("retained command buffer does not match historical work identity")
    sim = row.get("sim_provenance") or {}
    engine_sha = sim.get("sha256")
    config_sha = row.get("engine_config_sha256") or sim.get("config_sha256")
    counter_sha = row.get("counter_semantics_sha256")
    missing = [name for name, value in (("engine_binary", engine_sha),
        ("engine_configuration", config_sha), ("counter_semantics", counter_sha)) if not _sha(value)]
    # Raw declared fields are evidence to inspect, not a host-verified ROI contract.
    missing.extend(("host_verified_warm_window", "physical_byte_counters", "independent_timing_validation"))
    if work is None or work["exact_macs"] is None:
        missing.append("exact_command_work")
    hardware = doc.get("toolchain_shas") or {}
    if not isinstance(hardware, Mapping):
        raise ValueError("historical toolchain identities must be a mapping")
    result = {
        "schema": "historical_program_reference_v1", "target": target,
        "submission": observation.submission, "workload": observation.workload,
        "stage": observation.stage, "declared_measurement_tier": observation.tier,
        "status": "pass", "cycles": cycles, "unit": "cycles",
        "engine": row.get("engine"), "engine_binary_sha256": engine_sha,
        "engine_configuration_sha256": config_sha, "counter_semantics_sha256": counter_sha,
        "toolchain_shas": dict(hardware), "receipt_path": receipt_path,
        "receipt_sha256": receipt_sha256, "artifact_sha256": dict(artifact_sha256),
        "executable_sha256": {name: artifact_sha256[name] for name in executable_names},
        "harness_sha256": artifact_sha256[harness_name],
        "retained_asset_binding": "host-pinned retained bytes; historical execution lineage is separate",
        "carried": dict(row.get("carried") or {}),
        "window": "UNKNOWN", "declared_measurement_contract": row.get("measurement_contract"),
        "work": work, "work_location": work_location,
        "work_scope": "receipt-bound compiler command buffer, not hardware work counters",
        "physical_moved_bytes": None, "physical_movement_basis": "UNKNOWN",
        "usable_as": "historical_engine_relative_proxy" if _sha(engine_sha) else "diagnostic_only",
        "target_cycle_authority": False, "warm_calibration": False,
        "physical_roofline_complete": False, "full_model_cycle_ordering": "UNKNOWN",
        "missing_contracts": missing,
    }
    result["reference_sha256"] = _document_digest(result)
    return result


def reference_summary(records: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    """Compact agent-facing inventory; no pooling into a latency, peak, rank or fitted constant."""
    unique: dict[str, Mapping[str, Any]] = {}
    for record in records:
        raw = dict(record)
        identity = raw.pop("reference_sha256", None)
        if (raw.get("schema") != "historical_program_reference_v1" or identity != _document_digest(raw)
                or raw.get("target_cycle_authority") is not False
                or raw.get("warm_calibration") is not False):
            raise ValueError("historical reference identity/authority changed")
        unique[identity] = record
    groups: dict[str, dict[str, Any]] = {}
    for identity, record in sorted(unique.items()):
        group_identity = {key: record[key] for key in ("target", "engine", "engine_binary_sha256",
            "engine_configuration_sha256", "counter_semantics_sha256", "window", "toolchain_shas")}
        key = _document_digest(group_identity)
        group = groups.setdefault(key, {"identity": group_identity, "references": [],
                                       "comparable_schedule_ranking": "UNKNOWN"})
        work = record.get("work") or {}
        exact = work.get("exact_macs")
        group["references"].append({"reference_sha256": identity, "workload": record["workload"],
            "cycles": record["cycles"], "executable_sha256": record["executable_sha256"],
            "harness_sha256": record["harness_sha256"], "command_macs": exact,
            "command_macs_per_observed_cycle": exact / record["cycles"]
                if type(exact) is int and exact > 0 else None,
            "rate_interpretation": "historical command-work ratio; not a hardware peak or cycle bound",
            "missing_contracts": list(record["missing_contracts"])})
    return {"schema": "historical_reference_summary_v1", "reference_count": len(unique),
            "engine_groups": groups, "target_cycle_authority": False,
            "warm_calibration": False, "physical_roofline_complete": False,
            "full_model_cycle_ordering": "UNKNOWN",
            "next_action": "Match the changed source mechanism with a short warm paired probe; "
                           "do not extrapolate these historical ratios into full-model latency."}
