"""Generate the target-repo skeleton: root files, per-directory AGENT.md, contracts, docs.

The skeleton is always fully created (all layer directories exist with an AGENT.md) so the
generated repo passes structural checks regardless of which ``--emit`` flags are set. The
per-layer *content* (xDSL dialect, MLIR scaffold, Zephyr module, runtime adapter, LLVM plan)
is produced by the sibling generators and gated by ``--emit``.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ...common.artifacts import Artifact, yaml_artifact

# Top-level directories of a generated target repo, with AGENT.md purpose text.
TOP_LEVEL_DIRS: dict[str, str] = {
    "docs": "Generated, human-reviewable documentation for this target (architecture, ISA, "
            "lowering, runtime, zephyr, llvm) plus the evidence and validation reports.",
    "contracts": "The five synchronized plan artifacts (target_contract, dialect_plan, "
                 "runtime_adapter_plan, zephyr_plan, llvm_extension_plan).",
    "xdsl": "Fast xDSL prototype of the target dialect. Promote to MLIR/C++ once stable.",
    "include": "Public C++/ODS headers for the target dialect (placeholder scaffold).",
    "lib": "C++ implementation of the target dialect and its transforms (placeholder scaffold).",
    "tools": "Target-specific opt/translate/run tool entry points (placeholder).",
    "runtime": "Target-side runtime ADAPTER (not a runtime). Implements the Merlin runtime "
               "ABI: command encoding, simulator semantics, metrics mapping.",
    "zephyr": "Zephyr runtime-backend module: devicetree binding, Kconfig, driver, samples.",
    "llvm": "LLVM extension plan and (placeholder) out-of-tree TableGen/patches/tests.",
    "examples": "Example MLIR/kernels/workloads demonstrating this target.",
    "tests": "lit/unit/conformance/lowering/execution/golden tests for this target.",
}

# Files that the sibling generators write; used to render contextual AGENT.md notes.
_AGENT_NOTES: dict[str, str] = {
    "runtime": "Merlin owns the runtime ABI and command-buffer schema; this directory only "
               "ADAPTS them. Never define an independent runtime model here.",
    "llvm": "Default to out-of-tree. A fork is only justified by the plan's fork_triggers.",
    "xdsl": "If xDSL is not installed the prototype still imports as plain Python with TODOs.",
}


def camel(target: str) -> str:
    """Return a CamelCase token for a target name (toy_npu -> ToyNPU)."""
    special = {"toy_npu": "ToyNPU"}
    if target in special:
        return special[target]
    return "".join(part.capitalize() for part in target.split("_"))


def agent_md(
    rel_dir: str,
    purpose: str,
    belongs: list[str],
    not_belongs: list[str],
    interfaces: list[str],
    invariants: list[str],
    testing: list[str],
    notes: list[str],
) -> str:
    """Render an AGENT.md using the repo's 7-section template."""
    def block(items: list[str]) -> str:
        return "\n".join(f"- {i}" for i in items) if items else "- (none)"

    return (
        f"# AGENT.md — {rel_dir}\n\n"
        f"## Purpose\n\n{purpose}\n\n"
        f"## What belongs here\n\n{block(belongs)}\n\n"
        f"## What does not belong here\n\n{block(not_belongs)}\n\n"
        f"## Interfaces\n\n{block(interfaces)}\n\n"
        f"## Invariants\n\n{block(invariants)}\n\n"
        f"## Testing expectations\n\n{block(testing)}\n\n"
        f"## Notes for future agents\n\n{block(notes)}\n"
    )


def _dir_agent_md(rel_dir: str, purpose: str, target: str) -> Artifact:
    notes = [_AGENT_NOTES[rel_dir]] if rel_dir in _AGENT_NOTES else [
        "Generated by merlin.targetgen; safe to edit by hand after review."
    ]
    return Artifact(
        relpath=f"{rel_dir}/AGENT.md",
        content=agent_md(
            rel_dir=f"merlin-target-{target}/{rel_dir}",
            purpose=purpose,
            belongs=["Files appropriate to the purpose above."],
            not_belongs=["Unrelated code; generated build outputs; vendored external repos."],
            interfaces=["See contracts/ for the plans that drive this directory's generation."],
            invariants=["Keep this directory focused on its stated purpose.",
                        "Every subdirectory must also contain an AGENT.md."],
            testing=["Update tests/ when this directory's contracts change."],
            notes=notes,
        ),
    )


def _root_readme(target: str) -> str:
    return (
        f"# merlin-target-{target}\n\n"
        f"Generated Merlin target package for `{target}`.\n\n"
        "This repository was scaffolded by `merlin.targetgen`. It is **human-reviewable**: "
        "the generator does not claim its synthesized artifacts are correct. Start from "
        "`contracts/` and `docs/evidence_report.md`.\n\n"
        "## Layout\n\n"
        "- `contracts/` — the five synchronized plans\n"
        "- `xdsl/` — xDSL prototype dialect\n"
        "- `include/`, `lib/`, `tools/` — MLIR/C++ dialect scaffold (placeholder)\n"
        "- `runtime/` — Merlin runtime **adapter** (command encoding, simulator, metrics)\n"
        "- `zephyr/` — Zephyr runtime-backend module\n"
        "- `llvm/` — LLVM extension plan (out-of-tree first)\n"
        "- `examples/`, `tests/`, `docs/`\n\n"
        "## Core rule\n\n"
        "Merlin owns the core dialects (`contract`/`schedule`/`interface`/`runtime`) and the runtime "
        "abstraction. This target only provides a dialect + a runtime adapter.\n"
    )


def _root_agent_md(target: str) -> str:
    return agent_md(
        rel_dir=f"merlin-target-{target}",
        purpose=f"Generated Merlin target package for `{target}` (dialect + runtime adapter).",
        belongs=["Target dialect (xDSL prototype + MLIR/C++ scaffold), runtime adapter, "
                 "Zephyr module, LLVM extension plan, examples, tests, and the five contracts."],
        not_belongs=["Merlin core dialects or the runtime ABI (those live in the Merlin repo).",
                     "An independent runtime model — this target only adapts the Merlin runtime."],
        interfaces=["Consumes the Merlin runtime ABI, command-buffer schema, and metrics schema.",
                    "contracts/*.yaml validate against merlin/schemas/*.schema.yaml."],
        invariants=["Targets implement adapters; they never invent runtime models.",
                    "Every directory contains an AGENT.md."],
        testing=["`python build_tools/scripts/check_generated_target.py <this repo>` must pass."],
        notes=["Regenerate with `python -m merlin.targetgen.cli build --target-name "
               f"{target} ...`. Hand-edits after review are expected."],
    )


def _pyproject(target: str) -> str:
    return (
        "[build-system]\n"
        'requires = ["setuptools>=61"]\n'
        'build-backend = "setuptools.build_meta"\n\n'
        "[project]\n"
        f'name = "merlin-target-{target.replace("_", "-")}"\n'
        'version = "0.0.1"\n'
        f'description = "Generated Merlin target package for {target}"\n'
        'requires-python = ">=3.10"\n'
    )


def _cmakelists(target: str) -> str:
    return (
        "# Placeholder CMake for the generated target dialect scaffold.\n"
        "# Not expected to build yet; wired up once the MLIR/C++ scaffold is real.\n"
        "cmake_minimum_required(VERSION 3.20)\n"
        f"project(MerlinTarget{camel(target)} LANGUAGES CXX)\n"
    )


def generate_skeleton(target: str) -> list[Artifact]:
    """Root files + per-top-level-directory AGENT.md."""
    arts: list[Artifact] = [
        Artifact("README.md", _root_readme(target)),
        Artifact("AGENT.md", _root_agent_md(target)),
        Artifact("pyproject.toml", _pyproject(target)),
        Artifact("CMakeLists.txt", _cmakelists(target)),
    ]
    for rel, purpose in TOP_LEVEL_DIRS.items():
        arts.append(_dir_agent_md(rel, purpose, target))
    return arts


def emit_contracts(plans: dict[str, Any]) -> list[Artifact]:
    """Write the five plan YAMLs under contracts/."""
    headers = {
        "target_contract": "Generated target contract (validates against target_contract.schema.yaml).",
        "dialect_plan": "Generated dialect plan (validates against dialect_plan.schema.yaml).",
        "runtime_adapter_plan": "Generated runtime adapter plan (runtime_adapter_plan.schema.yaml).",
        "zephyr_plan": "Generated Zephyr plan (zephyr_plan.schema.yaml).",
        "llvm_extension_plan": "Generated LLVM extension plan (llvm_extension_plan.schema.yaml).",
    }
    arts: list[Artifact] = []
    for stem, obj in plans.items():
        arts.append(yaml_artifact(f"contracts/{stem}.yaml", obj, header=headers.get(stem)))
    return arts


def emit_docs(evidence_md: str, validation_md: str, target: str) -> list[Artifact]:
    """Write docs/evidence_report.md, docs/validation_report.md, and stub docs."""
    stub = lambda title: (  # noqa: E731
        f"# {title} — {target}\n\n_Placeholder generated by merlin.targetgen. "
        "Fill in after human review of the evidence report._\n"
    )
    return [
        Artifact("docs/evidence_report.md", evidence_md),
        Artifact("docs/validation_report.md", validation_md),
        Artifact("docs/architecture.md", stub("Architecture")),
        Artifact("docs/isa.md", stub("ISA")),
        Artifact("docs/dialect.md", stub("Dialect")),
        Artifact("docs/lowering.md", stub("Lowering")),
        Artifact("docs/runtime.md", stub("Runtime")),
        Artifact("docs/zephyr.md", stub("Zephyr")),
        Artifact("docs/llvm.md", stub("LLVM")),
    ]


_GENERIC_AGENT_MD = (
    "# AGENT.md — {rel}\n\n"
    "## Purpose\n\nGenerated sub-directory of a Merlin target package.\n\n"
    "## What belongs here\n\n- Files appropriate to the parent directory's purpose.\n\n"
    "## What does not belong here\n\n- Unrelated code or generated build outputs.\n\n"
    "## Interfaces\n\n- See the parent directory's AGENT.md and contracts/.\n\n"
    "## Invariants\n\n- Keep focused on the parent directory's purpose.\n"
    "- Every subdirectory must also contain an AGENT.md.\n\n"
    "## Testing expectations\n\n- Covered by the target repo's tests/.\n\n"
    "## Notes for future agents\n\n- Auto-seeded by merlin.targetgen; edit freely.\n"
)


def backfill_agent_md(repo: str | Path) -> list[Path]:
    """Filesystem pass: seed a generic AGENT.md into any directory lacking one.

    Run after all artifacts are written so every directory the sub-generators created has
    AGENT.md coverage. Returns the list of AGENT.md files created.
    """
    repo = Path(repo)
    created: list[Path] = []
    for d in sorted(p for p in repo.rglob("*") if p.is_dir()):
        if d.name.startswith(".") or d.name == "__pycache__":
            continue
        agent = d / "AGENT.md"
        if not agent.is_file():
            rel = d.relative_to(repo)
            agent.write_text(_GENERIC_AGENT_MD.format(rel=f"merlin-target-*/{rel}"), encoding="utf-8")
            created.append(agent)
    return created
